// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { UserCreateSchema } from './user.create.zod.js'

export const UserUpdateSchema = UserCreateSchema.partial()

export type UserUpdateInput = z.infer<typeof UserUpdateSchema>
