// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { AccountStatus } from '@prisma/client'

export const UserQuerySchema = z.object({
  skip: z.coerce.number().min(0).optional(),
  take: z.coerce.number().min(1).max(100).optional().default(20),
  orderBy: z.object({
    id: z.enum(['asc', 'desc']).optional(),
    email: z.enum(['asc', 'desc']).optional(),
    passwordHash: z.enum(['asc', 'desc']).optional(),
    oauthProvider: z.enum(['asc', 'desc']).optional(),
    oauthId: z.enum(['asc', 'desc']).optional(),
    accountStatus: z.enum(['asc', 'desc']).optional(),
    createdAt: z.enum(['asc', 'desc']).optional(),
    updatedAt: z.enum(['asc', 'desc']).optional(),
    lastLoginAt: z.enum(['asc', 'desc']).optional(),
    profile: z.record(z.enum(['asc', 'desc'])).optional(),
    photos: z.record(z.enum(['asc', 'desc'])).optional(),
    swipesAsSwiper: z.record(z.enum(['asc', 'desc'])).optional(),
    swipesAsSwiped: z.record(z.enum(['asc', 'desc'])).optional(),
    matchesAsUser1: z.record(z.enum(['asc', 'desc'])).optional(),
    matchesAsUser2: z.record(z.enum(['asc', 'desc'])).optional(),
    messagesSent: z.record(z.enum(['asc', 'desc'])).optional(),
    messagesReceived: z.record(z.enum(['asc', 'desc'])).optional(),
    quizAnswers: z.record(z.enum(['asc', 'desc'])).optional(),
    quizResults: z.record(z.enum(['asc', 'desc'])).optional(),
    behaviorEvents: z.record(z.enum(['asc', 'desc'])).optional(),
    userDimensionScores: z.record(z.enum(['asc', 'desc'])).optional(),
    userDimensionPriorities: z.record(z.enum(['asc', 'desc'])).optional(),
    compatibilityScoresAsUser1: z.record(z.enum(['asc', 'desc'])).optional(),
    compatibilityScoresAsUser2: z.record(z.enum(['asc', 'desc'])).optional(),
    blocksAsBlocker: z.record(z.enum(['asc', 'desc'])).optional(),
    blocksAsBlocked: z.record(z.enum(['asc', 'desc'])).optional()
  }).optional(),
  where: z.object({
    id: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    email: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    passwordHash: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional(),
      isNull: z.boolean().optional()
    }).optional(),
    oauthProvider: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional(),
      isNull: z.boolean().optional()
    }).optional(),
    oauthId: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional(),
      isNull: z.boolean().optional()
    }).optional(),
    accountStatus: z.nativeEnum(AccountStatus).optional(),
    createdAt: z.object({
      equals: z.coerce.date().optional(),
      gt: z.coerce.date().optional(),
      gte: z.coerce.date().optional(),
      lt: z.coerce.date().optional(),
      lte: z.coerce.date().optional()
    }).optional(),
    lastLoginAt: z.object({
      equals: z.coerce.date().optional(),
      gt: z.coerce.date().optional(),
      gte: z.coerce.date().optional(),
      lt: z.coerce.date().optional(),
      lte: z.coerce.date().optional(),
      isNull: z.boolean().optional()
    }).optional()
  }).optional(),
  include: z.object({
    profile: z.boolean().optional(),
    photos: z.boolean().optional(),
    swipesAsSwiper: z.boolean().optional(),
    swipesAsSwiped: z.boolean().optional(),
    matchesAsUser1: z.boolean().optional(),
    matchesAsUser2: z.boolean().optional(),
    messagesSent: z.boolean().optional(),
    messagesReceived: z.boolean().optional(),
    quizAnswers: z.boolean().optional(),
    quizResults: z.boolean().optional(),
    behaviorEvents: z.boolean().optional(),
    userDimensionScores: z.boolean().optional(),
    userDimensionPriorities: z.boolean().optional(),
    compatibilityScoresAsUser1: z.boolean().optional(),
    compatibilityScoresAsUser2: z.boolean().optional(),
    blocksAsBlocker: z.boolean().optional(),
    blocksAsBlocked: z.boolean().optional()
  }).optional(),
  select: z.object({
    id: z.boolean().optional(),
    email: z.boolean().optional(),
    passwordHash: z.boolean().optional(),
    oauthProvider: z.boolean().optional(),
    oauthId: z.boolean().optional(),
    accountStatus: z.boolean().optional(),
    createdAt: z.boolean().optional(),
    updatedAt: z.boolean().optional(),
    lastLoginAt: z.boolean().optional(),
    profile: z.boolean().optional(),
    photos: z.boolean().optional(),
    swipesAsSwiper: z.boolean().optional(),
    swipesAsSwiped: z.boolean().optional(),
    matchesAsUser1: z.boolean().optional(),
    matchesAsUser2: z.boolean().optional(),
    messagesSent: z.boolean().optional(),
    messagesReceived: z.boolean().optional(),
    quizAnswers: z.boolean().optional(),
    quizResults: z.boolean().optional(),
    behaviorEvents: z.boolean().optional(),
    userDimensionScores: z.boolean().optional(),
    userDimensionPriorities: z.boolean().optional(),
    compatibilityScoresAsUser1: z.boolean().optional(),
    compatibilityScoresAsUser2: z.boolean().optional(),
    blocksAsBlocker: z.boolean().optional(),
    blocksAsBlocked: z.boolean().optional()
  }).optional()
})

export type UserQueryInput = z.infer<typeof UserQuerySchema>
