// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { AccountStatus } from '@prisma/client'

export const UserCreateSchema = z.object({
  email: z.string().min(1, 'email is required'),
  passwordHash: z.string().nullable().optional(),
  oauthProvider: z.string().nullable().optional(),
  oauthId: z.string().nullable().optional(),
  accountStatus: z.nativeEnum(AccountStatus).optional().default("ACTIVE"),
  createdAt: z.coerce.date().optional().default(new Date()),
  lastLoginAt: z.coerce.date().nullable().optional()
})

export type UserCreateInput = z.infer<typeof UserCreateSchema>
