// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { EventType } from '@prisma/client'

export const EventWeightConfigCreateSchema = z.object({
  eventType: z.nativeEnum(EventType),
  baseWeight: z.number(),
  isActive: z.boolean().optional().default(true),
  description: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional().default(new Date())
})

export type EventWeightConfigCreateInput = z.infer<typeof EventWeightConfigCreateSchema>
