// @generated
// This file is automatically generated. Do not edit manually.

import type { 
  EventWeightConfig, 
  EventWeightConfigCreate, 
  EventWeightConfigUpdate, 
  EventWeightConfigQuery,
  ListResponse 
} from '../../types'
import type { SDK } from '../../index'
import { stableKey } from './shared/query-helpers'

/**
 * EventWeightConfig query factory - accepts API client for flexibility
 * 
 * These are pure query definitions that work with ANY SDK instance.
 * Inject your configured client via factory pattern.
 */
export function createEventWeightConfigQueries(api: SDK) {
  return {
    /**
     * Core queries - Standard CRUD operations
     */
    all: {
      /**
       * Get single EventWeightConfig by ID
       */
      get: (id: string) => ({
        queryKey: stableKey('eventweightconfig', id),
        queryFn: async (): Promise<EventWeightConfig | null> => {
          const result = await api.eventweightconfig.get(id)
          return result || null
        }
      }),
      
      /**
       * List EventWeightConfig records
       */
      list: (query?: EventWeightConfigQuery) => ({
        queryKey: stableKey('eventweightconfigs', query),
        queryFn: async (): Promise<ListResponse<EventWeightConfig>> => {
          const result = await api.eventweightconfig.list(query)
          return result || { data: [], meta: { total: 0, skip: 0, take: 20, hasMore: false } }
        }
      }),
      
      /**
       * Find EventWeightConfig by any field
       */
      findOne: (where: Partial<EventWeightConfig>) => ({
        queryKey: ['eventweightconfig', 'query', JSON.stringify(where)],
        queryFn: async (): Promise<EventWeightConfig | null> => {
          const result = await api.eventweightconfig.findOne(where)
          return result || null
        }
      }),
      
      /**
       * Count EventWeightConfig records
       */
      count: (query?: Pick<EventWeightConfigQuery, 'where'>) => ({
        queryKey: stableKey('eventweightconfigs:count', query),
        queryFn: async (): Promise<number> => {
          const result = await api.eventweightconfig.count(query as Partial<EventWeightConfigQuery>)
          return result || 0
        }
      })
    }
  }
}

/**
 * EventWeightConfig mutation factory - accepts API client
 */
export function createEventWeightConfigMutations(api: SDK) {
  return {
    /**
     * Create EventWeightConfig
     */
    create: () => ({
      mutationKey: ['eventweightconfig', 'create'] as const,
      mutationFn: async (data: EventWeightConfigCreate): Promise<EventWeightConfig> => 
        api.eventweightconfig.create(data)
    }),
    
    /**
     * Update EventWeightConfig
     */
    update: () => ({
      mutationKey: ['eventweightconfig', 'update'] as const,
      mutationFn: async ({ id, data }: { id: string; data: EventWeightConfigUpdate }): Promise<EventWeightConfig | null> => 
        api.eventweightconfig.update(id, data)
    }),
    
    /**
     * Delete EventWeightConfig
     */
    delete: () => ({
      mutationKey: ['eventweightconfig', 'delete'] as const,
      mutationFn: async (id: string): Promise<boolean> => 
        api.eventweightconfig.delete(id)
    })
  }
}

/**
 * EventWeightConfig infinite query factory - accepts API client
 */
export function createEventWeightConfigInfinite(api: SDK) {
  return {
    /**
     * Infinite scroll EventWeightConfig list
     */
    list: (query?: Omit<EventWeightConfigQuery, 'skip'>) => {
      const pageSize = query?.take || 20
      
      return {
        queryKey: stableKey('eventweightconfigs:infinite', query),
        queryFn: async (context: { pageParam: number }) => {
          const page = context.pageParam || 0
          return api.eventweightconfig.list({
            ...query,
            skip: page * pageSize,
            take: pageSize
          })
        },
        getNextPageParam: (lastPage: ListResponse<EventWeightConfig>, allPages: any[]) =>
          lastPage.meta.hasMore ? allPages.length : undefined,
        initialPageParam: 0
      }
    }
  }
}
