// @generated
// This file is automatically generated. Do not edit manually.

import type { 
  Profile, 
  ProfileCreate, 
  ProfileUpdate, 
  ProfileQuery,
  ListResponse 
} from '../../types'
import type { SDK } from '../../index'
import { stableKey } from './shared/query-helpers'

/**
 * Profile query factory - accepts API client for flexibility
 * 
 * These are pure query definitions that work with ANY SDK instance.
 * Inject your configured client via factory pattern.
 */
export function createProfileQueries(api: SDK) {
  return {
    /**
     * Core queries - Standard CRUD operations
     */
    all: {
      /**
       * Get single Profile by ID
       */
      get: (id: string) => ({
        queryKey: stableKey('profile', id),
        queryFn: async (): Promise<Profile | null> => {
          const result = await api.profile.get(id)
          return result || null
        }
      }),
      
      /**
       * List Profile records
       */
      list: (query?: ProfileQuery) => ({
        queryKey: stableKey('profiles', query),
        queryFn: async (): Promise<ListResponse<Profile>> => {
          const result = await api.profile.list(query)
          return result || { data: [], meta: { total: 0, skip: 0, take: 20, hasMore: false } }
        }
      }),
      
      /**
       * Find Profile by any field
       */
      findOne: (where: Partial<Profile>) => ({
        queryKey: ['profile', 'query', JSON.stringify(where)],
        queryFn: async (): Promise<Profile | null> => {
          const result = await api.profile.findOne(where)
          return result || null
        }
      }),
      
      /**
       * Count Profile records
       */
      count: (query?: Pick<ProfileQuery, 'where'>) => ({
        queryKey: stableKey('profiles:count', query),
        queryFn: async (): Promise<number> => {
          const result = await api.profile.count(query as Partial<ProfileQuery>)
          return result || 0
        }
      })
    }
  }
}

/**
 * Profile mutation factory - accepts API client
 */
export function createProfileMutations(api: SDK) {
  return {
    /**
     * Create Profile
     */
    create: () => ({
      mutationKey: ['profile', 'create'] as const,
      mutationFn: async (data: ProfileCreate): Promise<Profile> => 
        api.profile.create(data)
    }),
    
    /**
     * Update Profile
     */
    update: () => ({
      mutationKey: ['profile', 'update'] as const,
      mutationFn: async ({ id, data }: { id: string; data: ProfileUpdate }): Promise<Profile | null> => 
        api.profile.update(id, data)
    }),
    
    /**
     * Delete Profile
     */
    delete: () => ({
      mutationKey: ['profile', 'delete'] as const,
      mutationFn: async (id: string): Promise<boolean> => 
        api.profile.delete(id)
    })
  }
}

/**
 * Profile infinite query factory - accepts API client
 */
export function createProfileInfinite(api: SDK) {
  return {
    /**
     * Infinite scroll Profile list
     */
    list: (query?: Omit<ProfileQuery, 'skip'>) => {
      const pageSize = query?.take || 20
      
      return {
        queryKey: stableKey('profiles:infinite', query),
        queryFn: async (context: { pageParam: number }) => {
          const page = context.pageParam || 0
          return api.profile.list({
            ...query,
            skip: page * pageSize,
            take: pageSize
          })
        },
        getNextPageParam: (lastPage: ListResponse<Profile>, allPages: any[]) =>
          lastPage.meta.hasMore ? allPages.length : undefined,
        initialPageParam: 0
      }
    }
  }
}
