// @generated
// This file is automatically generated. Do not edit manually.

import type { 
  QuizResult, 
  QuizResultCreate, 
  QuizResultUpdate, 
  QuizResultQuery,
  ListResponse 
} from '../../types'
import type { SDK } from '../../index'
import { stableKey } from './shared/query-helpers'

/**
 * QuizResult query factory - accepts API client for flexibility
 * 
 * These are pure query definitions that work with ANY SDK instance.
 * Inject your configured client via factory pattern.
 */
export function createQuizResultQueries(api: SDK) {
  return {
    /**
     * Core queries - Standard CRUD operations
     */
    all: {
      /**
       * Get single QuizResult by ID
       */
      get: (id: string) => ({
        queryKey: stableKey('quizresult', id),
        queryFn: async (): Promise<QuizResult | null> => {
          const result = await api.quizresult.get(id)
          return result || null
        }
      }),
      
      /**
       * List QuizResult records
       */
      list: (query?: QuizResultQuery) => ({
        queryKey: stableKey('quizresults', query),
        queryFn: async (): Promise<ListResponse<QuizResult>> => {
          const result = await api.quizresult.list(query)
          return result || { data: [], meta: { total: 0, skip: 0, take: 20, hasMore: false } }
        }
      }),
      
      /**
       * Find QuizResult by any field
       */
      findOne: (where: Partial<QuizResult>) => ({
        queryKey: ['quizresult', 'query', JSON.stringify(where)],
        queryFn: async (): Promise<QuizResult | null> => {
          const result = await api.quizresult.findOne(where)
          return result || null
        }
      }),
      
      /**
       * Count QuizResult records
       */
      count: (query?: Pick<QuizResultQuery, 'where'>) => ({
        queryKey: stableKey('quizresults:count', query),
        queryFn: async (): Promise<number> => {
          const result = await api.quizresult.count(query as Partial<QuizResultQuery>)
          return result || 0
        }
      })
    }
  }
}

/**
 * QuizResult mutation factory - accepts API client
 */
export function createQuizResultMutations(api: SDK) {
  return {
    /**
     * Create QuizResult
     */
    create: () => ({
      mutationKey: ['quizresult', 'create'] as const,
      mutationFn: async (data: QuizResultCreate): Promise<QuizResult> => 
        api.quizresult.create(data)
    }),
    
    /**
     * Update QuizResult
     */
    update: () => ({
      mutationKey: ['quizresult', 'update'] as const,
      mutationFn: async ({ id, data }: { id: string; data: QuizResultUpdate }): Promise<QuizResult | null> => 
        api.quizresult.update(id, data)
    }),
    
    /**
     * Delete QuizResult
     */
    delete: () => ({
      mutationKey: ['quizresult', 'delete'] as const,
      mutationFn: async (id: string): Promise<boolean> => 
        api.quizresult.delete(id)
    })
  }
}

/**
 * QuizResult infinite query factory - accepts API client
 */
export function createQuizResultInfinite(api: SDK) {
  return {
    /**
     * Infinite scroll QuizResult list
     */
    list: (query?: Omit<QuizResultQuery, 'skip'>) => {
      const pageSize = query?.take || 20
      
      return {
        queryKey: stableKey('quizresults:infinite', query),
        queryFn: async (context: { pageParam: number }) => {
          const page = context.pageParam || 0
          return api.quizresult.list({
            ...query,
            skip: page * pageSize,
            take: pageSize
          })
        },
        getNextPageParam: (lastPage: ListResponse<QuizResult>, allPages: any[]) =>
          lastPage.meta.hasMore ? allPages.length : undefined,
        initialPageParam: 0
      }
    }
  }
}
