// @generated
// This file is automatically generated. Do not edit manually.

import type { 
  UserDimensionPriority, 
  UserDimensionPriorityCreate, 
  UserDimensionPriorityUpdate, 
  UserDimensionPriorityQuery,
  ListResponse 
} from '../../types'
import type { SDK } from '../../index'
import { stableKey } from './shared/query-helpers'

/**
 * UserDimensionPriority query factory - accepts API client for flexibility
 * 
 * These are pure query definitions that work with ANY SDK instance.
 * Inject your configured client via factory pattern.
 */
export function createUserDimensionPriorityQueries(api: SDK) {
  return {
    /**
     * Core queries - Standard CRUD operations
     */
    all: {
      /**
       * Get single UserDimensionPriority by ID
       */
      get: (id: string) => ({
        queryKey: stableKey('userdimensionpriority', id),
        queryFn: async (): Promise<UserDimensionPriority | null> => {
          const result = await api.userdimensionpriority.get(id)
          return result || null
        }
      }),
      
      /**
       * List UserDimensionPriority records
       */
      list: (query?: UserDimensionPriorityQuery) => ({
        queryKey: stableKey('userdimensionprioritys', query),
        queryFn: async (): Promise<ListResponse<UserDimensionPriority>> => {
          const result = await api.userdimensionpriority.list(query)
          return result || { data: [], meta: { total: 0, skip: 0, take: 20, hasMore: false } }
        }
      }),
      
      /**
       * Find UserDimensionPriority by any field
       */
      findOne: (where: Partial<UserDimensionPriority>) => ({
        queryKey: ['userdimensionpriority', 'query', JSON.stringify(where)],
        queryFn: async (): Promise<UserDimensionPriority | null> => {
          const result = await api.userdimensionpriority.findOne(where)
          return result || null
        }
      }),
      
      /**
       * Count UserDimensionPriority records
       */
      count: (query?: Pick<UserDimensionPriorityQuery, 'where'>) => ({
        queryKey: stableKey('userdimensionprioritys:count', query),
        queryFn: async (): Promise<number> => {
          const result = await api.userdimensionpriority.count(query as Partial<UserDimensionPriorityQuery>)
          return result || 0
        }
      })
    }
  }
}

/**
 * UserDimensionPriority mutation factory - accepts API client
 */
export function createUserDimensionPriorityMutations(api: SDK) {
  return {
    /**
     * Create UserDimensionPriority
     */
    create: () => ({
      mutationKey: ['userdimensionpriority', 'create'] as const,
      mutationFn: async (data: UserDimensionPriorityCreate): Promise<UserDimensionPriority> => 
        api.userdimensionpriority.create(data)
    }),
    
    /**
     * Update UserDimensionPriority
     */
    update: () => ({
      mutationKey: ['userdimensionpriority', 'update'] as const,
      mutationFn: async ({ id, data }: { id: string; data: UserDimensionPriorityUpdate }): Promise<UserDimensionPriority | null> => 
        api.userdimensionpriority.update(id, data)
    }),
    
    /**
     * Delete UserDimensionPriority
     */
    delete: () => ({
      mutationKey: ['userdimensionpriority', 'delete'] as const,
      mutationFn: async (id: string): Promise<boolean> => 
        api.userdimensionpriority.delete(id)
    })
  }
}

/**
 * UserDimensionPriority infinite query factory - accepts API client
 */
export function createUserDimensionPriorityInfinite(api: SDK) {
  return {
    /**
     * Infinite scroll UserDimensionPriority list
     */
    list: (query?: Omit<UserDimensionPriorityQuery, 'skip'>) => {
      const pageSize = query?.take || 20
      
      return {
        queryKey: stableKey('userdimensionprioritys:infinite', query),
        queryFn: async (context: { pageParam: number }) => {
          const page = context.pageParam || 0
          return api.userdimensionpriority.list({
            ...query,
            skip: page * pageSize,
            take: pageSize
          })
        },
        getNextPageParam: (lastPage: ListResponse<UserDimensionPriority>, allPages: any[]) =>
          lastPage.meta.hasMore ? allPages.length : undefined,
        initialPageParam: 0
      }
    }
  }
}
