// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { SwipeCreateSchema } from './swipe.create.zod.js'

export const SwipeUpdateSchema = SwipeCreateSchema.partial()

export type SwipeUpdateInput = z.infer<typeof SwipeUpdateSchema>
