// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { SwipeType } from '@prisma/client'

export const SwipeQuerySchema = z.object({
  skip: z.coerce.number().min(0).optional(),
  take: z.coerce.number().min(1).max(100).optional().default(20),
  orderBy: z.object({
    id: z.enum(['asc', 'desc']).optional(),
    swiperId: z.enum(['asc', 'desc']).optional(),
    swipedId: z.enum(['asc', 'desc']).optional(),
    type: z.enum(['asc', 'desc']).optional(),
    createdAt: z.enum(['asc', 'desc']).optional(),
    swiper: z.record(z.enum(['asc', 'desc'])).optional(),
    swiped: z.record(z.enum(['asc', 'desc'])).optional()
  }).optional(),
  where: z.object({
    id: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    swiperId: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    swipedId: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    type: z.nativeEnum(SwipeType).optional(),
    createdAt: z.object({
      equals: z.coerce.date().optional(),
      gt: z.coerce.date().optional(),
      gte: z.coerce.date().optional(),
      lt: z.coerce.date().optional(),
      lte: z.coerce.date().optional()
    }).optional()
  }).optional(),
  include: z.object({
    swiper: z.boolean().optional(),
    swiped: z.boolean().optional()
  }).optional(),
  select: z.object({
    id: z.boolean().optional(),
    swiperId: z.boolean().optional(),
    swipedId: z.boolean().optional(),
    type: z.boolean().optional(),
    createdAt: z.boolean().optional(),
    swiper: z.boolean().optional(),
    swiped: z.boolean().optional()
  }).optional()
})

export type SwipeQueryInput = z.infer<typeof SwipeQuerySchema>
