// @generated
// This file is automatically generated. Do not edit manually.

import type { UserDimensionPriorityUpdateInput } from '@/validators/user-dimension-priority/user-dimension-priority.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see UserDimensionPriorityUpdateSchema in validators
 */
export type UserDimensionPriorityUpdateDTO = UserDimensionPriorityUpdateInput
