// @generated
// This file is automatically generated. Do not edit manually.

import type { DimensionMappingRuleUpdateInput } from '@/validators/dimension-mapping-rule/dimension-mapping-rule.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see DimensionMappingRuleUpdateSchema in validators
 */
export type DimensionMappingRuleUpdateDTO = DimensionMappingRuleUpdateInput
