// @generated
// This file is automatically generated. Do not edit manually.

import {
  BaseCRUDController
} from '../../base/index.js'
import { userDimensionScoreService } from '../../services/user-dimension-score/index.js'
import {
  UserDimensionScoreCreateSchema,
  UserDimensionScoreUpdateSchema,
  UserDimensionScoreQuerySchema
} from '../../validators/user-dimension-score/index.js'

/**
 * UserDimensionScore CRUD Controller
 * Using BaseCRUDController to eliminate boilerplate
 */
const userDimensionScoreCRUD = new BaseCRUDController(
  userDimensionScoreService,
  {
    create: UserDimensionScoreCreateSchema,
    update: UserDimensionScoreUpdateSchema,
    query: UserDimensionScoreQuerySchema
  } as any,
  {
    modelName: 'UserDimensionScore',
    idType: 'string'
  }
)


// Standard CRUD operations
export const listUserDimensionScores = userDimensionScoreCRUD.list.bind(userDimensionScoreCRUD)
export const searchUserDimensionScores = userDimensionScoreCRUD.search.bind(userDimensionScoreCRUD)
export const getUserDimensionScore = userDimensionScoreCRUD.getById.bind(userDimensionScoreCRUD)
export const createUserDimensionScore = userDimensionScoreCRUD.create.bind(userDimensionScoreCRUD)
export const updateUserDimensionScore = userDimensionScoreCRUD.update.bind(userDimensionScoreCRUD)
export const deleteUserDimensionScore = userDimensionScoreCRUD.deleteRecord.bind(userDimensionScoreCRUD)
export const countUserDimensionScores = userDimensionScoreCRUD.count.bind(userDimensionScoreCRUD)

// Bulk operations
export const bulkCreateUserDimensionScores = userDimensionScoreCRUD.bulkCreate.bind(userDimensionScoreCRUD)
export const bulkUpdateUserDimensionScores = userDimensionScoreCRUD.bulkUpdate.bind(userDimensionScoreCRUD)
export const bulkDeleteUserDimensionScores = userDimensionScoreCRUD.bulkDelete.bind(userDimensionScoreCRUD)
