// @generated
// This file is automatically generated. Do not edit manually.

import type { PhotoReadDTO } from './photo.read.dto.js'

type PhotoWhereInput = {
    id?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    url?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    order?: number | {
      equals?: number
      gt?: number
      gte?: number
      lt?: number
      lte?: number
      in?: number[]
      notIn?: number[]
      not?: number
    }
    moderationStatus?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    createdAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    AND?: PhotoWhereInput[]
    OR?: PhotoWhereInput[]
    NOT?: PhotoWhereInput[]
  }

export interface PhotoQueryDTO {
  skip?: number  // Offset pagination (should be >= 0)
  take?: number  // Limit (should be > 0)
  cursor?: string  // Cursor for cursor-based pagination
  orderBy?: {
    id?: 'asc' | 'desc'
    userId?: 'asc' | 'desc'
    url?: 'asc' | 'desc'
    order?: 'asc' | 'desc'
    moderationStatus?: 'asc' | 'desc'
    createdAt?: 'asc' | 'desc'
    updatedAt?: 'asc' | 'desc'
    user?: { [key: string]: 'asc' | 'desc' }
  }
  where?: PhotoWhereInput
  include?: {
    user?: boolean | { include?: any; select?: any }
  }
  select?: {
    id?: boolean
    userId?: boolean
    url?: boolean
    order?: boolean
    moderationStatus?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    user?: boolean | { select?: any; include?: any }
  }
  distinct?: 'id' | 'url' | 'order' | 'moderationStatus' | 'createdAt' | Array<'id' | 'url' | 'order' | 'moderationStatus' | 'createdAt'>
}

export interface PhotoListResponse {
  data: PhotoReadDTO[]
  meta: {
    total: number
    skip: number
    take: number
    hasMore: boolean  // Calculated as: skip + take < total
  }
}
