// @generated
// This file is automatically generated. Do not edit manually.

import type { PhotoCreateInput } from '@/validators/photo/photo.create.zod.js'

/**
 * Create DTO - Derived from Zod schema (single source of truth)
 * @see PhotoCreateSchema in validators
 */
export type PhotoCreateDTO = PhotoCreateInput
