// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { EventType, TargetType } from '@prisma/client'

export const BehaviorEventArchiveQuerySchema = z.object({
  skip: z.coerce.number().min(0).optional(),
  take: z.coerce.number().min(1).max(100).optional().default(20),
  orderBy: z.object({
    id: z.enum(['asc', 'desc']).optional(),
    userId: z.enum(['asc', 'desc']).optional(),
    eventType: z.enum(['asc', 'desc']).optional(),
    targetType: z.enum(['asc', 'desc']).optional(),
    targetId: z.enum(['asc', 'desc']).optional(),
    meta: z.enum(['asc', 'desc']).optional(),
    processedAt: z.enum(['asc', 'desc']).optional(),
    ruleVersion: z.enum(['asc', 'desc']).optional(),
    createdAt: z.enum(['asc', 'desc']).optional(),
    archivedAt: z.enum(['asc', 'desc']).optional()
  }).optional(),
  where: z.object({
    id: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    userId: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    eventType: z.nativeEnum(EventType).optional(),
    targetType: z.nativeEnum(TargetType).optional(),
    targetId: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    processedAt: z.object({
      equals: z.coerce.date().optional(),
      gt: z.coerce.date().optional(),
      gte: z.coerce.date().optional(),
      lt: z.coerce.date().optional(),
      lte: z.coerce.date().optional(),
      isNull: z.boolean().optional()
    }).optional(),
    ruleVersion: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional(),
      isNull: z.boolean().optional()
    }).optional(),
    createdAt: z.object({
      equals: z.coerce.date().optional(),
      gt: z.coerce.date().optional(),
      gte: z.coerce.date().optional(),
      lt: z.coerce.date().optional(),
      lte: z.coerce.date().optional()
    }).optional(),
    archivedAt: z.object({
      equals: z.coerce.date().optional(),
      gt: z.coerce.date().optional(),
      gte: z.coerce.date().optional(),
      lt: z.coerce.date().optional(),
      lte: z.coerce.date().optional()
    }).optional()
  }).optional(),
  include: z.record(z.boolean()).optional(),
  select: z.object({
    id: z.boolean().optional(),
    userId: z.boolean().optional(),
    eventType: z.boolean().optional(),
    targetType: z.boolean().optional(),
    targetId: z.boolean().optional(),
    meta: z.boolean().optional(),
    processedAt: z.boolean().optional(),
    ruleVersion: z.boolean().optional(),
    createdAt: z.boolean().optional(),
    archivedAt: z.boolean().optional()
  }).optional()
})

export type BehaviorEventArchiveQueryInput = z.infer<typeof BehaviorEventArchiveQuerySchema>
