// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { BehaviorEventArchiveCreateSchema } from './behavior-event-archive.create.zod.js'

export const BehaviorEventArchiveUpdateSchema = BehaviorEventArchiveCreateSchema.partial()

export type BehaviorEventArchiveUpdateInput = z.infer<typeof BehaviorEventArchiveUpdateSchema>
