// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'

export const QuizAnswerQuerySchema = z.object({
  skip: z.coerce.number().min(0).optional(),
  take: z.coerce.number().min(1).max(100).optional().default(20),
  orderBy: z.object({
    id: z.enum(['asc', 'desc']).optional(),
    quizId: z.enum(['asc', 'desc']).optional(),
    questionId: z.enum(['asc', 'desc']).optional(),
    userId: z.enum(['asc', 'desc']).optional(),
    answerJson: z.enum(['asc', 'desc']).optional(),
    createdAt: z.enum(['asc', 'desc']).optional(),
    quiz: z.record(z.enum(['asc', 'desc'])).optional(),
    question: z.record(z.enum(['asc', 'desc'])).optional(),
    user: z.record(z.enum(['asc', 'desc'])).optional()
  }).optional(),
  where: z.object({
    id: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    quizId: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    questionId: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    userId: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    createdAt: z.object({
      equals: z.coerce.date().optional(),
      gt: z.coerce.date().optional(),
      gte: z.coerce.date().optional(),
      lt: z.coerce.date().optional(),
      lte: z.coerce.date().optional()
    }).optional()
  }).optional(),
  include: z.object({
    quiz: z.boolean().optional(),
    question: z.boolean().optional(),
    user: z.boolean().optional()
  }).optional(),
  select: z.object({
    id: z.boolean().optional(),
    quizId: z.boolean().optional(),
    questionId: z.boolean().optional(),
    userId: z.boolean().optional(),
    answerJson: z.boolean().optional(),
    createdAt: z.boolean().optional(),
    quiz: z.boolean().optional(),
    question: z.boolean().optional(),
    user: z.boolean().optional()
  }).optional()
})

export type QuizAnswerQueryInput = z.infer<typeof QuizAnswerQuerySchema>
