// @generated
// This file is automatically generated. Do not edit manually.

import type { BehaviorEventArchiveCreateInput } from '@/validators/behavior-event-archive/behavior-event-archive.create.zod.js'

/**
 * Create DTO - Derived from Zod schema (single source of truth)
 * @see BehaviorEventArchiveCreateSchema in validators
 */
export type BehaviorEventArchiveCreateDTO = BehaviorEventArchiveCreateInput
