// @generated
// This file is automatically generated. Do not edit manually.

export interface MessageReadDTO {
  id: string
  matchId: string
  senderId: string
  receiverId: string
  content: string
  messageType: string
  readAt: Date | null
  createdAt: Date
}
