// @generated
// This file is automatically generated. Do not edit manually.

import type { MessageCreateInput } from '@/validators/message/message.create.zod.js'

/**
 * Create DTO - Derived from Zod schema (single source of truth)
 * @see MessageCreateSchema in validators
 */
export type MessageCreateDTO = MessageCreateInput
