// @generated
// This file is automatically generated. Do not edit manually.

import type { MessageUpdateInput } from '@/validators/message/message.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see MessageUpdateSchema in validators
 */
export type MessageUpdateDTO = MessageUpdateInput
