// @generated
// This file is automatically generated. Do not edit manually.

import type { MessageReadDTO } from './message.read.dto.js'

type MessageWhereInput = {
    id?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    content?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    messageType?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    readAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
      isNull?: boolean
    }
    createdAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    AND?: MessageWhereInput[]
    OR?: MessageWhereInput[]
    NOT?: MessageWhereInput[]
  }

export interface MessageQueryDTO {
  skip?: number  // Offset pagination (should be >= 0)
  take?: number  // Limit (should be > 0)
  cursor?: string  // Cursor for cursor-based pagination
  orderBy?: {
    id?: 'asc' | 'desc'
    matchId?: 'asc' | 'desc'
    senderId?: 'asc' | 'desc'
    receiverId?: 'asc' | 'desc'
    content?: 'asc' | 'desc'
    messageType?: 'asc' | 'desc'
    readAt?: 'asc' | 'desc'
    createdAt?: 'asc' | 'desc'
    match?: { [key: string]: 'asc' | 'desc' }
    sender?: { [key: string]: 'asc' | 'desc' }
    receiver?: { [key: string]: 'asc' | 'desc' }
  }
  where?: MessageWhereInput
  include?: {
    match?: boolean | { include?: any; select?: any }
    sender?: boolean | { include?: any; select?: any }
    receiver?: boolean | { include?: any; select?: any }
  }
  select?: {
    id?: boolean
    matchId?: boolean
    senderId?: boolean
    receiverId?: boolean
    content?: boolean
    messageType?: boolean
    readAt?: boolean
    createdAt?: boolean
    match?: boolean | { select?: any; include?: any }
    sender?: boolean | { select?: any; include?: any }
    receiver?: boolean | { select?: any; include?: any }
  }
  distinct?: 'id' | 'content' | 'messageType' | 'readAt' | 'createdAt' | Array<'id' | 'content' | 'messageType' | 'readAt' | 'createdAt'>
}

export interface MessageListResponse {
  data: MessageReadDTO[]
  meta: {
    total: number
    skip: number
    take: number
    hasMore: boolean  // Calculated as: skip + take < total
  }
}
