// @generated
// This file is automatically generated. Do not edit manually.

import { Router, type Router as RouterType } from 'express'
import * as photoController from '@/controllers/photo/index.js'

export const photoRouter: RouterType = Router()

// List all Photo records (simple pagination)
photoRouter.get('/', photoController.listPhotos)

// Search Photo records (complex filtering via POST body)
photoRouter.post('/search', photoController.searchPhotos)

// Get Photo by ID
photoRouter.get('/:id', photoController.getPhoto)

// Create Photo
photoRouter.post('/', photoController.createPhoto)

// Update Photo
photoRouter.put('/:id', photoController.updatePhoto)
photoRouter.patch('/:id', photoController.updatePhoto)

// Delete Photo
photoRouter.delete('/:id', photoController.deletePhoto)

// Count Photo records
photoRouter.get('/meta/count', photoController.countPhotos)

// Bulk operations
photoRouter.post('/bulk/create', photoController.bulkCreatePhotos)
photoRouter.put('/bulk/update', photoController.bulkUpdatePhotos)
photoRouter.delete('/bulk/delete', photoController.bulkDeletePhotos)

