// @generated
// This file is automatically generated. Do not edit manually.

import type { EventWeightConfigCreateInput } from '@/validators/event-weight-config/event-weight-config.create.zod.js'

/**
 * Create DTO - Derived from Zod schema (single source of truth)
 * @see EventWeightConfigCreateSchema in validators
 */
export type EventWeightConfigCreateDTO = EventWeightConfigCreateInput
