// @generated
// This file is automatically generated. Do not edit manually.

import { EventType } from '@prisma/client'

import type { EventWeightConfigReadDTO } from './event-weight-config.read.dto.js'

type EventWeightConfigWhereInput = {
    id?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    eventType?: EventType | {
      equals?: EventType
      in?: EventType[]
      notIn?: EventType[]
      not?: EventType
    }
    baseWeight?: number | {
      equals?: number
      gt?: number
      gte?: number
      lt?: number
      lte?: number
      in?: number[]
      notIn?: number[]
      not?: number
    }
    isActive?: boolean | {
      equals?: boolean
      not?: boolean
    }
    description?: string | null | {
      equals?: string | null
      contains?: string | null
      startsWith?: string | null
      endsWith?: string | null
      in?: string | null[]
      notIn?: string | null[]
      not?: string | null
      mode?: 'default' | 'insensitive'
      isNull?: boolean
    }
    createdAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    AND?: EventWeightConfigWhereInput[]
    OR?: EventWeightConfigWhereInput[]
    NOT?: EventWeightConfigWhereInput[]
  }

export interface EventWeightConfigQueryDTO {
  skip?: number  // Offset pagination (should be >= 0)
  take?: number  // Limit (should be > 0)
  cursor?: string  // Cursor for cursor-based pagination
  orderBy?: {
    id?: 'asc' | 'desc'
    eventType?: 'asc' | 'desc'
    baseWeight?: 'asc' | 'desc'
    isActive?: 'asc' | 'desc'
    description?: 'asc' | 'desc'
    createdAt?: 'asc' | 'desc'
    updatedAt?: 'asc' | 'desc'
  }
  where?: EventWeightConfigWhereInput
  include?: Record<string, boolean | { include?: any; select?: any }>
  select?: {
    id?: boolean
    eventType?: boolean
    baseWeight?: boolean
    isActive?: boolean
    description?: boolean
    createdAt?: boolean
    updatedAt?: boolean
  }
  distinct?: 'id' | 'eventType' | 'baseWeight' | 'isActive' | 'description' | 'createdAt' | Array<'id' | 'eventType' | 'baseWeight' | 'isActive' | 'description' | 'createdAt'>
}

export interface EventWeightConfigListResponse {
  data: EventWeightConfigReadDTO[]
  meta: {
    total: number
    skip: number
    take: number
    hasMore: boolean  // Calculated as: skip + take < total
  }
}
