// @generated
// This file is automatically generated. Do not edit manually.

import type { EventWeightConfigUpdateInput } from '@/validators/event-weight-config/event-weight-config.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see EventWeightConfigUpdateSchema in validators
 */
export type EventWeightConfigUpdateDTO = EventWeightConfigUpdateInput
