// @generated
// This file is automatically generated. Do not edit manually.

import type { 
  BehaviorEvent, 
  BehaviorEventCreate, 
  BehaviorEventUpdate, 
  BehaviorEventQuery,
  ListResponse 
} from '../../types'
import type { SDK } from '../../index'
import { stableKey } from './shared/query-helpers'

/**
 * BehaviorEvent query factory - accepts API client for flexibility
 * 
 * These are pure query definitions that work with ANY SDK instance.
 * Inject your configured client via factory pattern.
 */
export function createBehaviorEventQueries(api: SDK) {
  return {
    /**
     * Core queries - Standard CRUD operations
     */
    all: {
      /**
       * Get single BehaviorEvent by ID
       */
      get: (id: string) => ({
        queryKey: stableKey('behaviorevent', id),
        queryFn: async (): Promise<BehaviorEvent | null> => {
          const result = await api.behaviorevent.get(id)
          return result || null
        }
      }),
      
      /**
       * List BehaviorEvent records
       */
      list: (query?: BehaviorEventQuery) => ({
        queryKey: stableKey('behaviorevents', query),
        queryFn: async (): Promise<ListResponse<BehaviorEvent>> => {
          const result = await api.behaviorevent.list(query)
          return result || { data: [], meta: { total: 0, skip: 0, take: 20, hasMore: false } }
        }
      }),
      
      /**
       * Find BehaviorEvent by any field
       */
      findOne: (where: Partial<BehaviorEvent>) => ({
        queryKey: ['behaviorevent', 'query', JSON.stringify(where)],
        queryFn: async (): Promise<BehaviorEvent | null> => {
          const result = await api.behaviorevent.findOne(where)
          return result || null
        }
      }),
      
      /**
       * Count BehaviorEvent records
       */
      count: (query?: Pick<BehaviorEventQuery, 'where'>) => ({
        queryKey: stableKey('behaviorevents:count', query),
        queryFn: async (): Promise<number> => {
          const result = await api.behaviorevent.count(query as Partial<BehaviorEventQuery>)
          return result || 0
        }
      })
    }
  }
}

/**
 * BehaviorEvent mutation factory - accepts API client
 */
export function createBehaviorEventMutations(api: SDK) {
  return {
    /**
     * Create BehaviorEvent
     */
    create: () => ({
      mutationKey: ['behaviorevent', 'create'] as const,
      mutationFn: async (data: BehaviorEventCreate): Promise<BehaviorEvent> => 
        api.behaviorevent.create(data)
    }),
    
    /**
     * Update BehaviorEvent
     */
    update: () => ({
      mutationKey: ['behaviorevent', 'update'] as const,
      mutationFn: async ({ id, data }: { id: string; data: BehaviorEventUpdate }): Promise<BehaviorEvent | null> => 
        api.behaviorevent.update(id, data)
    }),
    
    /**
     * Delete BehaviorEvent
     */
    delete: () => ({
      mutationKey: ['behaviorevent', 'delete'] as const,
      mutationFn: async (id: string): Promise<boolean> => 
        api.behaviorevent.delete(id)
    })
  }
}

/**
 * BehaviorEvent infinite query factory - accepts API client
 */
export function createBehaviorEventInfinite(api: SDK) {
  return {
    /**
     * Infinite scroll BehaviorEvent list
     */
    list: (query?: Omit<BehaviorEventQuery, 'skip'>) => {
      const pageSize = query?.take || 20
      
      return {
        queryKey: stableKey('behaviorevents:infinite', query),
        queryFn: async (context: { pageParam: number }) => {
          const page = context.pageParam || 0
          return api.behaviorevent.list({
            ...query,
            skip: page * pageSize,
            take: pageSize
          })
        },
        getNextPageParam: (lastPage: ListResponse<BehaviorEvent>, allPages: ListResponse<BehaviorEvent>[]) =>
          lastPage.meta.hasMore ? allPages.length : undefined,
        initialPageParam: 0
      }
    }
  }
}
