// @generated
// This file is automatically generated. Do not edit manually.

import type { 
  BehaviorEventArchive, 
  BehaviorEventArchiveCreate, 
  BehaviorEventArchiveUpdate, 
  BehaviorEventArchiveQuery,
  ListResponse 
} from '../../types'
import type { SDK } from '../../index'
import { stableKey } from './shared/query-helpers'

/**
 * BehaviorEventArchive query factory - accepts API client for flexibility
 * 
 * These are pure query definitions that work with ANY SDK instance.
 * Inject your configured client via factory pattern.
 */
export function createBehaviorEventArchiveQueries(api: SDK) {
  return {
    /**
     * Core queries - Standard CRUD operations
     */
    all: {
      /**
       * Get single BehaviorEventArchive by ID
       */
      get: (id: string) => ({
        queryKey: stableKey('behavioreventarchive', id),
        queryFn: async (): Promise<BehaviorEventArchive | null> => {
          const result = await api.behavioreventarchive.get(id)
          return result || null
        }
      }),
      
      /**
       * List BehaviorEventArchive records
       */
      list: (query?: BehaviorEventArchiveQuery) => ({
        queryKey: stableKey('behavioreventarchives', query),
        queryFn: async (): Promise<ListResponse<BehaviorEventArchive>> => {
          const result = await api.behavioreventarchive.list(query)
          return result || { data: [], meta: { total: 0, skip: 0, take: 20, hasMore: false } }
        }
      }),
      
      /**
       * Find BehaviorEventArchive by any field
       */
      findOne: (where: Partial<BehaviorEventArchive>) => ({
        queryKey: ['behavioreventarchive', 'query', JSON.stringify(where)],
        queryFn: async (): Promise<BehaviorEventArchive | null> => {
          const result = await api.behavioreventarchive.findOne(where)
          return result || null
        }
      }),
      
      /**
       * Count BehaviorEventArchive records
       */
      count: (query?: Pick<BehaviorEventArchiveQuery, 'where'>) => ({
        queryKey: stableKey('behavioreventarchives:count', query),
        queryFn: async (): Promise<number> => {
          const result = await api.behavioreventarchive.count(query as Partial<BehaviorEventArchiveQuery>)
          return result || 0
        }
      })
    }
  }
}

/**
 * BehaviorEventArchive mutation factory - accepts API client
 */
export function createBehaviorEventArchiveMutations(api: SDK) {
  return {
    /**
     * Create BehaviorEventArchive
     */
    create: () => ({
      mutationKey: ['behavioreventarchive', 'create'] as const,
      mutationFn: async (data: BehaviorEventArchiveCreate): Promise<BehaviorEventArchive> => 
        api.behavioreventarchive.create(data)
    }),
    
    /**
     * Update BehaviorEventArchive
     */
    update: () => ({
      mutationKey: ['behavioreventarchive', 'update'] as const,
      mutationFn: async ({ id, data }: { id: string; data: BehaviorEventArchiveUpdate }): Promise<BehaviorEventArchive | null> => 
        api.behavioreventarchive.update(id, data)
    }),
    
    /**
     * Delete BehaviorEventArchive
     */
    delete: () => ({
      mutationKey: ['behavioreventarchive', 'delete'] as const,
      mutationFn: async (id: string): Promise<boolean> => 
        api.behavioreventarchive.delete(id)
    })
  }
}

/**
 * BehaviorEventArchive infinite query factory - accepts API client
 */
export function createBehaviorEventArchiveInfinite(api: SDK) {
  return {
    /**
     * Infinite scroll BehaviorEventArchive list
     */
    list: (query?: Omit<BehaviorEventArchiveQuery, 'skip'>) => {
      const pageSize = query?.take || 20
      
      return {
        queryKey: stableKey('behavioreventarchives:infinite', query),
        queryFn: async (context: { pageParam: number }) => {
          const page = context.pageParam || 0
          return api.behavioreventarchive.list({
            ...query,
            skip: page * pageSize,
            take: pageSize
          })
        },
        getNextPageParam: (lastPage: ListResponse<BehaviorEventArchive>, allPages: ListResponse<BehaviorEventArchive>[]) =>
          lastPage.meta.hasMore ? allPages.length : undefined,
        initialPageParam: 0
      }
    }
  }
}
