// @generated
// This file is automatically generated. Do not edit manually.

import type { 
  Block, 
  BlockCreate, 
  BlockUpdate, 
  BlockQuery,
  ListResponse 
} from '../../types'
import type { SDK } from '../../index'
import { stableKey } from './shared/query-helpers'

/**
 * Block query factory - accepts API client for flexibility
 * 
 * These are pure query definitions that work with ANY SDK instance.
 * Inject your configured client via factory pattern.
 */
export function createBlockQueries(api: SDK) {
  return {
    /**
     * Core queries - Standard CRUD operations
     */
    all: {
      /**
       * Get single Block by ID
       */
      get: (id: string) => ({
        queryKey: stableKey('block', id),
        queryFn: async (): Promise<Block | null> => {
          const result = await api.block.get(id)
          return result || null
        }
      }),
      
      /**
       * List Block records
       */
      list: (query?: BlockQuery) => ({
        queryKey: stableKey('blocks', query),
        queryFn: async (): Promise<ListResponse<Block>> => {
          const result = await api.block.list(query)
          return result || { data: [], meta: { total: 0, skip: 0, take: 20, hasMore: false } }
        }
      }),
      
      /**
       * Find Block by any field
       */
      findOne: (where: Partial<Block>) => ({
        queryKey: ['block', 'query', JSON.stringify(where)],
        queryFn: async (): Promise<Block | null> => {
          const result = await api.block.findOne(where)
          return result || null
        }
      }),
      
      /**
       * Count Block records
       */
      count: (query?: Pick<BlockQuery, 'where'>) => ({
        queryKey: stableKey('blocks:count', query),
        queryFn: async (): Promise<number> => {
          const result = await api.block.count(query as Partial<BlockQuery>)
          return result || 0
        }
      })
    }
  }
}

/**
 * Block mutation factory - accepts API client
 */
export function createBlockMutations(api: SDK) {
  return {
    /**
     * Create Block
     */
    create: () => ({
      mutationKey: ['block', 'create'] as const,
      mutationFn: async (data: BlockCreate): Promise<Block> => 
        api.block.create(data)
    }),
    
    /**
     * Update Block
     */
    update: () => ({
      mutationKey: ['block', 'update'] as const,
      mutationFn: async ({ id, data }: { id: string; data: BlockUpdate }): Promise<Block | null> => 
        api.block.update(id, data)
    }),
    
    /**
     * Delete Block
     */
    delete: () => ({
      mutationKey: ['block', 'delete'] as const,
      mutationFn: async (id: string): Promise<boolean> => 
        api.block.delete(id)
    })
  }
}

/**
 * Block infinite query factory - accepts API client
 */
export function createBlockInfinite(api: SDK) {
  return {
    /**
     * Infinite scroll Block list
     */
    list: (query?: Omit<BlockQuery, 'skip'>) => {
      const pageSize = query?.take || 20
      
      return {
        queryKey: stableKey('blocks:infinite', query),
        queryFn: async (context: { pageParam: number }) => {
          const page = context.pageParam || 0
          return api.block.list({
            ...query,
            skip: page * pageSize,
            take: pageSize
          })
        },
        getNextPageParam: (lastPage: ListResponse<Block>, allPages: any[]) =>
          lastPage.meta.hasMore ? allPages.length : undefined,
        initialPageParam: 0
      }
    }
  }
}
