// @generated
// This file is automatically generated. Do not edit manually.

import type { 
  DimensionMappingRule, 
  DimensionMappingRuleCreate, 
  DimensionMappingRuleUpdate, 
  DimensionMappingRuleQuery,
  ListResponse 
} from '../../types'
import type { SDK } from '../../index'
import { stableKey } from './shared/query-helpers'

/**
 * DimensionMappingRule query factory - accepts API client for flexibility
 * 
 * These are pure query definitions that work with ANY SDK instance.
 * Inject your configured client via factory pattern.
 */
export function createDimensionMappingRuleQueries(api: SDK) {
  return {
    /**
     * Core queries - Standard CRUD operations
     */
    all: {
      /**
       * Get single DimensionMappingRule by ID
       */
      get: (id: string) => ({
        queryKey: stableKey('dimensionmappingrule', id),
        queryFn: async (): Promise<DimensionMappingRule | null> => {
          const result = await api.dimensionmappingrule.get(id)
          return result || null
        }
      }),
      
      /**
       * List DimensionMappingRule records
       */
      list: (query?: DimensionMappingRuleQuery) => ({
        queryKey: stableKey('dimensionmappingrules', query),
        queryFn: async (): Promise<ListResponse<DimensionMappingRule>> => {
          const result = await api.dimensionmappingrule.list(query)
          return result || { data: [], meta: { total: 0, skip: 0, take: 20, hasMore: false } }
        }
      }),
      
      /**
       * Find DimensionMappingRule by any field
       */
      findOne: (where: Partial<DimensionMappingRule>) => ({
        queryKey: ['dimensionmappingrule', 'query', JSON.stringify(where)],
        queryFn: async (): Promise<DimensionMappingRule | null> => {
          const result = await api.dimensionmappingrule.findOne(where)
          return result || null
        }
      }),
      
      /**
       * Count DimensionMappingRule records
       */
      count: (query?: Pick<DimensionMappingRuleQuery, 'where'>) => ({
        queryKey: stableKey('dimensionmappingrules:count', query),
        queryFn: async (): Promise<number> => {
          const result = await api.dimensionmappingrule.count(query as Partial<DimensionMappingRuleQuery>)
          return result || 0
        }
      })
    }
  }
}

/**
 * DimensionMappingRule mutation factory - accepts API client
 */
export function createDimensionMappingRuleMutations(api: SDK) {
  return {
    /**
     * Create DimensionMappingRule
     */
    create: () => ({
      mutationKey: ['dimensionmappingrule', 'create'] as const,
      mutationFn: async (data: DimensionMappingRuleCreate): Promise<DimensionMappingRule> => 
        api.dimensionmappingrule.create(data)
    }),
    
    /**
     * Update DimensionMappingRule
     */
    update: () => ({
      mutationKey: ['dimensionmappingrule', 'update'] as const,
      mutationFn: async ({ id, data }: { id: string; data: DimensionMappingRuleUpdate }): Promise<DimensionMappingRule | null> => 
        api.dimensionmappingrule.update(id, data)
    }),
    
    /**
     * Delete DimensionMappingRule
     */
    delete: () => ({
      mutationKey: ['dimensionmappingrule', 'delete'] as const,
      mutationFn: async (id: string): Promise<boolean> => 
        api.dimensionmappingrule.delete(id)
    })
  }
}

/**
 * DimensionMappingRule infinite query factory - accepts API client
 */
export function createDimensionMappingRuleInfinite(api: SDK) {
  return {
    /**
     * Infinite scroll DimensionMappingRule list
     */
    list: (query?: Omit<DimensionMappingRuleQuery, 'skip'>) => {
      const pageSize = query?.take || 20
      
      return {
        queryKey: stableKey('dimensionmappingrules:infinite', query),
        queryFn: async (context: { pageParam: number }) => {
          const page = context.pageParam || 0
          return api.dimensionmappingrule.list({
            ...query,
            skip: page * pageSize,
            take: pageSize
          })
        },
        getNextPageParam: (lastPage: ListResponse<DimensionMappingRule>, allPages: any[]) =>
          lastPage.meta.hasMore ? allPages.length : undefined,
        initialPageParam: 0
      }
    }
  }
}
