// @generated
// This file is automatically generated. Do not edit manually.

import type { 
  Match, 
  MatchCreate, 
  MatchUpdate, 
  MatchQuery,
  ListResponse 
} from '../../types'
import type { SDK } from '../../index'
import { stableKey } from './shared/query-helpers'

/**
 * Match query factory - accepts API client for flexibility
 * 
 * These are pure query definitions that work with ANY SDK instance.
 * Inject your configured client via factory pattern.
 */
export function createMatchQueries(api: SDK) {
  return {
    /**
     * Core queries - Standard CRUD operations
     */
    all: {
      /**
       * Get single Match by ID
       */
      get: (id: string) => ({
        queryKey: stableKey('match', id),
        queryFn: async (): Promise<Match | null> => {
          const result = await api.match.get(id)
          return result || null
        }
      }),
      
      /**
       * List Match records
       */
      list: (query?: MatchQuery) => ({
        queryKey: stableKey('matchs', query),
        queryFn: async (): Promise<ListResponse<Match>> => {
          const result = await api.match.list(query)
          return result || { data: [], meta: { total: 0, skip: 0, take: 20, hasMore: false } }
        }
      }),
      
      /**
       * Find Match by any field
       */
      findOne: (where: Partial<Match>) => ({
        queryKey: ['match', 'query', JSON.stringify(where)],
        queryFn: async (): Promise<Match | null> => {
          const result = await api.match.findOne(where)
          return result || null
        }
      }),
      
      /**
       * Count Match records
       */
      count: (query?: Pick<MatchQuery, 'where'>) => ({
        queryKey: stableKey('matchs:count', query),
        queryFn: async (): Promise<number> => {
          const result = await api.match.count(query as Partial<MatchQuery>)
          return result || 0
        }
      })
    }
  }
}

/**
 * Match mutation factory - accepts API client
 */
export function createMatchMutations(api: SDK) {
  return {
    /**
     * Create Match
     */
    create: () => ({
      mutationKey: ['match', 'create'] as const,
      mutationFn: async (data: MatchCreate): Promise<Match> => 
        api.match.create(data)
    }),
    
    /**
     * Update Match
     */
    update: () => ({
      mutationKey: ['match', 'update'] as const,
      mutationFn: async ({ id, data }: { id: string; data: MatchUpdate }): Promise<Match | null> => 
        api.match.update(id, data)
    }),
    
    /**
     * Delete Match
     */
    delete: () => ({
      mutationKey: ['match', 'delete'] as const,
      mutationFn: async (id: string): Promise<boolean> => 
        api.match.delete(id)
    })
  }
}

/**
 * Match infinite query factory - accepts API client
 */
export function createMatchInfinite(api: SDK) {
  return {
    /**
     * Infinite scroll Match list
     */
    list: (query?: Omit<MatchQuery, 'skip'>) => {
      const pageSize = query?.take || 20
      
      return {
        queryKey: stableKey('matchs:infinite', query),
        queryFn: async (context: { pageParam: number }) => {
          const page = context.pageParam || 0
          return api.match.list({
            ...query,
            skip: page * pageSize,
            take: pageSize
          })
        },
        getNextPageParam: (lastPage: ListResponse<Match>, allPages: ListResponse<Match>[]) =>
          lastPage.meta.hasMore ? allPages.length : undefined,
        initialPageParam: 0
      }
    }
  }
}
