// @generated
// This file is automatically generated. Do not edit manually.

import type { 
  Message, 
  MessageCreate, 
  MessageUpdate, 
  MessageQuery,
  ListResponse 
} from '../../types'
import type { SDK } from '../../index'
import { stableKey } from './shared/query-helpers'

/**
 * Message query factory - accepts API client for flexibility
 * 
 * These are pure query definitions that work with ANY SDK instance.
 * Inject your configured client via factory pattern.
 */
export function createMessageQueries(api: SDK) {
  return {
    /**
     * Core queries - Standard CRUD operations
     */
    all: {
      /**
       * Get single Message by ID
       */
      get: (id: string) => ({
        queryKey: stableKey('message', id),
        queryFn: async (): Promise<Message | null> => {
          const result = await api.message.get(id)
          return result || null
        }
      }),
      
      /**
       * List Message records
       */
      list: (query?: MessageQuery) => ({
        queryKey: stableKey('messages', query),
        queryFn: async (): Promise<ListResponse<Message>> => {
          const result = await api.message.list(query)
          return result || { data: [], meta: { total: 0, skip: 0, take: 20, hasMore: false } }
        }
      }),
      
      /**
       * Find Message by any field
       */
      findOne: (where: Partial<Message>) => ({
        queryKey: ['message', 'query', JSON.stringify(where)],
        queryFn: async (): Promise<Message | null> => {
          const result = await api.message.findOne(where)
          return result || null
        }
      }),
      
      /**
       * Count Message records
       */
      count: (query?: Pick<MessageQuery, 'where'>) => ({
        queryKey: stableKey('messages:count', query),
        queryFn: async (): Promise<number> => {
          const result = await api.message.count(query as Partial<MessageQuery>)
          return result || 0
        }
      })
    }
  }
}

/**
 * Message mutation factory - accepts API client
 */
export function createMessageMutations(api: SDK) {
  return {
    /**
     * Create Message
     */
    create: () => ({
      mutationKey: ['message', 'create'] as const,
      mutationFn: async (data: MessageCreate): Promise<Message> => 
        api.message.create(data)
    }),
    
    /**
     * Update Message
     */
    update: () => ({
      mutationKey: ['message', 'update'] as const,
      mutationFn: async ({ id, data }: { id: string; data: MessageUpdate }): Promise<Message | null> => 
        api.message.update(id, data)
    }),
    
    /**
     * Delete Message
     */
    delete: () => ({
      mutationKey: ['message', 'delete'] as const,
      mutationFn: async (id: string): Promise<boolean> => 
        api.message.delete(id)
    })
  }
}

/**
 * Message infinite query factory - accepts API client
 */
export function createMessageInfinite(api: SDK) {
  return {
    /**
     * Infinite scroll Message list
     */
    list: (query?: Omit<MessageQuery, 'skip'>) => {
      const pageSize = query?.take || 20
      
      return {
        queryKey: stableKey('messages:infinite', query),
        queryFn: async (context: { pageParam: number }) => {
          const page = context.pageParam || 0
          return api.message.list({
            ...query,
            skip: page * pageSize,
            take: pageSize
          })
        },
        getNextPageParam: (lastPage: ListResponse<Message>, allPages: ListResponse<Message>[]) =>
          lastPage.meta.hasMore ? allPages.length : undefined,
        initialPageParam: 0
      }
    }
  }
}
