// @generated
// This file is automatically generated. Do not edit manually.

import type { 
  PersonalityDimension, 
  PersonalityDimensionCreate, 
  PersonalityDimensionUpdate, 
  PersonalityDimensionQuery,
  ListResponse 
} from '../../types'
import type { SDK } from '../../index'
import { stableKey } from './shared/query-helpers'

/**
 * PersonalityDimension query factory - accepts API client for flexibility
 * 
 * These are pure query definitions that work with ANY SDK instance.
 * Inject your configured client via factory pattern.
 */
export function createPersonalityDimensionQueries(api: SDK) {
  return {
    /**
     * Core queries - Standard CRUD operations
     */
    all: {
      /**
       * Get single PersonalityDimension by ID
       */
      get: (id: string) => ({
        queryKey: stableKey('personalitydimension', id),
        queryFn: async (): Promise<PersonalityDimension | null> => {
          const result = await api.personalitydimension.get(id)
          return result || null
        }
      }),
      
      /**
       * List PersonalityDimension records
       */
      list: (query?: PersonalityDimensionQuery) => ({
        queryKey: stableKey('personalitydimensions', query),
        queryFn: async (): Promise<ListResponse<PersonalityDimension>> => {
          const result = await api.personalitydimension.list(query)
          return result || { data: [], meta: { total: 0, skip: 0, take: 20, hasMore: false } }
        }
      }),
      
      /**
       * Find PersonalityDimension by any field
       */
      findOne: (where: Partial<PersonalityDimension>) => ({
        queryKey: ['personalitydimension', 'query', JSON.stringify(where)],
        queryFn: async (): Promise<PersonalityDimension | null> => {
          const result = await api.personalitydimension.findOne(where)
          return result || null
        }
      }),
      
      /**
       * Count PersonalityDimension records
       */
      count: (query?: Pick<PersonalityDimensionQuery, 'where'>) => ({
        queryKey: stableKey('personalitydimensions:count', query),
        queryFn: async (): Promise<number> => {
          const result = await api.personalitydimension.count(query as Partial<PersonalityDimensionQuery>)
          return result || 0
        }
      })
    }
  }
}

/**
 * PersonalityDimension mutation factory - accepts API client
 */
export function createPersonalityDimensionMutations(api: SDK) {
  return {
    /**
     * Create PersonalityDimension
     */
    create: () => ({
      mutationKey: ['personalitydimension', 'create'] as const,
      mutationFn: async (data: PersonalityDimensionCreate): Promise<PersonalityDimension> => 
        api.personalitydimension.create(data)
    }),
    
    /**
     * Update PersonalityDimension
     */
    update: () => ({
      mutationKey: ['personalitydimension', 'update'] as const,
      mutationFn: async ({ id, data }: { id: string; data: PersonalityDimensionUpdate }): Promise<PersonalityDimension | null> => 
        api.personalitydimension.update(id, data)
    }),
    
    /**
     * Delete PersonalityDimension
     */
    delete: () => ({
      mutationKey: ['personalitydimension', 'delete'] as const,
      mutationFn: async (id: string): Promise<boolean> => 
        api.personalitydimension.delete(id)
    })
  }
}

/**
 * PersonalityDimension infinite query factory - accepts API client
 */
export function createPersonalityDimensionInfinite(api: SDK) {
  return {
    /**
     * Infinite scroll PersonalityDimension list
     */
    list: (query?: Omit<PersonalityDimensionQuery, 'skip'>) => {
      const pageSize = query?.take || 20
      
      return {
        queryKey: stableKey('personalitydimensions:infinite', query),
        queryFn: async (context: { pageParam: number }) => {
          const page = context.pageParam || 0
          return api.personalitydimension.list({
            ...query,
            skip: page * pageSize,
            take: pageSize
          })
        },
        getNextPageParam: (lastPage: ListResponse<PersonalityDimension>, allPages: ListResponse<PersonalityDimension>[]) =>
          lastPage.meta.hasMore ? allPages.length : undefined,
        initialPageParam: 0
      }
    }
  }
}
