// @generated
// This file is automatically generated. Do not edit manually.

import type { 
  Photo, 
  PhotoCreate, 
  PhotoUpdate, 
  PhotoQuery,
  ListResponse 
} from '../../types'
import type { SDK } from '../../index'
import { stableKey } from './shared/query-helpers'

/**
 * Photo query factory - accepts API client for flexibility
 * 
 * These are pure query definitions that work with ANY SDK instance.
 * Inject your configured client via factory pattern.
 */
export function createPhotoQueries(api: SDK) {
  return {
    /**
     * Core queries - Standard CRUD operations
     */
    all: {
      /**
       * Get single Photo by ID
       */
      get: (id: string) => ({
        queryKey: stableKey('photo', id),
        queryFn: async (): Promise<Photo | null> => {
          const result = await api.photo.get(id)
          return result || null
        }
      }),
      
      /**
       * List Photo records
       */
      list: (query?: PhotoQuery) => ({
        queryKey: stableKey('photos', query),
        queryFn: async (): Promise<ListResponse<Photo>> => {
          const result = await api.photo.list(query)
          return result || { data: [], meta: { total: 0, skip: 0, take: 20, hasMore: false } }
        }
      }),
      
      /**
       * Find Photo by any field
       */
      findOne: (where: Partial<Photo>) => ({
        queryKey: ['photo', 'query', JSON.stringify(where)],
        queryFn: async (): Promise<Photo | null> => {
          const result = await api.photo.findOne(where)
          return result || null
        }
      }),
      
      /**
       * Count Photo records
       */
      count: (query?: Pick<PhotoQuery, 'where'>) => ({
        queryKey: stableKey('photos:count', query),
        queryFn: async (): Promise<number> => {
          const result = await api.photo.count(query as Partial<PhotoQuery>)
          return result || 0
        }
      })
    }
  }
}

/**
 * Photo mutation factory - accepts API client
 */
export function createPhotoMutations(api: SDK) {
  return {
    /**
     * Create Photo
     */
    create: () => ({
      mutationKey: ['photo', 'create'] as const,
      mutationFn: async (data: PhotoCreate): Promise<Photo> => 
        api.photo.create(data)
    }),
    
    /**
     * Update Photo
     */
    update: () => ({
      mutationKey: ['photo', 'update'] as const,
      mutationFn: async ({ id, data }: { id: string; data: PhotoUpdate }): Promise<Photo | null> => 
        api.photo.update(id, data)
    }),
    
    /**
     * Delete Photo
     */
    delete: () => ({
      mutationKey: ['photo', 'delete'] as const,
      mutationFn: async (id: string): Promise<boolean> => 
        api.photo.delete(id)
    })
  }
}

/**
 * Photo infinite query factory - accepts API client
 */
export function createPhotoInfinite(api: SDK) {
  return {
    /**
     * Infinite scroll Photo list
     */
    list: (query?: Omit<PhotoQuery, 'skip'>) => {
      const pageSize = query?.take || 20
      
      return {
        queryKey: stableKey('photos:infinite', query),
        queryFn: async (context: { pageParam: number }) => {
          const page = context.pageParam || 0
          return api.photo.list({
            ...query,
            skip: page * pageSize,
            take: pageSize
          })
        },
        getNextPageParam: (lastPage: ListResponse<Photo>, allPages: any[]) =>
          lastPage.meta.hasMore ? allPages.length : undefined,
        initialPageParam: 0
      }
    }
  }
}
