// @generated
// This file is automatically generated. Do not edit manually.

import type { 
  QuizAnswer, 
  QuizAnswerCreate, 
  QuizAnswerUpdate, 
  QuizAnswerQuery,
  ListResponse 
} from '../../types'
import type { SDK } from '../../index'
import { stableKey } from './shared/query-helpers'

/**
 * QuizAnswer query factory - accepts API client for flexibility
 * 
 * These are pure query definitions that work with ANY SDK instance.
 * Inject your configured client via factory pattern.
 */
export function createQuizAnswerQueries(api: SDK) {
  return {
    /**
     * Core queries - Standard CRUD operations
     */
    all: {
      /**
       * Get single QuizAnswer by ID
       */
      get: (id: string) => ({
        queryKey: stableKey('quizanswer', id),
        queryFn: async (): Promise<QuizAnswer | null> => {
          const result = await api.quizanswer.get(id)
          return result || null
        }
      }),
      
      /**
       * List QuizAnswer records
       */
      list: (query?: QuizAnswerQuery) => ({
        queryKey: stableKey('quizanswers', query),
        queryFn: async (): Promise<ListResponse<QuizAnswer>> => {
          const result = await api.quizanswer.list(query)
          return result || { data: [], meta: { total: 0, skip: 0, take: 20, hasMore: false } }
        }
      }),
      
      /**
       * Find QuizAnswer by any field
       */
      findOne: (where: Partial<QuizAnswer>) => ({
        queryKey: ['quizanswer', 'query', JSON.stringify(where)],
        queryFn: async (): Promise<QuizAnswer | null> => {
          const result = await api.quizanswer.findOne(where)
          return result || null
        }
      }),
      
      /**
       * Count QuizAnswer records
       */
      count: (query?: Pick<QuizAnswerQuery, 'where'>) => ({
        queryKey: stableKey('quizanswers:count', query),
        queryFn: async (): Promise<number> => {
          const result = await api.quizanswer.count(query as Partial<QuizAnswerQuery>)
          return result || 0
        }
      })
    }
  }
}

/**
 * QuizAnswer mutation factory - accepts API client
 */
export function createQuizAnswerMutations(api: SDK) {
  return {
    /**
     * Create QuizAnswer
     */
    create: () => ({
      mutationKey: ['quizanswer', 'create'] as const,
      mutationFn: async (data: QuizAnswerCreate): Promise<QuizAnswer> => 
        api.quizanswer.create(data)
    }),
    
    /**
     * Update QuizAnswer
     */
    update: () => ({
      mutationKey: ['quizanswer', 'update'] as const,
      mutationFn: async ({ id, data }: { id: string; data: QuizAnswerUpdate }): Promise<QuizAnswer | null> => 
        api.quizanswer.update(id, data)
    }),
    
    /**
     * Delete QuizAnswer
     */
    delete: () => ({
      mutationKey: ['quizanswer', 'delete'] as const,
      mutationFn: async (id: string): Promise<boolean> => 
        api.quizanswer.delete(id)
    })
  }
}

/**
 * QuizAnswer infinite query factory - accepts API client
 */
export function createQuizAnswerInfinite(api: SDK) {
  return {
    /**
     * Infinite scroll QuizAnswer list
     */
    list: (query?: Omit<QuizAnswerQuery, 'skip'>) => {
      const pageSize = query?.take || 20
      
      return {
        queryKey: stableKey('quizanswers:infinite', query),
        queryFn: async (context: { pageParam: number }) => {
          const page = context.pageParam || 0
          return api.quizanswer.list({
            ...query,
            skip: page * pageSize,
            take: pageSize
          })
        },
        getNextPageParam: (lastPage: ListResponse<QuizAnswer>, allPages: ListResponse<QuizAnswer>[]) =>
          lastPage.meta.hasMore ? allPages.length : undefined,
        initialPageParam: 0
      }
    }
  }
}
