// @generated
// This file is automatically generated. Do not edit manually.

import type { 
  QuizQuestion, 
  QuizQuestionCreate, 
  QuizQuestionUpdate, 
  QuizQuestionQuery,
  ListResponse 
} from '../../types'
import type { SDK } from '../../index'
import { stableKey } from './shared/query-helpers'

/**
 * QuizQuestion query factory - accepts API client for flexibility
 * 
 * These are pure query definitions that work with ANY SDK instance.
 * Inject your configured client via factory pattern.
 */
export function createQuizQuestionQueries(api: SDK) {
  return {
    /**
     * Core queries - Standard CRUD operations
     */
    all: {
      /**
       * Get single QuizQuestion by ID
       */
      get: (id: string) => ({
        queryKey: stableKey('quizquestion', id),
        queryFn: async (): Promise<QuizQuestion | null> => {
          const result = await api.quizquestion.get(id)
          return result || null
        }
      }),
      
      /**
       * List QuizQuestion records
       */
      list: (query?: QuizQuestionQuery) => ({
        queryKey: stableKey('quizquestions', query),
        queryFn: async (): Promise<ListResponse<QuizQuestion>> => {
          const result = await api.quizquestion.list(query)
          return result || { data: [], meta: { total: 0, skip: 0, take: 20, hasMore: false } }
        }
      }),
      
      /**
       * Find QuizQuestion by any field
       */
      findOne: (where: Partial<QuizQuestion>) => ({
        queryKey: ['quizquestion', 'query', JSON.stringify(where)],
        queryFn: async (): Promise<QuizQuestion | null> => {
          const result = await api.quizquestion.findOne(where)
          return result || null
        }
      }),
      
      /**
       * Count QuizQuestion records
       */
      count: (query?: Pick<QuizQuestionQuery, 'where'>) => ({
        queryKey: stableKey('quizquestions:count', query),
        queryFn: async (): Promise<number> => {
          const result = await api.quizquestion.count(query as Partial<QuizQuestionQuery>)
          return result || 0
        }
      })
    }
  }
}

/**
 * QuizQuestion mutation factory - accepts API client
 */
export function createQuizQuestionMutations(api: SDK) {
  return {
    /**
     * Create QuizQuestion
     */
    create: () => ({
      mutationKey: ['quizquestion', 'create'] as const,
      mutationFn: async (data: QuizQuestionCreate): Promise<QuizQuestion> => 
        api.quizquestion.create(data)
    }),
    
    /**
     * Update QuizQuestion
     */
    update: () => ({
      mutationKey: ['quizquestion', 'update'] as const,
      mutationFn: async ({ id, data }: { id: string; data: QuizQuestionUpdate }): Promise<QuizQuestion | null> => 
        api.quizquestion.update(id, data)
    }),
    
    /**
     * Delete QuizQuestion
     */
    delete: () => ({
      mutationKey: ['quizquestion', 'delete'] as const,
      mutationFn: async (id: string): Promise<boolean> => 
        api.quizquestion.delete(id)
    })
  }
}

/**
 * QuizQuestion infinite query factory - accepts API client
 */
export function createQuizQuestionInfinite(api: SDK) {
  return {
    /**
     * Infinite scroll QuizQuestion list
     */
    list: (query?: Omit<QuizQuestionQuery, 'skip'>) => {
      const pageSize = query?.take || 20
      
      return {
        queryKey: stableKey('quizquestions:infinite', query),
        queryFn: async (context: { pageParam: number }) => {
          const page = context.pageParam || 0
          return api.quizquestion.list({
            ...query,
            skip: page * pageSize,
            take: pageSize
          })
        },
        getNextPageParam: (lastPage: ListResponse<QuizQuestion>, allPages: any[]) =>
          lastPage.meta.hasMore ? allPages.length : undefined,
        initialPageParam: 0
      }
    }
  }
}
