// @generated
// This file is automatically generated. Do not edit manually.

import type { 
  Quiz, 
  QuizCreate, 
  QuizUpdate, 
  QuizQuery,
  ListResponse 
} from '../../types'
import type { SDK } from '../../index'
import { stableKey } from './shared/query-helpers'

/**
 * Quiz query factory - accepts API client for flexibility
 * 
 * These are pure query definitions that work with ANY SDK instance.
 * Inject your configured client via factory pattern.
 */
export function createQuizQueries(api: SDK) {
  return {
    /**
     * Core queries - Standard CRUD operations
     */
    all: {
      /**
       * Get single Quiz by ID
       */
      get: (id: string) => ({
        queryKey: stableKey('quiz', id),
        queryFn: async (): Promise<Quiz | null> => {
          const result = await api.quiz.get(id)
          return result || null
        }
      }),
      
      /**
       * List Quiz records
       */
      list: (query?: QuizQuery) => ({
        queryKey: stableKey('quizs', query),
        queryFn: async (): Promise<ListResponse<Quiz>> => {
          const result = await api.quiz.list(query)
          return result || { data: [], meta: { total: 0, skip: 0, take: 20, hasMore: false } }
        }
      }),
      
      /**
       * Find Quiz by any field
       */
      findOne: (where: Partial<Quiz>) => ({
        queryKey: ['quiz', 'query', JSON.stringify(where)],
        queryFn: async (): Promise<Quiz | null> => {
          const result = await api.quiz.findOne(where)
          return result || null
        }
      }),
      
      /**
       * Count Quiz records
       */
      count: (query?: Pick<QuizQuery, 'where'>) => ({
        queryKey: stableKey('quizs:count', query),
        queryFn: async (): Promise<number> => {
          const result = await api.quiz.count(query as Partial<QuizQuery>)
          return result || 0
        }
      })
    }
  }
}

/**
 * Quiz mutation factory - accepts API client
 */
export function createQuizMutations(api: SDK) {
  return {
    /**
     * Create Quiz
     */
    create: () => ({
      mutationKey: ['quiz', 'create'] as const,
      mutationFn: async (data: QuizCreate): Promise<Quiz> => 
        api.quiz.create(data)
    }),
    
    /**
     * Update Quiz
     */
    update: () => ({
      mutationKey: ['quiz', 'update'] as const,
      mutationFn: async ({ id, data }: { id: string; data: QuizUpdate }): Promise<Quiz | null> => 
        api.quiz.update(id, data)
    }),
    
    /**
     * Delete Quiz
     */
    delete: () => ({
      mutationKey: ['quiz', 'delete'] as const,
      mutationFn: async (id: string): Promise<boolean> => 
        api.quiz.delete(id)
    })
  }
}

/**
 * Quiz infinite query factory - accepts API client
 */
export function createQuizInfinite(api: SDK) {
  return {
    /**
     * Infinite scroll Quiz list
     */
    list: (query?: Omit<QuizQuery, 'skip'>) => {
      const pageSize = query?.take || 20
      
      return {
        queryKey: stableKey('quizs:infinite', query),
        queryFn: async (context: { pageParam: number }) => {
          const page = context.pageParam || 0
          return api.quiz.list({
            ...query,
            skip: page * pageSize,
            take: pageSize
          })
        },
        getNextPageParam: (lastPage: ListResponse<Quiz>, allPages: ListResponse<Quiz>[]) =>
          lastPage.meta.hasMore ? allPages.length : undefined,
        initialPageParam: 0
      }
    }
  }
}
