// @generated
// This file is automatically generated. Do not edit manually.

import type { 
  User, 
  UserCreate, 
  UserUpdate, 
  UserQuery,
  ListResponse 
} from '../../types'
import type { SDK } from '../../index'
import { stableKey } from './shared/query-helpers'

/**
 * User query factory - accepts API client for flexibility
 * 
 * These are pure query definitions that work with ANY SDK instance.
 * Inject your configured client via factory pattern.
 */
export function createUserQueries(api: SDK) {
  return {
    /**
     * Core queries - Standard CRUD operations
     */
    all: {
      /**
       * Get single User by ID
       */
      get: (id: string) => ({
        queryKey: stableKey('user', id),
        queryFn: async (): Promise<User | null> => {
          const result = await api.user.get(id)
          return result || null
        }
      }),
      
      /**
       * List User records
       */
      list: (query?: UserQuery) => ({
        queryKey: stableKey('users', query),
        queryFn: async (): Promise<ListResponse<User>> => {
          const result = await api.user.list(query)
          return result || { data: [], meta: { total: 0, skip: 0, take: 20, hasMore: false } }
        }
      }),
      
      /**
       * Find User by any field
       */
      findOne: (where: Partial<User>) => ({
        queryKey: ['user', 'query', JSON.stringify(where)],
        queryFn: async (): Promise<User | null> => {
          const result = await api.user.findOne(where)
          return result || null
        }
      }),
      
      /**
       * Count User records
       */
      count: (query?: Pick<UserQuery, 'where'>) => ({
        queryKey: stableKey('users:count', query),
        queryFn: async (): Promise<number> => {
          const result = await api.user.count(query as Partial<UserQuery>)
          return result || 0
        }
      })
    }
  }
}

/**
 * User mutation factory - accepts API client
 */
export function createUserMutations(api: SDK) {
  return {
    /**
     * Create User
     */
    create: () => ({
      mutationKey: ['user', 'create'] as const,
      mutationFn: async (data: UserCreate): Promise<User> => 
        api.user.create(data)
    }),
    
    /**
     * Update User
     */
    update: () => ({
      mutationKey: ['user', 'update'] as const,
      mutationFn: async ({ id, data }: { id: string; data: UserUpdate }): Promise<User | null> => 
        api.user.update(id, data)
    }),
    
    /**
     * Delete User
     */
    delete: () => ({
      mutationKey: ['user', 'delete'] as const,
      mutationFn: async (id: string): Promise<boolean> => 
        api.user.delete(id)
    })
  }
}

/**
 * User infinite query factory - accepts API client
 */
export function createUserInfinite(api: SDK) {
  return {
    /**
     * Infinite scroll User list
     */
    list: (query?: Omit<UserQuery, 'skip'>) => {
      const pageSize = query?.take || 20
      
      return {
        queryKey: stableKey('users:infinite', query),
        queryFn: async (context: { pageParam: number }) => {
          const page = context.pageParam || 0
          return api.user.list({
            ...query,
            skip: page * pageSize,
            take: pageSize
          })
        },
        getNextPageParam: (lastPage: ListResponse<User>, allPages: any[]) =>
          lastPage.meta.hasMore ? allPages.length : undefined,
        initialPageParam: 0
      }
    }
  }
}
