// @generated
// This file is automatically generated. Do not edit manually.

import type { 
  UserDimensionScore, 
  UserDimensionScoreCreate, 
  UserDimensionScoreUpdate, 
  UserDimensionScoreQuery,
  ListResponse 
} from '../../types'
import type { SDK } from '../../index'
import { stableKey } from './shared/query-helpers'

/**
 * UserDimensionScore query factory - accepts API client for flexibility
 * 
 * These are pure query definitions that work with ANY SDK instance.
 * Inject your configured client via factory pattern.
 */
export function createUserDimensionScoreQueries(api: SDK) {
  return {
    /**
     * Core queries - Standard CRUD operations
     */
    all: {
      /**
       * Get single UserDimensionScore by ID
       */
      get: (id: string) => ({
        queryKey: stableKey('userdimensionscore', id),
        queryFn: async (): Promise<UserDimensionScore | null> => {
          const result = await api.userdimensionscore.get(id)
          return result || null
        }
      }),
      
      /**
       * List UserDimensionScore records
       */
      list: (query?: UserDimensionScoreQuery) => ({
        queryKey: stableKey('userdimensionscores', query),
        queryFn: async (): Promise<ListResponse<UserDimensionScore>> => {
          const result = await api.userdimensionscore.list(query)
          return result || { data: [], meta: { total: 0, skip: 0, take: 20, hasMore: false } }
        }
      }),
      
      /**
       * Find UserDimensionScore by any field
       */
      findOne: (where: Partial<UserDimensionScore>) => ({
        queryKey: ['userdimensionscore', 'query', JSON.stringify(where)],
        queryFn: async (): Promise<UserDimensionScore | null> => {
          const result = await api.userdimensionscore.findOne(where)
          return result || null
        }
      }),
      
      /**
       * Count UserDimensionScore records
       */
      count: (query?: Pick<UserDimensionScoreQuery, 'where'>) => ({
        queryKey: stableKey('userdimensionscores:count', query),
        queryFn: async (): Promise<number> => {
          const result = await api.userdimensionscore.count(query as Partial<UserDimensionScoreQuery>)
          return result || 0
        }
      })
    }
  }
}

/**
 * UserDimensionScore mutation factory - accepts API client
 */
export function createUserDimensionScoreMutations(api: SDK) {
  return {
    /**
     * Create UserDimensionScore
     */
    create: () => ({
      mutationKey: ['userdimensionscore', 'create'] as const,
      mutationFn: async (data: UserDimensionScoreCreate): Promise<UserDimensionScore> => 
        api.userdimensionscore.create(data)
    }),
    
    /**
     * Update UserDimensionScore
     */
    update: () => ({
      mutationKey: ['userdimensionscore', 'update'] as const,
      mutationFn: async ({ id, data }: { id: string; data: UserDimensionScoreUpdate }): Promise<UserDimensionScore | null> => 
        api.userdimensionscore.update(id, data)
    }),
    
    /**
     * Delete UserDimensionScore
     */
    delete: () => ({
      mutationKey: ['userdimensionscore', 'delete'] as const,
      mutationFn: async (id: string): Promise<boolean> => 
        api.userdimensionscore.delete(id)
    })
  }
}

/**
 * UserDimensionScore infinite query factory - accepts API client
 */
export function createUserDimensionScoreInfinite(api: SDK) {
  return {
    /**
     * Infinite scroll UserDimensionScore list
     */
    list: (query?: Omit<UserDimensionScoreQuery, 'skip'>) => {
      const pageSize = query?.take || 20
      
      return {
        queryKey: stableKey('userdimensionscores:infinite', query),
        queryFn: async (context: { pageParam: number }) => {
          const page = context.pageParam || 0
          return api.userdimensionscore.list({
            ...query,
            skip: page * pageSize,
            take: pageSize
          })
        },
        getNextPageParam: (lastPage: ListResponse<UserDimensionScore>, allPages: any[]) =>
          lastPage.meta.hasMore ? allPages.length : undefined,
        initialPageParam: 0
      }
    }
  }
}
