// @generated
// This file is automatically generated. Do not edit manually.

import {
  BaseCRUDController
} from '../../base/index.js'
import { userService } from '../../services/user/index.js'
import {
  UserCreateSchema,
  UserUpdateSchema,
  UserQuerySchema
} from '../../validators/user/index.js'

/**
 * User CRUD Controller
 * Using BaseCRUDController to eliminate boilerplate
 */
const userCRUD = new BaseCRUDController(
  userService,
  {
    create: UserCreateSchema,
    update: UserUpdateSchema,
    query: UserQuerySchema
  } as any,
  {
    modelName: 'User',
    idType: 'string'
  }
)


// Standard CRUD operations
export const listUsers = userCRUD.list.bind(userCRUD)
export const searchUsers = userCRUD.search.bind(userCRUD)
export const getUser = userCRUD.getById.bind(userCRUD)
export const createUser = userCRUD.create.bind(userCRUD)
export const updateUser = userCRUD.update.bind(userCRUD)
export const deleteUser = userCRUD.deleteRecord.bind(userCRUD)
export const countUsers = userCRUD.count.bind(userCRUD)

// Bulk operations
export const bulkCreateUsers = userCRUD.bulkCreate.bind(userCRUD)
export const bulkUpdateUsers = userCRUD.bulkUpdate.bind(userCRUD)
export const bulkDeleteUsers = userCRUD.bulkDelete.bind(userCRUD)
