// @generated
// This file is automatically generated. Do not edit manually.

import type { UserCreateInput } from '@/validators/user/user.create.zod.js'

/**
 * Create DTO - Derived from Zod schema (single source of truth)
 * @see UserCreateSchema in validators
 */
export type UserCreateDTO = UserCreateInput
