// @generated
// This file is automatically generated. Do not edit manually.

import type { UserUpdateInput } from '@/validators/user/user.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see UserUpdateSchema in validators
 */
export type UserUpdateDTO = UserUpdateInput
