// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  quizanswerQueries, 
  quizanswerMutations,
  quizanswerInfinite
} from '../../core/queries/quizanswer-queries'
import type { 
  QuizAnswer, 
  QuizAnswerCreate, 
  QuizAnswerUpdate, 
  QuizAnswerQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single QuizAnswer by ID */
export function useQuizAnswer(
  id: string,
  options?: UseQueryOptions<QuizAnswer | null, Error>
) {
  return useQuery({ ...quizanswerQueries.all.get(id), ...options })
}

/** List QuizAnswer records */
export function useQuizAnswers(
  query?: QuizAnswerQuery,
  options?: UseQueryOptions<ListResponse<QuizAnswer>, Error>
) {
  return useQuery({ ...quizanswerQueries.all.list(query), ...options })
}

/** Infinite scroll QuizAnswer records */
export function useInfiniteQuizAnswers(
  query?: Omit<QuizAnswerQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<QuizAnswer>, Error>
) {
  return useInfiniteQuery({ ...quizanswerInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create QuizAnswer mutation */
export function useCreateQuizAnswer(
  options?: UseMutationOptions<QuizAnswer, Error, QuizAnswerCreate>
) {
  return useMutation({ ...quizanswerMutations.create(), ...options })
}

/** Update QuizAnswer mutation */
export function useUpdateQuizAnswer(
  options?: UseMutationOptions<QuizAnswer | null, Error, { id: string; data: QuizAnswerUpdate }>
) {
  return useMutation({ ...quizanswerMutations.update(), ...options })
}

/** Delete QuizAnswer mutation */
export function useDeleteQuizAnswer(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...quizanswerMutations.delete(), ...options })
}

