// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  behavioreventarchiveQueries, 
  behavioreventarchiveMutations,
  behavioreventarchiveInfinite
} from '../../core/queries/behavioreventarchive-queries'
import type { 
  BehaviorEventArchive, 
  BehaviorEventArchiveCreate, 
  BehaviorEventArchiveUpdate, 
  BehaviorEventArchiveQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single BehaviorEventArchive by ID */
export function useBehaviorEventArchive(
  id: string,
  options?: UseQueryOptions<BehaviorEventArchive | null, Error>
) {
  return useQuery({ ...behavioreventarchiveQueries.all.get(id), ...options })
}

/** List BehaviorEventArchive records */
export function useBehaviorEventArchives(
  query?: BehaviorEventArchiveQuery,
  options?: UseQueryOptions<ListResponse<BehaviorEventArchive>, Error>
) {
  return useQuery({ ...behavioreventarchiveQueries.all.list(query), ...options })
}

/** Infinite scroll BehaviorEventArchive records */
export function useInfiniteBehaviorEventArchives(
  query?: Omit<BehaviorEventArchiveQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<BehaviorEventArchive>, Error>
) {
  return useInfiniteQuery({ ...behavioreventarchiveInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create BehaviorEventArchive mutation */
export function useCreateBehaviorEventArchive(
  options?: UseMutationOptions<BehaviorEventArchive, Error, BehaviorEventArchiveCreate>
) {
  return useMutation({ ...behavioreventarchiveMutations.create(), ...options })
}

/** Update BehaviorEventArchive mutation */
export function useUpdateBehaviorEventArchive(
  options?: UseMutationOptions<BehaviorEventArchive | null, Error, { id: string; data: BehaviorEventArchiveUpdate }>
) {
  return useMutation({ ...behavioreventarchiveMutations.update(), ...options })
}

/** Delete BehaviorEventArchive mutation */
export function useDeleteBehaviorEventArchive(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...behavioreventarchiveMutations.delete(), ...options })
}

