// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  profileQueries, 
  profileMutations,
  profileInfinite
} from '../../core/queries/profile-queries'
import type { 
  Profile, 
  ProfileCreate, 
  ProfileUpdate, 
  ProfileQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single Profile by ID */
export function useProfile(
  id: string,
  options?: UseQueryOptions<Profile | null, Error>
) {
  return useQuery({ ...profileQueries.all.get(id), ...options })
}

/** List Profile records */
export function useProfiles(
  query?: ProfileQuery,
  options?: UseQueryOptions<ListResponse<Profile>, Error>
) {
  return useQuery({ ...profileQueries.all.list(query), ...options })
}

/** Infinite scroll Profile records */
export function useInfiniteProfiles(
  query?: Omit<ProfileQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<Profile>, Error>
) {
  return useInfiniteQuery({ ...profileInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create Profile mutation */
export function useCreateProfile(
  options?: UseMutationOptions<Profile, Error, ProfileCreate>
) {
  return useMutation({ ...profileMutations.create(), ...options })
}

/** Update Profile mutation */
export function useUpdateProfile(
  options?: UseMutationOptions<Profile | null, Error, { id: string; data: ProfileUpdate }>
) {
  return useMutation({ ...profileMutations.update(), ...options })
}

/** Delete Profile mutation */
export function useDeleteProfile(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...profileMutations.delete(), ...options })
}

