// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  blockQueries, 
  blockMutations,
  blockInfinite
} from '../../core/queries/block-queries'
import type { 
  Block, 
  BlockCreate, 
  BlockUpdate, 
  BlockQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single Block by ID */
export function useBlock(
  id: string,
  options?: UseQueryOptions<Block | null, Error>
) {
  return useQuery({ ...blockQueries.all.get(id), ...options })
}

/** List Block records */
export function useBlocks(
  query?: BlockQuery,
  options?: UseQueryOptions<ListResponse<Block>, Error>
) {
  return useQuery({ ...blockQueries.all.list(query), ...options })
}

/** Infinite scroll Block records */
export function useInfiniteBlocks(
  query?: Omit<BlockQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<Block>, Error>
) {
  return useInfiniteQuery({ ...blockInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create Block mutation */
export function useCreateBlock(
  options?: UseMutationOptions<Block, Error, BlockCreate>
) {
  return useMutation({ ...blockMutations.create(), ...options })
}

/** Update Block mutation */
export function useUpdateBlock(
  options?: UseMutationOptions<Block | null, Error, { id: string; data: BlockUpdate }>
) {
  return useMutation({ ...blockMutations.update(), ...options })
}

/** Delete Block mutation */
export function useDeleteBlock(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...blockMutations.delete(), ...options })
}

