// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  compatibilityscoreQueries, 
  compatibilityscoreMutations,
  compatibilityscoreInfinite
} from '../../core/queries/compatibilityscore-queries'
import type { 
  CompatibilityScore, 
  CompatibilityScoreCreate, 
  CompatibilityScoreUpdate, 
  CompatibilityScoreQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single CompatibilityScore by ID */
export function useCompatibilityScore(
  id: string,
  options?: UseQueryOptions<CompatibilityScore | null, Error>
) {
  return useQuery({ ...compatibilityscoreQueries.all.get(id), ...options })
}

/** List CompatibilityScore records */
export function useCompatibilityScores(
  query?: CompatibilityScoreQuery,
  options?: UseQueryOptions<ListResponse<CompatibilityScore>, Error>
) {
  return useQuery({ ...compatibilityscoreQueries.all.list(query), ...options })
}

/** Infinite scroll CompatibilityScore records */
export function useInfiniteCompatibilityScores(
  query?: Omit<CompatibilityScoreQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<CompatibilityScore>, Error>
) {
  return useInfiniteQuery({ ...compatibilityscoreInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create CompatibilityScore mutation */
export function useCreateCompatibilityScore(
  options?: UseMutationOptions<CompatibilityScore, Error, CompatibilityScoreCreate>
) {
  return useMutation({ ...compatibilityscoreMutations.create(), ...options })
}

/** Update CompatibilityScore mutation */
export function useUpdateCompatibilityScore(
  options?: UseMutationOptions<CompatibilityScore | null, Error, { id: string; data: CompatibilityScoreUpdate }>
) {
  return useMutation({ ...compatibilityscoreMutations.update(), ...options })
}

/** Delete CompatibilityScore mutation */
export function useDeleteCompatibilityScore(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...compatibilityscoreMutations.delete(), ...options })
}

