// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  messageQueries, 
  messageMutations,
  messageInfinite
} from '../../core/queries/message-queries'
import type { 
  Message, 
  MessageCreate, 
  MessageUpdate, 
  MessageQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single Message by ID */
export function useMessage(
  id: string,
  options?: UseQueryOptions<Message | null, Error>
) {
  return useQuery({ ...messageQueries.all.get(id), ...options })
}

/** List Message records */
export function useMessages(
  query?: MessageQuery,
  options?: UseQueryOptions<ListResponse<Message>, Error>
) {
  return useQuery({ ...messageQueries.all.list(query), ...options })
}

/** Infinite scroll Message records */
export function useInfiniteMessages(
  query?: Omit<MessageQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<Message>, Error>
) {
  return useInfiniteQuery({ ...messageInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create Message mutation */
export function useCreateMessage(
  options?: UseMutationOptions<Message, Error, MessageCreate>
) {
  return useMutation({ ...messageMutations.create(), ...options })
}

/** Update Message mutation */
export function useUpdateMessage(
  options?: UseMutationOptions<Message | null, Error, { id: string; data: MessageUpdate }>
) {
  return useMutation({ ...messageMutations.update(), ...options })
}

/** Delete Message mutation */
export function useDeleteMessage(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...messageMutations.delete(), ...options })
}

