// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  quizQueries, 
  quizMutations,
  quizInfinite
} from '../../core/queries/quiz-queries'
import type { 
  Quiz, 
  QuizCreate, 
  QuizUpdate, 
  QuizQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single Quiz by ID */
export function useQuiz(
  id: string,
  options?: UseQueryOptions<Quiz | null, Error>
) {
  return useQuery({ ...quizQueries.all.get(id), ...options })
}

/** List Quiz records */
export function useQuizs(
  query?: QuizQuery,
  options?: UseQueryOptions<ListResponse<Quiz>, Error>
) {
  return useQuery({ ...quizQueries.all.list(query), ...options })
}

/** Infinite scroll Quiz records */
export function useInfiniteQuizs(
  query?: Omit<QuizQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<Quiz>, Error>
) {
  return useInfiniteQuery({ ...quizInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create Quiz mutation */
export function useCreateQuiz(
  options?: UseMutationOptions<Quiz, Error, QuizCreate>
) {
  return useMutation({ ...quizMutations.create(), ...options })
}

/** Update Quiz mutation */
export function useUpdateQuiz(
  options?: UseMutationOptions<Quiz | null, Error, { id: string; data: QuizUpdate }>
) {
  return useMutation({ ...quizMutations.update(), ...options })
}

/** Delete Quiz mutation */
export function useDeleteQuiz(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...quizMutations.delete(), ...options })
}

