// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  quizquestionQueries, 
  quizquestionMutations,
  quizquestionInfinite
} from '../../core/queries/quizquestion-queries'
import type { 
  QuizQuestion, 
  QuizQuestionCreate, 
  QuizQuestionUpdate, 
  QuizQuestionQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single QuizQuestion by ID */
export function useQuizQuestion(
  id: string,
  options?: UseQueryOptions<QuizQuestion | null, Error>
) {
  return useQuery({ ...quizquestionQueries.all.get(id), ...options })
}

/** List QuizQuestion records */
export function useQuizQuestions(
  query?: QuizQuestionQuery,
  options?: UseQueryOptions<ListResponse<QuizQuestion>, Error>
) {
  return useQuery({ ...quizquestionQueries.all.list(query), ...options })
}

/** Infinite scroll QuizQuestion records */
export function useInfiniteQuizQuestions(
  query?: Omit<QuizQuestionQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<QuizQuestion>, Error>
) {
  return useInfiniteQuery({ ...quizquestionInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create QuizQuestion mutation */
export function useCreateQuizQuestion(
  options?: UseMutationOptions<QuizQuestion, Error, QuizQuestionCreate>
) {
  return useMutation({ ...quizquestionMutations.create(), ...options })
}

/** Update QuizQuestion mutation */
export function useUpdateQuizQuestion(
  options?: UseMutationOptions<QuizQuestion | null, Error, { id: string; data: QuizQuestionUpdate }>
) {
  return useMutation({ ...quizquestionMutations.update(), ...options })
}

/** Delete QuizQuestion mutation */
export function useDeleteQuizQuestion(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...quizquestionMutations.delete(), ...options })
}

