// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  userdimensionpriorityQueries, 
  userdimensionpriorityMutations,
  userdimensionpriorityInfinite
} from '../../core/queries/userdimensionpriority-queries'
import type { 
  UserDimensionPriority, 
  UserDimensionPriorityCreate, 
  UserDimensionPriorityUpdate, 
  UserDimensionPriorityQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single UserDimensionPriority by ID */
export function useUserDimensionPriority(
  id: string,
  options?: UseQueryOptions<UserDimensionPriority | null, Error>
) {
  return useQuery({ ...userdimensionpriorityQueries.all.get(id), ...options })
}

/** List UserDimensionPriority records */
export function useUserDimensionPrioritys(
  query?: UserDimensionPriorityQuery,
  options?: UseQueryOptions<ListResponse<UserDimensionPriority>, Error>
) {
  return useQuery({ ...userdimensionpriorityQueries.all.list(query), ...options })
}

/** Infinite scroll UserDimensionPriority records */
export function useInfiniteUserDimensionPrioritys(
  query?: Omit<UserDimensionPriorityQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<UserDimensionPriority>, Error>
) {
  return useInfiniteQuery({ ...userdimensionpriorityInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create UserDimensionPriority mutation */
export function useCreateUserDimensionPriority(
  options?: UseMutationOptions<UserDimensionPriority, Error, UserDimensionPriorityCreate>
) {
  return useMutation({ ...userdimensionpriorityMutations.create(), ...options })
}

/** Update UserDimensionPriority mutation */
export function useUpdateUserDimensionPriority(
  options?: UseMutationOptions<UserDimensionPriority | null, Error, { id: string; data: UserDimensionPriorityUpdate }>
) {
  return useMutation({ ...userdimensionpriorityMutations.update(), ...options })
}

/** Delete UserDimensionPriority mutation */
export function useDeleteUserDimensionPriority(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...userdimensionpriorityMutations.delete(), ...options })
}

