/**
 * Generated by SSOT UI Generator v1.0.0
 * Component: DataTable
 * 
 * Production-ready data table with sorting, filtering, search, and pagination
 * Conforms to SDK Hook Contract v1.0.0
 */

import { useMemo, useEffect } from 'react'
import type { DataTableProps } from '../types.js'
import { useTableState } from '../hooks/useTableState.js'
import { TableHeader } from './TableHeader.js'
import { TableBody } from './TableBody.js'
import { TablePagination } from './TablePagination.js'
import { TableToolbar } from './TableToolbar.js'
import { getRelationName, isRelationPath } from '../utils/cell-accessor.js'

export function DataTable<T = any>(props: DataTableProps<T>) {
  const {
    hook,
    hookParams,
    data: explicitData,
    total: explicitTotal,
    isLoading: explicitLoading,
    error: explicitError,
    onParamsChange,
    columns,
    searchable,
    searchPlaceholder,
    filterable,
    defaultSort,
    pagination = 'pages',
    defaultPageSize = 20,
    pageSizeOptions = [10, 20, 50, 100],
    rowActions,
    onRowClick,
    emptyState,
    loadingState,
    errorState,
    virtualize,
    rowHeight = 48,
    messages,
    className,
    tableClassName,
    compact = false
  } = props
  
  // Table state management
  const tableState = useTableState({ defaultPageSize, defaultSort })
  
  // Use hook if provided, otherwise use explicit data
  const hookResult = hook?.(
    hookParams 
      ? { ...hookParams, ...tableState.params }
      : tableState.params
  )
  
  const data = hookResult?.data ?? explicitData ?? []
  const total = hookResult?.total ?? explicitTotal ?? data.length
  const isLoading = hookResult?.isLoading ?? explicitLoading ?? false
  const error = hookResult?.error ?? explicitError ?? null
  
  // Notify parent of params changes
  useEffect(() => {
    if (onParamsChange) {
      onParamsChange(tableState.params)
    }
  }, [tableState.params, onParamsChange])
  
  // Check for missing relation data
  useEffect(() => {
    if (data.length > 0 && !isLoading) {
      const firstRow = data[0] as Record<string, any>
      
      columns.forEach(column => {
        if (isRelationPath(column.key)) {
          const relationName = getRelationName(column.key)
          
          if (relationName && firstRow[relationName] === undefined) {
            console.warn(
              `⚠️ @ssot-ui/data-table: Field '${column.key}' returned undefined\n\n` +
              `Problem:\n` +
              `  The field '${column.key}' is not present in the data\n\n` +
              `Why:\n` +
              `  The relation '${relationName}' was not included in the query\n\n` +
              `How to fix:\n` +
              `  Add the relation to your query hook:\n\n` +
              `  ${hook?.name || 'yourHook'}({ include: { ${relationName}: true } })\n\n` +
              `Current data structure:\n` +
              `  ${JSON.stringify(Object.keys(firstRow as object), null, 2)}\n\n` +
              `📖 Docs: https://ssot-codegen.dev/ui/data-table#relations`
            )
          }
        }
      })
    }
  }, [data, columns, isLoading, hook])
  
  // Determine if virtualization should be enabled
  const shouldVirtualize = useMemo(() => {
    if (typeof virtualize === 'boolean') return virtualize
    if (virtualize?.threshold) return total > virtualize.threshold
    return total > 1000 // Default threshold
  }, [virtualize, total])
  
  // Filter visible columns
  const visibleColumns = useMemo(() => {
    return columns.filter(col => {
      if (typeof col.visible === 'boolean') return col.visible
      if (typeof col.visible === 'function' && data.length > 0) {
        return col.visible(data[0])
      }
      return true
    })
  }, [columns, data])
  
  return (
    <div className={`ssot-data-table ${className || ''}`}>
      <TableToolbar
        searchable={searchable}
        searchPlaceholder={searchPlaceholder || messages?.search}
        filterable={filterable}
        filters={tableState.state.filters}
        search={tableState.state.search}
        onSearchChange={tableState.setSearch}
        onFilterAdd={tableState.addFilter}
        onFilterRemove={tableState.removeFilter}
        onFiltersClear={tableState.clearFilters}
        messages={messages}
      />
      
      <div className="ssot-table-container">
        <table 
          className={`ssot-table ${tableClassName || ''} ${compact ? 'compact' : ''}`}
          role="grid"
          aria-label={`Data table with ${total} items`}
        >
          <TableHeader
            columns={visibleColumns}
            sort={tableState.state.sort}
            onToggleSort={tableState.toggleSort}
            onClearSort={tableState.clearSort}
          />
          
          <TableBody
            columns={visibleColumns}
            data={data}
            isLoading={isLoading}
            error={error}
            rowActions={rowActions}
            onRowClick={onRowClick}
            emptyState={emptyState}
            loadingState={loadingState}
            errorState={errorState}
            messages={messages}
            shouldVirtualize={shouldVirtualize}
            rowHeight={rowHeight}
          />
        </table>
      </div>
      
      {pagination && !isLoading && !error && data.length > 0 && (
        <TablePagination
          page={tableState.state.page}
          pageSize={tableState.state.pageSize}
          total={total}
          pageSizeOptions={pageSizeOptions}
          onPageChange={tableState.setPage}
          onPageSizeChange={tableState.setPageSize}
          mode={pagination}
          messages={messages}
        />
      )}
    </div>
  )
}

