/**
 * Chatbot Template Generator
 * 
 * Generates a complete chatbot UI with:
 * - Message list with chat bubbles
 * - Message input with send button
 * - Typing indicators
 * - User avatars
 * - Timestamp formatting
 * 
 * Demonstrates component reuse with blog template
 */

import type { ProjectConfig } from '../prompts.js'
import type { ParsedModel } from '../ui-generator.js'
import fs from 'node:fs'
import path from 'node:path'

export interface ChatbotMapping {
  models: Record<string, string>
  fields: Record<string, string>
}

/**
 * Generate chatbot template UI
 */
export async function generateChatbotTemplate(
  projectPath: string,
  config: ProjectConfig,
  models: ParsedModel[],
  mappings?: ChatbotMapping
): Promise<void> {
  // Check if OpenAI plugin is selected
  const hasOpenAI = config.selectedPlugins?.includes('openai') || false
  // Default mappings
  const schemaMappings: ChatbotMapping = mappings || {
    models: {
      'user': 'User',
      'message': 'Message',
      'conversation': 'Conversation'
    },
    fields: {}
  }
  
  // Resolve mapped models
  const userModel = findModel(models, schemaMappings.models['user'])
  const messageModel = findModel(models, schemaMappings.models['message'])
  const conversationModel = findModel(models, schemaMappings.models['conversation']) || null
  
  if (!userModel || !messageModel) {
    throw new Error('Chatbot template requires User and Message models. Check your schema mappings.')
  }
  
  // Get field names using mappings
  const fields = {
    user: {
      id: getField(schemaMappings, 'user.id', 'id'),
      name: getField(schemaMappings, 'user.name', 'name'),
      avatar: getField(schemaMappings, 'user.avatar', 'avatar'),
      isOnline: getField(schemaMappings, 'user.isOnline', 'isOnline')
    },
    message: {
      id: getField(schemaMappings, 'message.id', 'id'),
      content: getField(schemaMappings, 'message.content', 'content'),
      sender: getField(schemaMappings, 'message.sender', 'sender'),
      senderId: getField(schemaMappings, 'message.senderId', 'senderId'),
      timestamp: getField(schemaMappings, 'message.timestamp', 'timestamp'),
      isBot: getField(schemaMappings, 'message.isBot', 'isBot')
    }
  }
  
  const appDir = path.join(projectPath, 'app')
  const chatDir = path.join(appDir, '(chat)')
  const componentsDir = path.join(projectPath, 'components')
  
  fs.mkdirSync(chatDir, { recursive: true })
  fs.mkdirSync(componentsDir, { recursive: true })
  
  // Generate chat layout
  fs.writeFileSync(
    path.join(chatDir, 'layout.tsx'),
    generateChatLayout()
  )
  
  // Generate chat page
  fs.writeFileSync(
    path.join(chatDir, 'page.tsx'),
    generateChatPage(messageModel, userModel, fields)
  )
  
  // Generate chat components
  fs.writeFileSync(
    path.join(componentsDir, 'ChatMessage.tsx'),
    generateChatMessage(messageModel, userModel, fields)
  )
  
  fs.writeFileSync(
    path.join(componentsDir, 'ChatInput.tsx'),
    generateChatInput(messageModel, fields)
  )
  
  fs.writeFileSync(
    path.join(componentsDir, 'TypingIndicator.tsx'),
    generateTypingIndicator()
  )
  
  // Generate API integration if backend exists
  const { generateChatbotAPI } = await import('./chatbot-api-generator.js')
  generateChatbotAPI(projectPath, config, {
    hasOpenAI,
    messageModel,
    userModel
  })
}

function findModel(models: ParsedModel[], name: string): ParsedModel | undefined {
  return models.find(m => m.name.toLowerCase() === name.toLowerCase())
}

function getField(mappings: ChatbotMapping, templateField: string, defaultField: string): string {
  const mapped = mappings.fields[templateField]
  if (mapped) {
    const parts = mapped.split('.')
    return parts[parts.length - 1]
  }
  return defaultField
}

function generateChatLayout(): string {
  return `/**
 * Generated by SSOT CodeGen - Chatbot Template
 * Chat layout with header
 */

export default function ChatLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <div className="h-screen flex flex-col bg-neutral-50">
      {/* Header */}
      <header className="border-b border-neutral-200 bg-white px-6 py-4">
        <div className="flex items-center justify-between">
          <h1 className="text-xl font-bold">Chat</h1>
          <div className="flex items-center gap-3">
            <span className="text-sm text-neutral-600">Support Assistant</span>
          </div>
        </div>
      </header>
      
      {/* Main chat area */}
      <main className="flex-1 overflow-hidden">
        {children}
      </main>
    </div>
  )
}
`
}

function generateChatPage(messageModel: ParsedModel, userModel: ParsedModel, fields: any): string {
  return `/**
 * Generated by SSOT CodeGen - Chatbot Template
 * Main chat interface
 * 
 * ✨ SAFE TO EDIT - Customize chat behavior
 */

'use client'

import { use${messageModel.name}List, useCreate${messageModel.name} } from '@/generated/sdk/hooks/react/use-${messageModel.nameLower}'
import { ChatMessage } from '@/components/ChatMessage'
import { ChatInput } from '@/components/ChatInput'
import { TypingIndicator } from '@/components/TypingIndicator'
import { useEffect, useRef, useState } from 'react'

export default function ChatPage() {
  const messagesEndRef = useRef<HTMLDivElement>(null)
  const [isTyping, setIsTyping] = useState(false)
  
  // Fetch messages
  const { data: messages, isLoading, refetch } = use${messageModel.name}List({
    sort: [{ field: '${fields.message.timestamp}', dir: 'asc' }],
    include: { ${fields.message.sender}: true }
  })
  
  // Create message mutation
  const { mutate: sendMessage, isPending } = useCreate${messageModel.name}()
  
  // Auto-scroll to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages])
  
  const handleSend = async (content: string) => {
    if (!content.trim()) return
    
    setIsTyping(true)
    
    try {
      // Call backend API - handles both user message and AI response
      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: content,
          userId: 1 // TODO: Get from auth context
        })
      })
      
      if (!response.ok) {
        throw new Error('Failed to send message')
      }
      
      // Backend saves both user message and bot response
      await refetch()
    } catch (error) {
      console.error('Chat error:', error)
      alert('Failed to send message. Please try again.')
    } finally {
      setIsTyping(false)
    }
  }
  
  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-neutral-500">Loading messages...</div>
      </div>
    )
  }
  
  return (
    <div className="h-full flex flex-col">
      {/* Messages area */}
      <div className="flex-1 overflow-y-auto px-6 py-4 space-y-4">
        {messages && messages.length > 0 ? (
          messages.map((message) => (
            <ChatMessage key={message.${fields.message.id}} message={message} />
          ))
        ) : (
          <div className="flex items-center justify-center h-full">
            <div className="text-center text-neutral-500">
              <p className="text-lg mb-2">No messages yet</p>
              <p className="text-sm">Start a conversation below!</p>
            </div>
          </div>
        )}
        
        {isTyping && <TypingIndicator />}
        
        <div ref={messagesEndRef} />
      </div>
      
      {/* Input area */}
      <div className="border-t border-neutral-200 bg-white px-6 py-4">
        <ChatInput onSend={handleSend} isLoading={isTyping} />
      </div>
    </div>
  )
}
`
}

function generateChatMessage(messageModel: ParsedModel, userModel: ParsedModel, fields: any): string {
  return `/**
 * Generated by SSOT CodeGen - Chatbot Template
 * Chat message bubble component
 * 
 * ✨ Uses shared components: Avatar, TimeAgo, Badge
 */

import { Avatar, TimeAgo, Badge } from '@ssot-ui/shared'
import type { ${messageModel.name} } from '@/generated/sdk/types'

interface ChatMessageProps {
  message: ${messageModel.name} & {
    ${fields.message.sender}?: {
      ${fields.user.id}: number
      ${fields.user.name}: string
      ${fields.user.avatar}?: string | null
      ${fields.user.isOnline}?: boolean
    }
  }
}

export function ChatMessage({ message }: ChatMessageProps) {
  const isBot = message.${fields.message.isBot}
  const sender = message.${fields.message.sender}
  
  return (
    <div className={\`flex gap-3 \${isBot ? 'flex-row' : 'flex-row-reverse'}\`}>
      {/* Avatar - SHARED COMPONENT */}
      <Avatar
        src={sender?.${fields.user.avatar}}
        alt={sender?.${fields.user.name} || 'Bot'}
        size="md"
        fallbackText={isBot ? '🤖' : undefined}
      />
      
      <div className={\`flex flex-col \${isBot ? 'items-start' : 'items-end'} max-w-[70%]\`}>
        {/* Sender name with online status */}
        <div className="flex items-center gap-2 mb-1">
          <span className="text-sm font-medium text-neutral-700">
            {sender?.${fields.user.name} || 'Bot'}
          </span>
          
          {/* Online badge - SHARED COMPONENT */}
          {sender?.${fields.user.isOnline} && !isBot && (
            <Badge variant="success" size="sm">● Online</Badge>
          )}
        </div>
        
        {/* Message bubble */}
        <div
          className={\`
            px-4 py-2 rounded-lg
            \${isBot 
              ? 'bg-white border border-neutral-200 text-neutral-900' 
              : 'bg-primary-600 text-white'
            }
          \`}
        >
          <p className="whitespace-pre-wrap break-words">
            {message.${fields.message.content}}
          </p>
        </div>
        
        {/* Timestamp - SHARED COMPONENT */}
        <TimeAgo 
          date={message.${fields.message.timestamp}} 
          className="text-xs text-neutral-500 mt-1"
        />
      </div>
    </div>
  )
}

/**
 * COMPONENT REUSE DEMONSTRATION
 * 
 * This chatbot component uses 3 shared components also used in blog:
 * 
 * 1. Avatar (from @ssot-ui/shared)
 *    - Blog: Author avatars in comments/posts
 *    - Chat: User/bot avatars in messages
 * 
 * 2. Badge (from @ssot-ui/shared)
 *    - Blog: Post tags, publish status
 *    - Chat: Online status, typing indicator
 * 
 * 3. TimeAgo (from @ssot-ui/shared)
 *    - Blog: Post/comment timestamps
 *    - Chat: Message timestamps
 * 
 * Benefits:
 * - Consistent design
 * - Code reuse (DRY)
 * - Smaller bundle size
 * - Easier maintenance
 */
`
}

function generateChatInput(messageModel: ParsedModel, fields: any): string {
  return `/**
 * Generated by SSOT CodeGen - Chatbot Template
 * Chat input component
 * 
 * ✨ Uses shared components: Button
 */

'use client'

import { useState } from 'react'
import { Button } from '@ssot-ui/shared'

interface ChatInputProps {
  onSend: (content: string) => void
  isLoading?: boolean
}

export function ChatInput({ onSend, isLoading }: ChatInputProps) {
  const [message, setMessage] = useState('')
  
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (message.trim()) {
      onSend(message)
      setMessage('')
    }
  }
  
  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSubmit(e)
    }
  }
  
  return (
    <form onSubmit={handleSubmit} className="flex gap-3">
      <textarea
        value={message}
        onChange={(e) => setMessage(e.target.value)}
        onKeyDown={handleKeyDown}
        placeholder="Type your message... (Enter to send, Shift+Enter for new line)"
        className="flex-1 px-4 py-2 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent resize-none"
        rows={1}
        disabled={isLoading}
        style={{
          minHeight: '42px',
          maxHeight: '120px'
        }}
      />
      
      {/* Send button - SHARED COMPONENT */}
      <Button
        type="submit"
        variant="primary"
        size="md"
        isLoading={isLoading}
        disabled={!message.trim() || isLoading}
      >
        {isLoading ? 'Sending...' : 'Send'}
      </Button>
    </form>
  )
}

/**
 * COMPONENT REUSE
 * 
 * Button component shared with:
 * - Blog: Comment submission, post creation
 * - Admin: CRUD operations, exports
 * - Chat: Send message
 */
`
}

function generateTypingIndicator(): string {
  return `/**
 * Generated by SSOT CodeGen - Chatbot Template
 * Typing indicator component
 * 
 * ✨ Uses shared components: Avatar, Badge
 */

import { Avatar, Badge } from '@ssot-ui/shared'

export function TypingIndicator() {
  return (
    <div className="flex gap-3">
      {/* Bot avatar - SHARED COMPONENT */}
      <Avatar
        alt="Bot"
        size="md"
        fallbackText="🤖"
      />
      
      <div className="flex flex-col items-start">
        {/* Typing badge - SHARED COMPONENT */}
        <Badge variant="neutral" size="sm" className="mb-1">
          Typing...
        </Badge>
        
        {/* Animated dots */}
        <div className="px-4 py-2 bg-white border border-neutral-200 rounded-lg">
          <div className="flex gap-1">
            <div className="w-2 h-2 bg-neutral-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
            <div className="w-2 h-2 bg-neutral-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
            <div className="w-2 h-2 bg-neutral-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
          </div>
        </div>
      </div>
    </div>
  )
}
`
}

