// @generated
// This file is automatically generated. Do not edit manually.

import {
  BaseCRUDController
} from '../../base/index.js'
import { behaviorEventArchiveService } from '../../services/behavior-event-archive/index.js'
import {
  BehaviorEventArchiveCreateSchema,
  BehaviorEventArchiveUpdateSchema,
  BehaviorEventArchiveQuerySchema
} from '../../validators/behavior-event-archive/index.js'

/**
 * BehaviorEventArchive CRUD Controller
 * Using BaseCRUDController to eliminate boilerplate
 */
const behaviorEventArchiveCRUD = new BaseCRUDController(
  behaviorEventArchiveService,
  {
    create: BehaviorEventArchiveCreateSchema,
    update: BehaviorEventArchiveUpdateSchema,
    query: BehaviorEventArchiveQuerySchema
  } as any,
  {
    modelName: 'BehaviorEventArchive',
    idType: 'string'
  }
)


// Standard CRUD operations
export const listBehaviorEventArchives = behaviorEventArchiveCRUD.list.bind(behaviorEventArchiveCRUD)
export const searchBehaviorEventArchives = behaviorEventArchiveCRUD.search.bind(behaviorEventArchiveCRUD)
export const getBehaviorEventArchive = behaviorEventArchiveCRUD.getById.bind(behaviorEventArchiveCRUD)
export const createBehaviorEventArchive = behaviorEventArchiveCRUD.create.bind(behaviorEventArchiveCRUD)
export const updateBehaviorEventArchive = behaviorEventArchiveCRUD.update.bind(behaviorEventArchiveCRUD)
export const deleteBehaviorEventArchive = behaviorEventArchiveCRUD.deleteRecord.bind(behaviorEventArchiveCRUD)
export const countBehaviorEventArchives = behaviorEventArchiveCRUD.count.bind(behaviorEventArchiveCRUD)

// Bulk operations
export const bulkCreateBehaviorEventArchives = behaviorEventArchiveCRUD.bulkCreate.bind(behaviorEventArchiveCRUD)
export const bulkUpdateBehaviorEventArchives = behaviorEventArchiveCRUD.bulkUpdate.bind(behaviorEventArchiveCRUD)
export const bulkDeleteBehaviorEventArchives = behaviorEventArchiveCRUD.bulkDelete.bind(behaviorEventArchiveCRUD)
