// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'

export const QuizAnswerCreateSchema = z.object({
  answerJson: z.record(z.any()),
  createdAt: z.coerce.date().optional().default(new Date())
})

export type QuizAnswerCreateInput = z.infer<typeof QuizAnswerCreateSchema>
