// @generated
// This file is automatically generated. Do not edit manually.

import prisma from '@/db'
import type { ProfileCreateDTO, ProfileUpdateDTO, ProfileQueryDTO } from '@/contracts/profile'
import type { Prisma } from '@prisma/client'
import { Gender, BodyType } from '@prisma/client'
import { logger } from '@/logger'

export const profileService = {
  /**
   * List Profile records with pagination and relationships
   */
  async list(query: ProfileQueryDTO) {
    const { skip = 0, take = 20, orderBy, where } = query
    
    logger.debug({ skip, take }, 'Listing Profile records')
    
    const whereWithSoftDelete = where
    
    const [items, total] = await Promise.all([
      prisma.profile.findMany({
        skip,
        take,
        orderBy: orderBy as Prisma.ProfileOrderByWithRelationInput,
        where: whereWithSoftDelete as Prisma.ProfileWhereInput,
      include: {
        user: {
          select: { id: true, email: true }
        }
      }
      }),
      prisma.profile.count({
        where: whereWithSoftDelete as Prisma.ProfileWhereInput,
      })
    ])
    
    return {
      data: items,
      meta: {
        total,
        skip,
        take,
        hasMore: skip + take < total
      }
    }
  },
  
  /**
   * Find Profile by ID with relationships
   */
  async findById(id: string) {
    return prisma.profile.findUnique({
      where: { id },
      include: {
        user: {
          select: { id: true, email: true }
        }
      }
    })
  },
  
  /**
   * Create Profile
   */
  async create(data: Prisma.ProfileCreateInput) {
    const item = await prisma.profile.create({
      data,
      include: {
        user: {
          select: { id: true, email: true }
        }
      }
    })
    logger.info({ profileId: item.id }, 'Profile created')
    return item
  },
  
  /**
   * Update Profile
   */
  async update(id: string, data: ProfileUpdateDTO) {
    const item = await prisma.profile.update({
      where: { id },
      data: data as Prisma.ProfileUpdateInput,
      include: {
        user: {
          select: { id: true, email: true }
        }
      }
    })
    logger.info({ profileId: id }, 'Profile updated')
    return item
  },
  
  /**
   * Delete Profile
   */
  async delete(id: string) {
    await prisma.profile.delete({
      where: { id }
    })
    logger.info({ profileId: id }, 'Profile deleted')
    return true
  },
  
  /**
   * Count Profile records
   */
  async count(where?: Prisma.ProfileWhereInput) {
    return prisma.profile.count({ where })
  },
  
  /**
   * Check if Profile exists
   */
  async exists(id: string) {
    const count = await prisma.profile.count({
      where: { id }
    })
    return count > 0
  },
  
  /**
   * Create multiple Profile records (bulk operation)
   */
  async createMany(data: Prisma.ProfileCreateManyInput[]) {
    const result = await prisma.profile.createMany({
      data,
      skipDuplicates: true
    })
    logger.info({ count: result.count }, 'Profile bulk created')
    return result
  },
  
  /**
   * Update multiple Profile records (bulk operation)
   */
  async updateMany(where: Prisma.ProfileWhereInput, data: Prisma.ProfileUpdateManyMutationInput) {
    const result = await prisma.profile.updateMany({
      where,
      data
    })
    logger.info({ count: result.count }, 'Profile bulk updated')
    return result
  },
  
  /**
   * Delete multiple Profile records (bulk operation)
   */
  async deleteMany(where: Prisma.ProfileWhereInput) {
    const result = await prisma.profile.deleteMany({ where })
    logger.info({ count: result.count }, 'Profile bulk deleted')
    return result
  },

  /**
   * Search Profiles with text query and filters
   * Auto-generated from searchable fields: name, bio, ethnicity, eyeColor, hairColor, education, occupation
   */
  async search(params: {
    q: string
    name?: string
    minAge?: number
    maxAge?: number
    gender?: Gender
    bio?: string
    ethnicity?: string
    minHeight?: number
    maxHeight?: number
    bodyType?: BodyType
    eyeColor?: string
    hairColor?: string
    education?: string
    occupation?: string
    minCreatedAt?: Date | string
    maxCreatedAt?: Date | string
    skip?: number
    take?: number
  }) {
    const where: Prisma.ProfileWhereInput = {
      AND: [
        params.q ? {
          OR: [
            { name: { contains: params.q } },
            { bio: { contains: params.q } },
            { ethnicity: { contains: params.q } },
            { eyeColor: { contains: params.q } },
            { hairColor: { contains: params.q } },
            { education: { contains: params.q } },
            { occupation: { contains: params.q } }
          ]
        } : {},
        params.name ? { name: params.name } : {},
        params.minAge ? { age: { gte: params.minAge } } : {},
        params.maxAge ? { age: { lte: params.maxAge } } : {},
        params.gender ? { gender: params.gender } : {},
        params.bio ? { bio: params.bio } : {},
        params.ethnicity ? { ethnicity: params.ethnicity } : {},
        params.minHeight ? { height: { gte: params.minHeight } } : {},
        params.maxHeight ? { height: { lte: params.maxHeight } } : {},
        params.bodyType ? { bodyType: params.bodyType } : {},
        params.eyeColor ? { eyeColor: params.eyeColor } : {},
        params.hairColor ? { hairColor: params.hairColor } : {},
        params.education ? { education: params.education } : {},
        params.occupation ? { occupation: params.occupation } : {},
        params.minCreatedAt ? { createdAt: { gte: params.minCreatedAt } } : {},
        params.maxCreatedAt ? { createdAt: { lte: params.maxCreatedAt } } : {}
      ].filter(condition => Object.keys(condition).length > 0)
    }
    
    return prisma.profile.findMany({
      where,
      skip: params.skip || 0,
      take: Math.min(params.take || 20, 100)
    })
  },

  /**
   * Get Profiles by ProfileToUser
   * Auto-generated from foreign key detection: userId
   */
  async getByProfileToUser(userId: string, options?: {
    skip?: number
    take?: number
  }) {
    return prisma.profile.findMany({
      where: { userId },
      skip: options?.skip || 0,
      take: options?.take || 20
    })
  }
}
