// @generated
// This file is automatically generated. Do not edit manually.

import type { QuizAnswerReadDTO } from './quiz-answer.read.dto.js'

type QuizAnswerWhereInput = {
    id?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    answerJson?: Record<string, any>
    createdAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    AND?: QuizAnswerWhereInput[]
    OR?: QuizAnswerWhereInput[]
    NOT?: QuizAnswerWhereInput[]
  }

export interface QuizAnswerQueryDTO {
  skip?: number  // Offset pagination (should be >= 0)
  take?: number  // Limit (should be > 0)
  cursor?: string  // Cursor for cursor-based pagination
  orderBy?: {
    id?: 'asc' | 'desc'
    quizId?: 'asc' | 'desc'
    questionId?: 'asc' | 'desc'
    userId?: 'asc' | 'desc'
    answerJson?: 'asc' | 'desc'
    createdAt?: 'asc' | 'desc'
    quiz?: { [key: string]: 'asc' | 'desc' }
    question?: { [key: string]: 'asc' | 'desc' }
    user?: { [key: string]: 'asc' | 'desc' }
  }
  where?: QuizAnswerWhereInput
  include?: {
    quiz?: boolean | { include?: any; select?: any }
    question?: boolean | { include?: any; select?: any }
    user?: boolean | { include?: any; select?: any }
  }
  select?: {
    id?: boolean
    quizId?: boolean
    questionId?: boolean
    userId?: boolean
    answerJson?: boolean
    createdAt?: boolean
    quiz?: boolean | { select?: any; include?: any }
    question?: boolean | { select?: any; include?: any }
    user?: boolean | { select?: any; include?: any }
  }
  distinct?: 'id' | 'answerJson' | 'createdAt' | Array<'id' | 'answerJson' | 'createdAt'>
}

export interface QuizAnswerListResponse {
  data: QuizAnswerReadDTO[]
  meta: {
    total: number
    skip: number
    take: number
    hasMore: boolean  // Calculated as: skip + take < total
  }
}
