// @generated
// This file is automatically generated. Do not edit manually.

import type { QuizAnswerCreateInput } from '@/validators/quiz-answer/quiz-answer.create.zod.js'

/**
 * Create DTO - Derived from Zod schema (single source of truth)
 * @see QuizAnswerCreateSchema in validators
 */
export type QuizAnswerCreateDTO = QuizAnswerCreateInput
