// @generated
// This file is automatically generated. Do not edit manually.

import {
  BaseCRUDController
} from '../../base/index.js'
import { behaviorEventService } from '../../services/behavior-event/index.js'
import {
  BehaviorEventCreateSchema,
  BehaviorEventUpdateSchema,
  BehaviorEventQuerySchema
} from '../../validators/behavior-event/index.js'

/**
 * BehaviorEvent CRUD Controller
 * Using BaseCRUDController to eliminate boilerplate
 */
const behaviorEventCRUD = new BaseCRUDController(
  behaviorEventService,
  {
    create: BehaviorEventCreateSchema,
    update: BehaviorEventUpdateSchema,
    query: BehaviorEventQuerySchema
  } as any,
  {
    modelName: 'BehaviorEvent',
    idType: 'string'
  }
)


// Standard CRUD operations
export const listBehaviorEvents = behaviorEventCRUD.list.bind(behaviorEventCRUD)
export const searchBehaviorEvents = behaviorEventCRUD.search.bind(behaviorEventCRUD)
export const getBehaviorEvent = behaviorEventCRUD.getById.bind(behaviorEventCRUD)
export const createBehaviorEvent = behaviorEventCRUD.create.bind(behaviorEventCRUD)
export const updateBehaviorEvent = behaviorEventCRUD.update.bind(behaviorEventCRUD)
export const deleteBehaviorEvent = behaviorEventCRUD.deleteRecord.bind(behaviorEventCRUD)
export const countBehaviorEvents = behaviorEventCRUD.count.bind(behaviorEventCRUD)

// Bulk operations
export const bulkCreateBehaviorEvents = behaviorEventCRUD.bulkCreate.bind(behaviorEventCRUD)
export const bulkUpdateBehaviorEvents = behaviorEventCRUD.bulkUpdate.bind(behaviorEventCRUD)
export const bulkDeleteBehaviorEvents = behaviorEventCRUD.bulkDelete.bind(behaviorEventCRUD)
