// @generated
// This file is automatically generated. Do not edit manually.

import prisma from '@/db'
import type { QuizQuestionCreateDTO, QuizQuestionUpdateDTO, QuizQuestionQueryDTO } from '@/contracts/quiz-question'
import type { Prisma } from '@prisma/client'
import { logger } from '@/logger'

export const quizQuestionService = {
  /**
   * List QuizQuestion records with pagination and relationships
   */
  async list(query: QuizQuestionQueryDTO) {
    const { skip = 0, take = 20, orderBy, where } = query
    
    logger.debug({ skip, take }, 'Listing QuizQuestion records')
    
    const whereWithSoftDelete = where
    
    const [items, total] = await Promise.all([
      prisma.quizQuestion.findMany({
        skip,
        take,
        orderBy: orderBy as Prisma.QuizQuestionOrderByWithRelationInput,
        where: whereWithSoftDelete as Prisma.QuizQuestionWhereInput,
      include: {
        quiz: {
          select: { id: true, title: true }
        }
      }
      }),
      prisma.quizQuestion.count({
        where: whereWithSoftDelete as Prisma.QuizQuestionWhereInput,
      })
    ])
    
    return {
      data: items,
      meta: {
        total,
        skip,
        take,
        hasMore: skip + take < total
      }
    }
  },
  
  /**
   * Find QuizQuestion by ID with relationships
   */
  async findById(id: string) {
    return prisma.quizQuestion.findUnique({
      where: { id },
      include: {
        quiz: {
          select: { id: true, title: true }
        }
      }
    })
  },
  
  /**
   * Create QuizQuestion
   */
  async create(data: Prisma.QuizQuestionCreateInput) {
    const item = await prisma.quizQuestion.create({
      data,
      include: {
        quiz: {
          select: { id: true, title: true }
        }
      }
    })
    logger.info({ quizQuestionId: item.id }, 'QuizQuestion created')
    return item
  },
  
  /**
   * Update QuizQuestion
   */
  async update(id: string, data: QuizQuestionUpdateDTO) {
    const item = await prisma.quizQuestion.update({
      where: { id },
      data: data as Prisma.QuizQuestionUpdateInput,
      include: {
        quiz: {
          select: { id: true, title: true }
        }
      }
    })
    logger.info({ quizQuestionId: id }, 'QuizQuestion updated')
    return item
  },
  
  /**
   * Delete QuizQuestion
   */
  async delete(id: string) {
    await prisma.quizQuestion.delete({
      where: { id }
    })
    logger.info({ quizQuestionId: id }, 'QuizQuestion deleted')
    return true
  },
  
  /**
   * Count QuizQuestion records
   */
  async count(where?: Prisma.QuizQuestionWhereInput) {
    return prisma.quizQuestion.count({ where })
  },
  
  /**
   * Check if QuizQuestion exists
   */
  async exists(id: string) {
    const count = await prisma.quizQuestion.count({
      where: { id }
    })
    return count > 0
  },
  
  /**
   * Create multiple QuizQuestion records (bulk operation)
   */
  async createMany(data: Prisma.QuizQuestionCreateManyInput[]) {
    const result = await prisma.quizQuestion.createMany({
      data,
      skipDuplicates: true
    })
    logger.info({ count: result.count }, 'QuizQuestion bulk created')
    return result
  },
  
  /**
   * Update multiple QuizQuestion records (bulk operation)
   */
  async updateMany(where: Prisma.QuizQuestionWhereInput, data: Prisma.QuizQuestionUpdateManyMutationInput) {
    const result = await prisma.quizQuestion.updateMany({
      where,
      data
    })
    logger.info({ count: result.count }, 'QuizQuestion bulk updated')
    return result
  },
  
  /**
   * Delete multiple QuizQuestion records (bulk operation)
   */
  async deleteMany(where: Prisma.QuizQuestionWhereInput) {
    const result = await prisma.quizQuestion.deleteMany({ where })
    logger.info({ count: result.count }, 'QuizQuestion bulk deleted')
    return result
  },

  /**
   * Get QuizQuestions by QuizToQuizQuestion
   * Auto-generated from foreign key detection: quizId
   */
  async getByQuizToQuizQuestion(quizId: string, options?: {
    skip?: number
    take?: number
  }) {
    return prisma.quizQuestion.findMany({
      where: { quizId },
      skip: options?.skip || 0,
      take: options?.take || 20
    })
  }
}
