// @generated
// This file is automatically generated. Do not edit manually.

import type { QuizQuestionUpdateInput } from '@/validators/quiz-question/quiz-question.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see QuizQuestionUpdateSchema in validators
 */
export type QuizQuestionUpdateDTO = QuizQuestionUpdateInput
