// @generated
// This file is automatically generated. Do not edit manually.

import { QuizQuestionType } from '@prisma/client'

import type { QuizQuestionReadDTO } from './quiz-question.read.dto.js'

type QuizQuestionWhereInput = {
    id?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    type?: QuizQuestionType | {
      equals?: QuizQuestionType
      in?: QuizQuestionType[]
      notIn?: QuizQuestionType[]
      not?: QuizQuestionType
    }
    order?: number | {
      equals?: number
      gt?: number
      gte?: number
      lt?: number
      lte?: number
      in?: number[]
      notIn?: number[]
      not?: number
    }
    configJson?: Record<string, any>
    createdAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    AND?: QuizQuestionWhereInput[]
    OR?: QuizQuestionWhereInput[]
    NOT?: QuizQuestionWhereInput[]
  }

export interface QuizQuestionQueryDTO {
  skip?: number  // Offset pagination (should be >= 0)
  take?: number  // Limit (should be > 0)
  cursor?: string  // Cursor for cursor-based pagination
  orderBy?: {
    id?: 'asc' | 'desc'
    quizId?: 'asc' | 'desc'
    type?: 'asc' | 'desc'
    order?: 'asc' | 'desc'
    configJson?: 'asc' | 'desc'
    createdAt?: 'asc' | 'desc'
    quiz?: { [key: string]: 'asc' | 'desc' }
    answers?: { [key: string]: 'asc' | 'desc' }
  }
  where?: QuizQuestionWhereInput
  include?: {
    quiz?: boolean | { include?: any; select?: any }
    answers?: boolean | { include?: any; select?: any }
  }
  select?: {
    id?: boolean
    quizId?: boolean
    type?: boolean
    order?: boolean
    configJson?: boolean
    createdAt?: boolean
    quiz?: boolean | { select?: any; include?: any }
    answers?: boolean | { select?: any; include?: any }
  }
  distinct?: 'id' | 'type' | 'order' | 'configJson' | 'createdAt' | Array<'id' | 'type' | 'order' | 'configJson' | 'createdAt'>
}

export interface QuizQuestionListResponse {
  data: QuizQuestionReadDTO[]
  meta: {
    total: number
    skip: number
    take: number
    hasMore: boolean  // Calculated as: skip + take < total
  }
}
