// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { PersonalityDimensionCreateSchema } from './personality-dimension.create.zod.js'

export const PersonalityDimensionUpdateSchema = PersonalityDimensionCreateSchema.partial()

export type PersonalityDimensionUpdateInput = z.infer<typeof PersonalityDimensionUpdateSchema>
