// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { DimensionCategory } from '@prisma/client'

export const PersonalityDimensionQuerySchema = z.object({
  skip: z.coerce.number().min(0).optional(),
  take: z.coerce.number().min(1).max(100).optional().default(20),
  orderBy: z.object({
    id: z.enum(['asc', 'desc']).optional(),
    name: z.enum(['asc', 'desc']).optional(),
    description: z.enum(['asc', 'desc']).optional(),
    category: z.enum(['asc', 'desc']).optional(),
    isActive: z.enum(['asc', 'desc']).optional(),
    normalizationConfig: z.enum(['asc', 'desc']).optional(),
    createdAt: z.enum(['asc', 'desc']).optional(),
    updatedAt: z.enum(['asc', 'desc']).optional(),
    userDimensionScores: z.record(z.enum(['asc', 'desc'])).optional(),
    dimensionMappingRules: z.record(z.enum(['asc', 'desc'])).optional(),
    userDimensionPriorities: z.record(z.enum(['asc', 'desc'])).optional()
  }).optional(),
  where: z.object({
    id: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    name: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    description: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional(),
      isNull: z.boolean().optional()
    }).optional(),
    category: z.nativeEnum(DimensionCategory).optional(),
    isActive: z.boolean().optional(),
    createdAt: z.object({
      equals: z.coerce.date().optional(),
      gt: z.coerce.date().optional(),
      gte: z.coerce.date().optional(),
      lt: z.coerce.date().optional(),
      lte: z.coerce.date().optional()
    }).optional()
  }).optional(),
  include: z.object({
    userDimensionScores: z.boolean().optional(),
    dimensionMappingRules: z.boolean().optional(),
    userDimensionPriorities: z.boolean().optional()
  }).optional(),
  select: z.object({
    id: z.boolean().optional(),
    name: z.boolean().optional(),
    description: z.boolean().optional(),
    category: z.boolean().optional(),
    isActive: z.boolean().optional(),
    normalizationConfig: z.boolean().optional(),
    createdAt: z.boolean().optional(),
    updatedAt: z.boolean().optional(),
    userDimensionScores: z.boolean().optional(),
    dimensionMappingRules: z.boolean().optional(),
    userDimensionPriorities: z.boolean().optional()
  }).optional()
})

export type PersonalityDimensionQueryInput = z.infer<typeof PersonalityDimensionQuerySchema>
