// @generated
// This file is automatically generated. Do not edit manually.

import type { QuizAnswerUpdateInput } from '@/validators/quiz-answer/quiz-answer.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see QuizAnswerUpdateSchema in validators
 */
export type QuizAnswerUpdateDTO = QuizAnswerUpdateInput
