// @generated
// This file is automatically generated. Do not edit manually.

export interface QuizAnswerReadDTO {
  id: string
  quizId: string
  questionId: string
  userId: string
  answerJson: Record<string, any>
  createdAt: Date
}
