// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { BehaviorEventCreateSchema } from './behavior-event.create.zod.js'

export const BehaviorEventUpdateSchema = BehaviorEventCreateSchema.partial()

export type BehaviorEventUpdateInput = z.infer<typeof BehaviorEventUpdateSchema>
