// @generated
// This file is automatically generated. Do not edit manually.

import type { CompatibilityScoreUpdateInput } from '@/validators/compatibility-score/compatibility-score.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see CompatibilityScoreUpdateSchema in validators
 */
export type CompatibilityScoreUpdateDTO = CompatibilityScoreUpdateInput
