// @generated
// This file is automatically generated. Do not edit manually.

export interface CompatibilityScoreReadDTO {
  id: string
  user1Id: string
  user2Id: string
  overallScore: number
  dimensionBreakdown: Record<string, any>
  calculatedAt: Date
  cacheVersion: string | null
}
