// @generated
// This file is automatically generated. Do not edit manually.

import { Router, type Router as RouterType } from 'express'
import * as compatibilityScoreController from '@/controllers/compatibility-score/index.js'

export const compatibilityScoreRouter: RouterType = Router()

// List all CompatibilityScore records (simple pagination)
compatibilityScoreRouter.get('/', compatibilityScoreController.listCompatibilityScores)

// Search CompatibilityScore records (complex filtering via POST body)
compatibilityScoreRouter.post('/search', compatibilityScoreController.searchCompatibilityScores)

// Get CompatibilityScore by ID
compatibilityScoreRouter.get('/:id', compatibilityScoreController.getCompatibilityScore)

// Create CompatibilityScore
compatibilityScoreRouter.post('/', compatibilityScoreController.createCompatibilityScore)

// Update CompatibilityScore
compatibilityScoreRouter.put('/:id', compatibilityScoreController.updateCompatibilityScore)
compatibilityScoreRouter.patch('/:id', compatibilityScoreController.updateCompatibilityScore)

// Delete CompatibilityScore
compatibilityScoreRouter.delete('/:id', compatibilityScoreController.deleteCompatibilityScore)

// Count CompatibilityScore records
compatibilityScoreRouter.get('/meta/count', compatibilityScoreController.countCompatibilityScores)

// Bulk operations
compatibilityScoreRouter.post('/bulk/create', compatibilityScoreController.bulkCreateCompatibilityScores)
compatibilityScoreRouter.put('/bulk/update', compatibilityScoreController.bulkUpdateCompatibilityScores)
compatibilityScoreRouter.delete('/bulk/delete', compatibilityScoreController.bulkDeleteCompatibilityScores)

