// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'

export const PhotoCreateSchema = z.object({
  url: z.string().min(1, 'url is required'),
  order: z.number().int().optional(),
  moderationStatus: z.string().min(1, 'moderationStatus is required').optional().default("pending"),
  createdAt: z.coerce.date().optional().default(new Date())
})

export type PhotoCreateInput = z.infer<typeof PhotoCreateSchema>
