// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { PhotoCreateSchema } from './photo.create.zod.js'

export const PhotoUpdateSchema = PhotoCreateSchema.partial()

export type PhotoUpdateInput = z.infer<typeof PhotoUpdateSchema>
