// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { BlockCreateSchema } from './block.create.zod.js'

export const BlockUpdateSchema = BlockCreateSchema.partial()

export type BlockUpdateInput = z.infer<typeof BlockUpdateSchema>
