// @generated
// This file is automatically generated. Do not edit manually.

import type { MatchReadDTO } from './match.read.dto.js'

type MatchWhereInput = {
    id?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    createdAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    unmatchedAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
      isNull?: boolean
    }
    AND?: MatchWhereInput[]
    OR?: MatchWhereInput[]
    NOT?: MatchWhereInput[]
  }

export interface MatchQueryDTO {
  skip?: number  // Offset pagination (should be >= 0)
  take?: number  // Limit (should be > 0)
  cursor?: string  // Cursor for cursor-based pagination
  orderBy?: {
    id?: 'asc' | 'desc'
    user1Id?: 'asc' | 'desc'
    user2Id?: 'asc' | 'desc'
    createdAt?: 'asc' | 'desc'
    unmatchedAt?: 'asc' | 'desc'
    user1?: { [key: string]: 'asc' | 'desc' }
    user2?: { [key: string]: 'asc' | 'desc' }
    messages?: { [key: string]: 'asc' | 'desc' }
  }
  where?: MatchWhereInput
  include?: {
    user1?: boolean | { include?: any; select?: any }
    user2?: boolean | { include?: any; select?: any }
    messages?: boolean | { include?: any; select?: any }
  }
  select?: {
    id?: boolean
    user1Id?: boolean
    user2Id?: boolean
    createdAt?: boolean
    unmatchedAt?: boolean
    user1?: boolean | { select?: any; include?: any }
    user2?: boolean | { select?: any; include?: any }
    messages?: boolean | { select?: any; include?: any }
  }
  distinct?: 'id' | 'createdAt' | 'unmatchedAt' | Array<'id' | 'createdAt' | 'unmatchedAt'>
}

export interface MatchListResponse {
  data: MatchReadDTO[]
  meta: {
    total: number
    skip: number
    take: number
    hasMore: boolean  // Calculated as: skip + take < total
  }
}
