// @generated
// This file is automatically generated. Do not edit manually.

import type { MatchUpdateInput } from '@/validators/match/match.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see MatchUpdateSchema in validators
 */
export type MatchUpdateDTO = MatchUpdateInput
