// @generated
// This file is automatically generated. Do not edit manually.

import type { ProfileCreateInput } from '@/validators/profile/profile.create.zod.js'

/**
 * Create DTO - Derived from Zod schema (single source of truth)
 * @see ProfileCreateSchema in validators
 */
export type ProfileCreateDTO = ProfileCreateInput
