// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { SwipeType } from '@prisma/client'

export const SwipeCreateSchema = z.object({
  type: z.nativeEnum(SwipeType),
  createdAt: z.coerce.date().optional().default(new Date())
})

export type SwipeCreateInput = z.infer<typeof SwipeCreateSchema>
