// @generated
// This file is automatically generated. Do not edit manually.

import { Router, type Router as RouterType } from 'express'
import * as personalityDimensionController from '@/controllers/personality-dimension/index.js'

export const personalityDimensionRouter: RouterType = Router()

// List all PersonalityDimension records (simple pagination)
personalityDimensionRouter.get('/', personalityDimensionController.listPersonalityDimensions)

// Search PersonalityDimension records (complex filtering via POST body)
personalityDimensionRouter.post('/search', personalityDimensionController.searchPersonalityDimensions)

// Get PersonalityDimension by ID
personalityDimensionRouter.get('/:id', personalityDimensionController.getPersonalityDimension)

// Create PersonalityDimension
personalityDimensionRouter.post('/', personalityDimensionController.createPersonalityDimension)

// Update PersonalityDimension
personalityDimensionRouter.put('/:id', personalityDimensionController.updatePersonalityDimension)
personalityDimensionRouter.patch('/:id', personalityDimensionController.updatePersonalityDimension)

// Delete PersonalityDimension
personalityDimensionRouter.delete('/:id', personalityDimensionController.deletePersonalityDimension)

// Count PersonalityDimension records
personalityDimensionRouter.get('/meta/count', personalityDimensionController.countPersonalityDimensions)

// Bulk operations
personalityDimensionRouter.post('/bulk/create', personalityDimensionController.bulkCreatePersonalityDimensions)
personalityDimensionRouter.put('/bulk/update', personalityDimensionController.bulkUpdatePersonalityDimensions)
personalityDimensionRouter.delete('/bulk/delete', personalityDimensionController.bulkDeletePersonalityDimensions)

