// @generated
// This file is automatically generated. Do not edit manually.

import prisma from '@/db'
import type { MessageCreateDTO, MessageUpdateDTO, MessageQueryDTO } from '@/contracts/message'
import type { Prisma } from '@prisma/client'
import { logger } from '@/logger'

export const messageService = {
  /**
   * List Message records with pagination and relationships
   */
  async list(query: MessageQueryDTO) {
    const { skip = 0, take = 20, orderBy, where } = query
    
    logger.debug({ skip, take }, 'Listing Message records')
    
    const whereWithSoftDelete = where
    
    const [items, total] = await Promise.all([
      prisma.message.findMany({
        skip,
        take,
        orderBy: orderBy as Prisma.MessageOrderByWithRelationInput,
        where: whereWithSoftDelete as Prisma.MessageWhereInput,
      include: {
        sender: {
          select: { id: true, email: true }
        },
        receiver: {
          select: { id: true, email: true }
        }
      }
      }),
      prisma.message.count({
        where: whereWithSoftDelete as Prisma.MessageWhereInput,
      })
    ])
    
    return {
      data: items,
      meta: {
        total,
        skip,
        take,
        hasMore: skip + take < total
      }
    }
  },
  
  /**
   * Find Message by ID with relationships
   */
  async findById(id: string) {
    return prisma.message.findUnique({
      where: { id },
      include: {
        sender: {
          select: { id: true, email: true }
        },
        receiver: {
          select: { id: true, email: true }
        }
      }
    })
  },
  
  /**
   * Create Message
   */
  async create(data: Prisma.MessageCreateInput) {
    const item = await prisma.message.create({
      data,
      include: {
        sender: {
          select: { id: true, email: true }
        },
        receiver: {
          select: { id: true, email: true }
        }
      }
    })
    logger.info({ messageId: item.id }, 'Message created')
    return item
  },
  
  /**
   * Update Message
   */
  async update(id: string, data: MessageUpdateDTO) {
    const item = await prisma.message.update({
      where: { id },
      data: data as Prisma.MessageUpdateInput,
      include: {
        sender: {
          select: { id: true, email: true }
        },
        receiver: {
          select: { id: true, email: true }
        }
      }
    })
    logger.info({ messageId: id }, 'Message updated')
    return item
  },
  
  /**
   * Delete Message
   */
  async delete(id: string) {
    await prisma.message.delete({
      where: { id }
    })
    logger.info({ messageId: id }, 'Message deleted')
    return true
  },
  
  /**
   * Count Message records
   */
  async count(where?: Prisma.MessageWhereInput) {
    return prisma.message.count({ where })
  },
  
  /**
   * Check if Message exists
   */
  async exists(id: string) {
    const count = await prisma.message.count({
      where: { id }
    })
    return count > 0
  },
  
  /**
   * Create multiple Message records (bulk operation)
   */
  async createMany(data: Prisma.MessageCreateManyInput[]) {
    const result = await prisma.message.createMany({
      data,
      skipDuplicates: true
    })
    logger.info({ count: result.count }, 'Message bulk created')
    return result
  },
  
  /**
   * Update multiple Message records (bulk operation)
   */
  async updateMany(where: Prisma.MessageWhereInput, data: Prisma.MessageUpdateManyMutationInput) {
    const result = await prisma.message.updateMany({
      where,
      data
    })
    logger.info({ count: result.count }, 'Message bulk updated')
    return result
  },
  
  /**
   * Delete multiple Message records (bulk operation)
   */
  async deleteMany(where: Prisma.MessageWhereInput) {
    const result = await prisma.message.deleteMany({ where })
    logger.info({ count: result.count }, 'Message bulk deleted')
    return result
  },

  /**
   * Search Messages with text query and filters
   * Auto-generated from searchable fields: content, messageType
   */
  async search(params: {
    q: string
    content?: string
    messageType?: string
    minReadAt?: Date | string
    maxReadAt?: Date | string
    minCreatedAt?: Date | string
    maxCreatedAt?: Date | string
    skip?: number
    take?: number
  }) {
    const where: Prisma.MessageWhereInput = {
      AND: [
        params.q ? {
          OR: [
            { content: { contains: params.q } },
            { messageType: { contains: params.q } }
          ]
        } : {},
        params.content ? { content: params.content } : {},
        params.messageType ? { messageType: params.messageType } : {},
        params.minReadAt ? { readAt: { gte: params.minReadAt } } : {},
        params.maxReadAt ? { readAt: { lte: params.maxReadAt } } : {},
        params.minCreatedAt ? { createdAt: { gte: params.minCreatedAt } } : {},
        params.maxCreatedAt ? { createdAt: { lte: params.maxCreatedAt } } : {}
      ].filter(condition => Object.keys(condition).length > 0)
    }
    
    return prisma.message.findMany({
      where,
      skip: params.skip || 0,
      take: Math.min(params.take || 20, 100)
    })
  },

  /**
   * Get Messages by MatchToMessage
   * Auto-generated from foreign key detection: matchId
   */
  async getByMatchToMessage(matchId: string, options?: {
    skip?: number
    take?: number
  }) {
    return prisma.message.findMany({
      where: { matchId },
      skip: options?.skip || 0,
      take: options?.take || 20
    })
  },

  /**
   * Get Messages by Sender
   * Auto-generated from foreign key detection: senderId
   */
  async getBySender(senderId: string, options?: {
    skip?: number
    take?: number
  }) {
    return prisma.message.findMany({
      where: { senderId },
      skip: options?.skip || 0,
      take: options?.take || 20
    })
  },

  /**
   * Get Messages by Receiver
   * Auto-generated from foreign key detection: receiverId
   */
  async getByReceiver(receiverId: string, options?: {
    skip?: number
    take?: number
  }) {
    return prisma.message.findMany({
      where: { receiverId },
      skip: options?.skip || 0,
      take: options?.take || 20
    })
  }
}
