// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'

export const MessageCreateSchema = z.object({
  content: z.string().min(1, 'content is required'),
  messageType: z.string().min(1, 'messageType is required').optional().default("text"),
  readAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional().default(new Date())
})

export type MessageCreateInput = z.infer<typeof MessageCreateSchema>
