// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { MessageCreateSchema } from './message.create.zod.js'

export const MessageUpdateSchema = MessageCreateSchema.partial()

export type MessageUpdateInput = z.infer<typeof MessageUpdateSchema>
