// @generated
// This file is automatically generated. Do not edit manually.

import { AccountStatus } from '@prisma/client'

export interface UserReadDTO {
  id: string
  email: string
  passwordHash: string | null
  oauthProvider: string | null
  oauthId: string | null
  accountStatus: AccountStatus
  createdAt: Date
  updatedAt: Date
  lastLoginAt: Date | null
}
