// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { QuizQuestionCreateSchema } from './quiz-question.create.zod.js'

export const QuizQuestionUpdateSchema = QuizQuestionCreateSchema.partial()

export type QuizQuestionUpdateInput = z.infer<typeof QuizQuestionUpdateSchema>
