// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { QuizQuestionType } from '@prisma/client'

export const QuizQuestionQuerySchema = z.object({
  skip: z.coerce.number().min(0).optional(),
  take: z.coerce.number().min(1).max(100).optional().default(20),
  orderBy: z.object({
    id: z.enum(['asc', 'desc']).optional(),
    quizId: z.enum(['asc', 'desc']).optional(),
    type: z.enum(['asc', 'desc']).optional(),
    order: z.enum(['asc', 'desc']).optional(),
    configJson: z.enum(['asc', 'desc']).optional(),
    createdAt: z.enum(['asc', 'desc']).optional(),
    quiz: z.record(z.enum(['asc', 'desc'])).optional(),
    answers: z.record(z.enum(['asc', 'desc'])).optional()
  }).optional(),
  where: z.object({
    id: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    quizId: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    type: z.nativeEnum(QuizQuestionType).optional(),
    order: z.object({
      equals: z.number().optional(),
      gt: z.number().optional(),
      gte: z.number().optional(),
      lt: z.number().optional(),
      lte: z.number().optional()
    }).optional(),
    createdAt: z.object({
      equals: z.coerce.date().optional(),
      gt: z.coerce.date().optional(),
      gte: z.coerce.date().optional(),
      lt: z.coerce.date().optional(),
      lte: z.coerce.date().optional()
    }).optional()
  }).optional(),
  include: z.object({
    quiz: z.boolean().optional(),
    answers: z.boolean().optional()
  }).optional(),
  select: z.object({
    id: z.boolean().optional(),
    quizId: z.boolean().optional(),
    type: z.boolean().optional(),
    order: z.boolean().optional(),
    configJson: z.boolean().optional(),
    createdAt: z.boolean().optional(),
    quiz: z.boolean().optional(),
    answers: z.boolean().optional()
  }).optional()
})

export type QuizQuestionQueryInput = z.infer<typeof QuizQuestionQuerySchema>
