// @generated
// This file is automatically generated. Do not edit manually.

/**
 * Schema hash for version checking
 * Regenerate SDK if backend schema hash differs
 */
export const SCHEMA_HASH = 'development'

/**
 * Generator tool version
 */
export const TOOL_VERSION = '0.0.0-dev'

/**
 * Check if SDK version matches backend
 */
export function checkVersion(backendHash: string): {
  compatible: boolean
  message?: string
} {
  if (backendHash === SCHEMA_HASH) {
    return { compatible: true }
  }
  
  return {
    compatible: false,
    message: `SDK version mismatch. SDK: ${SCHEMA_HASH.slice(0, 8)}, Backend: ${backendHash.slice(0, 8)}. Please regenerate SDK.`
  }
}
