// @generated
// This file is automatically generated. Do not edit manually.

import { SwipeType } from '@prisma/client'

import type { SwipeReadDTO } from './swipe.read.dto.js'

type SwipeWhereInput = {
    id?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    type?: SwipeType | {
      equals?: SwipeType
      in?: SwipeType[]
      notIn?: SwipeType[]
      not?: SwipeType
    }
    createdAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    AND?: SwipeWhereInput[]
    OR?: SwipeWhereInput[]
    NOT?: SwipeWhereInput[]
  }

export interface SwipeQueryDTO {
  skip?: number  // Offset pagination (should be >= 0)
  take?: number  // Limit (should be > 0)
  cursor?: string  // Cursor for cursor-based pagination
  orderBy?: {
    id?: 'asc' | 'desc'
    swiperId?: 'asc' | 'desc'
    swipedId?: 'asc' | 'desc'
    type?: 'asc' | 'desc'
    createdAt?: 'asc' | 'desc'
    swiper?: { [key: string]: 'asc' | 'desc' }
    swiped?: { [key: string]: 'asc' | 'desc' }
  }
  where?: SwipeWhereInput
  include?: {
    swiper?: boolean | { include?: any; select?: any }
    swiped?: boolean | { include?: any; select?: any }
  }
  select?: {
    id?: boolean
    swiperId?: boolean
    swipedId?: boolean
    type?: boolean
    createdAt?: boolean
    swiper?: boolean | { select?: any; include?: any }
    swiped?: boolean | { select?: any; include?: any }
  }
  distinct?: 'id' | 'type' | 'createdAt' | Array<'id' | 'type' | 'createdAt'>
}

export interface SwipeListResponse {
  data: SwipeReadDTO[]
  meta: {
    total: number
    skip: number
    take: number
    hasMore: boolean  // Calculated as: skip + take < total
  }
}
