// @generated
// This file is automatically generated. Do not edit manually.

import { SwipeType } from '@prisma/client'

export interface SwipeReadDTO {
  id: string
  swiperId: string
  swipedId: string
  type: SwipeType
  createdAt: Date
}
