// @generated
// This file is automatically generated. Do not edit manually.

import type { UserDimensionScoreUpdateInput } from '@/validators/user-dimension-score/user-dimension-score.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see UserDimensionScoreUpdateSchema in validators
 */
export type UserDimensionScoreUpdateDTO = UserDimensionScoreUpdateInput
