// @generated
// This file is automatically generated. Do not edit manually.

import prisma from '@/db'
import type { EventWeightConfigCreateDTO, EventWeightConfigUpdateDTO, EventWeightConfigQueryDTO } from '@/contracts/event-weight-config'
import type { Prisma } from '@prisma/client'
import { EventType } from '@prisma/client'
import { logger } from '@/logger'

export const eventWeightConfigService = {
  /**
   * List EventWeightConfig records with pagination
   */
  async list(query: EventWeightConfigQueryDTO) {
    const { skip = 0, take = 20, orderBy, where, include, select } = query
    
    logger.debug({ skip, take }, 'Listing EventWeightConfig records')
    
    const whereWithSoftDelete = where
    
    const [items, total] = await Promise.all([
      prisma.eventWeightConfig.findMany({
        skip,
        take,
        ...(orderBy && { orderBy: orderBy as Prisma.EventWeightConfigOrderByWithRelationInput }),
        ...(whereWithSoftDelete && { where: whereWithSoftDelete as Prisma.EventWeightConfigWhereInput }),
        ...(include && { include: include as Prisma.EventWeightConfigInclude }),
        ...(select && { select: select as Prisma.EventWeightConfigSelect })
      }),
      prisma.eventWeightConfig.count({
        where: whereWithSoftDelete as Prisma.EventWeightConfigWhereInput,
      })
    ])
    
    return {
      data: items,
      meta: {
        total,
        skip,
        take,
        hasMore: skip + take < total
      }
    }
  },
  
  /**
   * Find EventWeightConfig by ID
   */
  async findById(id: string) {
    return prisma.eventWeightConfig.findUnique({
      where: { id }
    })
  },
  
  /**
   * Create EventWeightConfig
   */
  async create(data: Prisma.EventWeightConfigCreateInput) {
    const item = await prisma.eventWeightConfig.create({
      data
    })
    logger.info({ eventWeightConfigId: item.id }, 'EventWeightConfig created')
    return item
  },
  
  /**
   * Update EventWeightConfig
   */
  async update(id: string, data: EventWeightConfigUpdateDTO) {
    const item = await prisma.eventWeightConfig.update({
      where: { id },
      data: data as Prisma.EventWeightConfigUpdateInput
    })
    logger.info({ eventWeightConfigId: id }, 'EventWeightConfig updated')
    return item
  },
  
  /**
   * Delete EventWeightConfig
   */
  async delete(id: string) {
    await prisma.eventWeightConfig.delete({
      where: { id }
    })
    logger.info({ eventWeightConfigId: id }, 'EventWeightConfig deleted')
    return true
  },
  
  /**
   * Count EventWeightConfig records
   */
  async count(where?: Prisma.EventWeightConfigWhereInput) {
    return prisma.eventWeightConfig.count({ where })
  },
  
  /**
   * Check if EventWeightConfig exists
   */
  async exists(id: string) {
    const count = await prisma.eventWeightConfig.count({
      where: { id }
    })
    return count > 0
  },
  
  /**
   * Create multiple EventWeightConfig records (bulk operation)
   */
  async createMany(data: Prisma.EventWeightConfigCreateManyInput[]) {
    const result = await prisma.eventWeightConfig.createMany({
      data,
      skipDuplicates: true
    })
    logger.info({ count: result.count }, 'EventWeightConfig bulk created')
    return result
  },
  
  /**
   * Update multiple EventWeightConfig records (bulk operation)
   */
  async updateMany(where: Prisma.EventWeightConfigWhereInput, data: Prisma.EventWeightConfigUpdateManyMutationInput) {
    const result = await prisma.eventWeightConfig.updateMany({
      where,
      data
    })
    logger.info({ count: result.count }, 'EventWeightConfig bulk updated')
    return result
  },
  
  /**
   * Delete multiple EventWeightConfig records (bulk operation)
   */
  async deleteMany(where: Prisma.EventWeightConfigWhereInput) {
    const result = await prisma.eventWeightConfig.deleteMany({ where })
    logger.info({ count: result.count }, 'EventWeightConfig bulk deleted')
    return result
  },

  /**
   * Search EventWeightConfigs with text query and filters
   * Auto-generated from searchable fields: description
   */
  async search(params: {
    q: string
    eventType?: EventType
    minBaseWeight?: number
    maxBaseWeight?: number
    isActive?: boolean
    description?: string
    minCreatedAt?: Date | string
    maxCreatedAt?: Date | string
    skip?: number
    take?: number
  }) {
    const where: Prisma.EventWeightConfigWhereInput = {
      AND: [
        params.q ? {
          OR: [
            { description: { contains: params.q } }
          ]
        } : {},
        params.eventType ? { eventType: params.eventType } : {},
        params.minBaseWeight ? { baseWeight: { gte: params.minBaseWeight } } : {},
        params.maxBaseWeight ? { baseWeight: { lte: params.maxBaseWeight } } : {},
        params.isActive !== undefined ? { isActive: params.isActive } : {},
        params.description ? { description: params.description } : {},
        params.minCreatedAt ? { createdAt: { gte: params.minCreatedAt } } : {},
        params.maxCreatedAt ? { createdAt: { lte: params.maxCreatedAt } } : {}
      ].filter(condition => Object.keys(condition).length > 0)
    }
    
    return prisma.eventWeightConfig.findMany({
      where,
      skip: params.skip || 0,
      take: Math.min(params.take || 20, 100)
    })
  },

  /**
   * Get active EventWeightConfigs
   * Auto-generated from 'isActive' field detection
   */
  async getActive(query?: Prisma.EventWeightConfigWhereInput) {
    return prisma.eventWeightConfig.findMany({
      where: {
        isActive: true,
        ...query
      }
    })
  }
}
