// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { EventType, TargetType } from '@prisma/client'

export const BehaviorEventArchiveCreateSchema = z.object({
  userId: z.string().min(1, 'userId is required'),
  eventType: z.nativeEnum(EventType),
  targetType: z.nativeEnum(TargetType),
  targetId: z.string().min(1, 'targetId is required'),
  meta: z.record(z.any()),
  processedAt: z.coerce.date().nullable().optional(),
  ruleVersion: z.string().nullable().optional(),
  createdAt: z.coerce.date(),
  archivedAt: z.coerce.date().optional().default(new Date())
})

export type BehaviorEventArchiveCreateInput = z.infer<typeof BehaviorEventArchiveCreateSchema>
