// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { TargetType } from '@prisma/client'

export const DimensionMappingRuleCreateSchema = z.object({
  eventType: z.string().min(1, 'eventType is required'),
  targetType: z.nativeEnum(TargetType),
  metaKey: z.string().min(1, 'metaKey is required'),
  metaValue: z.string().nullable().optional(),
  weight: z.number().optional().default(1),
  isActive: z.boolean().optional().default(true),
  version: z.string().min(1, 'version is required').optional().default("v1.0"),
  matchType: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional().default(new Date())
})

export type DimensionMappingRuleCreateInput = z.infer<typeof DimensionMappingRuleCreateSchema>
