// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { DimensionMappingRuleCreateSchema } from './dimension-mapping-rule.create.zod.js'

export const DimensionMappingRuleUpdateSchema = DimensionMappingRuleCreateSchema.partial()

export type DimensionMappingRuleUpdateInput = z.infer<typeof DimensionMappingRuleUpdateSchema>
