/**
 * Auth Middleware Generator
 * 
 * Generates authentication gate for admin routes
 */

import fs from 'node:fs'
import path from 'node:path'

/**
 * Generate authenticated middleware
 * Guards /admin routes
 */
export function generateAuthMiddleware(projectPath: string): void {
  const content = `/**
 * Generated by SSOT CodeGen
 * Authentication middleware for admin routes
 * 
 * ✨ SAFE TO EDIT - Add your auth logic here
 */

import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

export function middleware(request: NextRequest) {
  // TODO: Add authentication check
  // Example with NextAuth:
  // import { getToken } from 'next-auth/jwt'
  // const token = await getToken({ req: request })
  // if (!token) {
  //   return NextResponse.redirect(new URL('/login', request.url))
  // }
  
  // For now, allow through but log warning
  if (process.env.NODE_ENV === 'development') {
    console.warn('⚠️  Admin routes are not authenticated. Add auth logic in middleware.ts')
  }
  
  return NextResponse.next()
}

export const config = {
  matcher: '/admin/:path*'
}
`
  
  const filePath = path.join(projectPath, 'middleware.ts')
  
  // Skip if already exists (don't overwrite user auth logic)
  if (fs.existsSync(filePath)) {
    console.log('  ⏭️  Skipping middleware.ts (already exists)')
    return
  }
  
  fs.writeFileSync(filePath, content, 'utf-8')
  console.log('  ✅ Generated middleware.ts (auth gate)')
}

