/**
 * UI Generator Fixes
 * 
 * Critical fixes for ui-generator.ts:
 * 1. ID handling (string PKs)
 * 2. Authentication gate
 * 3. SDK path resolution
 * 4. Module format consistency
 * 5. Safe file writing
 */

import fs from 'node:fs'
import path from 'node:path'

/**
 * Enhanced ParsedModel with ID field info
 */
export interface EnrichedModel {
  name: string
  nameLower: string
  namePlural: string
  idField: {
    name: string
    type: string  // 'String' | 'Int' | 'BigInt'
  }
  fields: Array<{
    name: string
    type: string
    isRelation: boolean
    isId?: boolean
  }>
}

/**
 * Extract ID field from model
 * Pure function, no side effects
 */
export function extractIdField(model: any): { name: string; type: string } {
  // Find @id field
  const idField = model.fields.find((f: any) => f.isId)
  
  if (idField) {
    return { name: idField.name, type: idField.type }
  }
  
  // Fallback to 'id' field
  const defaultId = model.fields.find((f: any) => f.name === 'id')
  if (defaultId) {
    return { name: 'id', type: defaultId.type }
  }
  
  // Last resort fallback
  return { name: 'id', type: 'Int' }
}

/**
 * Generate ID parameter access
 * Handles String, Int, BigInt types correctly
 */
export function generateIdParam(idField: { name: string; type: string }): string {
  switch (idField.type) {
    case 'String':
      return 'params.id'
    case 'Int':
      return 'Number(params.id)'
    case 'BigInt':
      return 'BigInt(params.id)'
    default:
      // String-like types (cuid, uuid, etc.)
      return 'params.id'
  }
}

/**
 * Generate authenticated middleware
 * Guards /admin routes
 */
export function generateAuthMiddleware(projectPath: string): void {
  const content = `/**
 * Generated by SSOT CodeGen
 * Authentication middleware for admin routes
 * 
 * ✨ SAFE TO EDIT - Add your auth logic here
 */

import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

export function middleware(request: NextRequest) {
  // TODO: Add authentication check
  // Example with NextAuth:
  // const token = await getToken({ req: request })
  // if (!token) {
  //   return NextResponse.redirect(new URL('/login', request.url))
  // }
  
  // For now, allow through but log warning
  if (process.env.NODE_ENV === 'development') {
    console.warn('⚠️  Admin routes are not authenticated. Add auth logic in middleware.ts')
  }
  
  return NextResponse.next()
}

export const config = {
  matcher: '/admin/:path*'
}
`
  
  const filePath = path.join(projectPath, 'middleware.ts')
  writeFileSafe(filePath, content, { skipIfExists: true })
}

/**
 * Generate unauthenticated banner
 */
export function generateUnauthBanner(): string {
  return `      {process.env.NODE_ENV === 'development' && (
        <div className="bg-yellow-50 border-b border-yellow-200 px-4 py-3">
          <p className="text-sm text-yellow-800">
            ⚠️ <strong>No authentication</strong> - Add auth logic in <code>middleware.ts</code>
          </p>
        </div>
      )}
`
}

/**
 * Safe file writer with preservation logic
 * Respects user edits, only overwrites with --force
 */
export function writeFileSafe(
  filepath: string,
  content: string,
  options: {
    skipIfExists?: boolean
    preserveMarkers?: string[]
    force?: boolean
  } = {}
): boolean {
  // Skip if file exists and skipIfExists is true
  if (options.skipIfExists && fs.existsSync(filepath)) {
    console.log(`  ⏭️  Skipping ${filepath} (already exists)`)
    return false
  }
  
  // If force, always write
  if (options.force) {
    fs.writeFileSync(filepath, content, 'utf-8')
    return true
  }
  
  // If file exists, preserve user edits
  if (fs.existsSync(filepath)) {
    const existing = fs.readFileSync(filepath, 'utf-8')
    
    // Check for user edit marker
    if (existing.includes('SAFE TO EDIT') || existing.includes('USER EDIT')) {
      console.log(`  ⏭️  Preserving ${filepath} (contains user edits)`)
      return false
    }
    
    // No user edits detected, safe to overwrite
    fs.writeFileSync(filepath, content, 'utf-8')
    return true
  }
  
  // New file, write it
  fs.writeFileSync(filepath, content, 'utf-8')
  return true
}

/**
 * Generate ESM config files (not CJS)
 */
export function generateTailwindConfigESM(): string {
  return `/**
 * Generated by SSOT CodeGen
 * Tailwind configuration (ESM)
 */

import tokens from '@ssot-ui/tokens/tailwind'

export default {
  ...tokens,
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/@ssot-ui/**/*.{js,ts,jsx,tsx}'
  ]
}
`
}

export function generateNextConfigESM(): string {
  return `/**
 * Generated by SSOT CodeGen
 * Next.js configuration (ESM)
 */

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: ['@ssot-ui/data-table', '@ssot-ui/tokens']
}

export default nextConfig
`
}

/**
 * Generate detail page with correct ID handling
 */
export function generateDetailPageFixed(model: EnrichedModel): string {
  const idParam = generateIdParam(model.idField)
  const displayFields = model.fields.filter(f => 
    !f.name.toLowerCase().includes('password') && 
    !f.name.toLowerCase().includes('hash')
  )
  
  return `/**
 * Generated by SSOT CodeGen
 * ${model.name} detail page
 * 
 * ✨ SAFE TO EDIT - Customize layout and fields
 */

'use client'

import { use${model.name} } from '@/generated/sdk'
import Link from 'next/link'

export default function ${model.name}DetailPage({
  params
}: {
  params: { id: string }
}) {
  const { data: ${model.nameLower}, isLoading, error } = use${model.name}(${idParam})
  
  if (isLoading) {
    return (
      <div className="p-8">
        <div className="animate-pulse">
          <div className="h-8 bg-neutral-200 rounded w-1/4 mb-4"></div>
          <div className="h-4 bg-neutral-200 rounded w-1/2"></div>
        </div>
      </div>
    )
  }
  
  if (error || !${model.nameLower}) {
    return (
      <div className="p-8">
        <div className="bg-red-50 border border-red-200 text-red-700 p-4 rounded-md">
          {error?.message || '${model.name} not found'}
        </div>
      </div>
    )
  }
  
  return (
    <div className="p-8">
      <div className="mb-6">
        <Link 
          href="/admin/${model.namePlural}"
          className="text-blue-600 hover:underline mb-2 inline-block"
        >
          ← Back to ${model.name}s
        </Link>
        <h1 className="text-3xl font-bold">
          ${model.name} #{${model.nameLower}.${model.idField.name}}
        </h1>
      </div>
      
      <div className="bg-white rounded-lg border border-neutral-200 p-6">
        <dl className="grid grid-cols-1 md:grid-cols-2 gap-4">
          ${displayFields.map(f => `
          <div>
            <dt className="text-sm font-medium text-neutral-500">${formatFieldLabel(f.name)}</dt>
            <dd className="mt-1 text-sm text-neutral-900">
              {${formatFieldValue(f, model.nameLower)}}
            </dd>
          </div>`).join('')}
        </dl>
      </div>
    </div>
  )
}
`
}

/**
 * Generate list page with correct ID handling
 */
export function generateListPageFixed(model: EnrichedModel): string {
  const displayFields = model.fields
    .filter(f => !f.name.toLowerCase().includes('password'))
    .slice(0, 5)
  
  return `/**
 * Generated by SSOT CodeGen
 * ${model.name} list page
 */

'use client'

import { DataTable } from '@ssot-ui/data-table'
import '@ssot-ui/data-table/styles.css'
import { use${model.name}List } from '@/generated/sdk'
import Link from 'next/link'

export default function ${model.name}ListPage() {
  return (
    <div className="p-8">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-3xl font-bold">${model.name}s</h1>
          <p className="text-neutral-600">Browse all ${model.nameLower} records</p>
        </div>
      </div>
      
      <DataTable
        hook={use${model.name}List}
        columns={[${displayFields.map(f => `
          {
            key: '${f.name}',
            header: '${formatFieldLabel(f.name)}',
            sortable: ${!f.isRelation},
            cellRender: (value, row) => (
              <Link 
                href={\`/admin/${model.namePlural}/\${row.${model.idField.name}}\`}
                className="text-blue-600 hover:underline"
              >
                {${f.isRelation ? `value?.name || value?.title || '[${f.type}]'` : 'value'}}
              </Link>
            )
          }`).join(',')
        }]}
        searchable={${JSON.stringify(displayFields.filter(f => !f.isRelation && f.type === 'String').map(f => f.name))}}
        pagination="pages"
        defaultPageSize={20}
      />
    </div>
  )
}
`
}

/**
 * Helper: Format field value (pure)
 */
function formatFieldValue(field: any, modelVar: string): string {
  if (field.isRelation) {
    return `${modelVar}.${field.name}?.name || ${modelVar}.${field.name}?.title || '[${field.type}]'`
  }
  
  if (field.type === 'DateTime') {
    return `new Date(${modelVar}.${field.name}).toLocaleString()`
  }
  
  if (field.type === 'Boolean') {
    return `${modelVar}.${field.name} ? '✓ Yes' : '○ No'`
  }
  
  return `${modelVar}.${field.name} || '-'`
}

/**
 * Helper: Format field label (pure)
 */
function formatFieldLabel(name: string): string {
  return name
    .replace(/([A-Z])/g, ' $1')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, l => l.toUpperCase())
    .trim()
}

/**
 * Generate admin layout with auth banner
 */
export function generateAdminLayoutFixed(models: EnrichedModel[]): string {
  return `/**
 * Generated by SSOT CodeGen
 * Admin panel layout with navigation
 * 
 * ✨ SAFE TO EDIT - Customize navigation and styling
 */

import Link from 'next/link'

export default function AdminLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex flex-col h-screen bg-neutral-50">
      {/* Auth warning banner */}
${generateUnauthBanner()}
      
      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar */}
        <aside className="w-64 bg-white border-r border-neutral-200 overflow-y-auto">
          <div className="p-6 border-b border-neutral-200">
            <h1 className="text-xl font-bold">Admin Panel</h1>
            <p className="text-sm text-neutral-600">Data Browser</p>
          </div>
          
          <nav className="p-4">
            <Link
              href="/admin"
              className="block px-4 py-2 rounded-md hover:bg-neutral-100 text-neutral-700 hover:text-neutral-900"
            >
              📊 Dashboard
            </Link>
            
            <div className="mt-6">
              <h3 className="px-4 text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-2">
                Models
              </h3>
              ${models.map(model => `
              <Link
                href="/admin/${model.namePlural}"
                className="block px-4 py-2 rounded-md hover:bg-neutral-100 text-neutral-700 hover:text-neutral-900"
              >
                📝 ${model.name}s
              </Link>`).join('')}
            </div>
          </nav>
        </aside>
        
        {/* Main content */}
        <main className="flex-1 overflow-auto">
          {children}
        </main>
      </div>
    </div>
  )
}
`
}

