/**
 * UI generation for create-ssot-app
 * Generates Next.js pages using @ssot-ui components
 */

import type { ProjectConfig } from './prompts.js'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { generateAuthMiddleware } from './ui-generator-auth.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

export interface ParsedModel {
  name: string
  nameLower: string
  namePlural: string
  idField: {
    name: string
    type: string  // 'String' | 'Int' | 'BigInt' | string-like (uuid, cuid, etc.)
  }
  fields: Array<{
    name: string
    type: string
    isRelation: boolean
    isId?: boolean
  }>
}

/**
 * Generate ID parameter access - always pass as string to SDK
 * SDK will coerce on server side as needed
 */
function generateIdParam(_idField: { name: string; type: string }): string {
  return 'params.id'
}

/**
 * Safe file writer with edit detection
 */
function writeFileSafe(filepath: string, content: string, skipIfExists = false): void {
  if (skipIfExists && fs.existsSync(filepath)) {
    console.log(`  ⏭️  Skipping ${path.basename(filepath)} (already exists)`)
    return
  }
  
  // Check for user edits before overwriting
  if (fs.existsSync(filepath)) {
    const existing = fs.readFileSync(filepath, 'utf-8')
    // Detect if file was generated by us and is still unmodified
    const hasGenMarker = existing.includes('Generated by SSOT CodeGen')
    if (hasGenMarker && !content.includes('Generated by SSOT CodeGen')) {
      // Don't overwrite generated files with non-generated content
      return
    }
    // Check for explicit user markers
    if (existing.includes('USER EDIT') || existing.includes('// Custom:')) {
      console.log(`  ⏭️  Preserving ${path.basename(filepath)} (user edits detected)`)
      return
    }
  }
  
  // Ensure parent directory exists
  fs.mkdirSync(path.dirname(filepath), { recursive: true })
  fs.writeFileSync(filepath, content, 'utf-8')
}

/**
 * Generate UI files based on template selection
 */
export async function generateUI(projectPath: string, config: ProjectConfig, models: ParsedModel[], mappings?: Record<string, unknown>): Promise<void> {
  if (!config.generateUI || !config.uiTemplate) {
    return
  }
  
  // Generate auth middleware for admin routes
  generateAuthMiddleware(projectPath)
  
  // V3 Runtime (JSON only, no code generation)
  if (config.uiMode === 'v3-runtime') {
    const { generateV3UI } = await import('./v3-ui-generator.js')
    await generateV3UI(projectPath, config, models)
    return
  }
  
  // V2 Code Generation (legacy)
  switch (config.uiTemplate) {
    case 'data-browser':
      generateDataBrowser(projectPath, config, models)
      break
    case 'blog': {
      const { generateBlogTemplate } = await import('./templates/blog-generator.js')
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      generateBlogTemplate(projectPath, config, models, mappings as any)
      break
    }
    case 'chatbot': {
      const { generateChatbotTemplate } = await import('./templates/chatbot-generator.js')
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      await generateChatbotTemplate(projectPath, config, models, mappings as any)
      break
    }
    case 'ecommerce':
    case 'dashboard':
      // Not implemented yet
      console.log(`\n⚠️  ${config.uiTemplate} template coming soon`)
      break
  }
}

/**
 * Generate Data Browser UI (read-only admin panel)
 */
function generateDataBrowser(projectPath: string, config: ProjectConfig, models: ParsedModel[]): void {
  // Filter out join tables and composite PK models
  const validModels = models.filter(m => m.idField && m.fields.length > 1)
  
  // Create app directory for Next.js
  const appDir = path.join(projectPath, 'app')
  const adminDir = path.join(appDir, 'admin')
  const componentsDir = path.join(projectPath, 'components')
  
  fs.mkdirSync(appDir, { recursive: true })
  fs.mkdirSync(adminDir, { recursive: true })
  fs.mkdirSync(componentsDir, { recursive: true })
  
  // Generate shared components
  writeFileSafe(
    path.join(componentsDir, 'loading.tsx'),
    generateLoadingComponent()
  )
  
  writeFileSafe(
    path.join(componentsDir, 'error-message.tsx'),
    generateErrorComponent()
  )
  
  // Generate root layout
  writeFileSafe(
    path.join(appDir, 'layout.tsx'),
    generateRootLayout(config)
  )
  
  // Generate admin layout with navigation
  writeFileSafe(
    path.join(adminDir, 'layout.tsx'),
    generateAdminLayout(validModels)
  )
  
  // Generate admin dashboard (home)
  writeFileSafe(
    path.join(adminDir, 'page.tsx'),
    generateDashboard(validModels)
  )
  
  // Generate a page for each model
  for (const model of validModels) {
    const modelDir = path.join(adminDir, model.namePlural)
    fs.mkdirSync(modelDir, { recursive: true })
    
    // List page
    writeFileSafe(
      path.join(modelDir, 'page.tsx'),
      generateModelListPage(model)
    )
    
    // Detail page
    const detailDir = path.join(modelDir, '[id]')
    fs.mkdirSync(detailDir, { recursive: true })
    writeFileSafe(
      path.join(detailDir, 'page.tsx'),
      generateModelDetailPage(model)
    )
  }
  
  // Generate globals.css with Tailwind
  writeFileSafe(
    path.join(appDir, 'globals.css'),
    generateGlobalCSS()
  )
  
  // Generate tailwind.config.ts (ESM)
  writeFileSafe(
    path.join(projectPath, 'tailwind.config.ts'),
    generateTailwindConfig(),
    true  // Skip if exists
  )
  
  // Generate next.config.mjs (ESM)
  writeFileSafe(
    path.join(projectPath, 'next.config.mjs'),
    generateNextConfig(),
    true  // Skip if exists
  )
  
  // Generate tsconfig.json for Next.js
  writeFileSafe(
    path.join(projectPath, 'tsconfig.json'),
    generateNextTSConfig(),
    true  // Skip if exists
  )
  
  // Generate UI README
  writeFileSafe(
    path.join(projectPath, 'UI_README.md'),
    generateUIReadme(validModels)
  )
}

/**
 * Generate root layout.tsx
 */
function generateRootLayout(config: ProjectConfig): string {
  return `/**
 * Generated by SSOT CodeGen
 * Root layout for Next.js app
 * 
 * ✨ SAFE TO EDIT - Your changes preserved
 */

import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: '${config.projectName} - Admin',
  description: 'Data browser generated by SSOT CodeGen'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`
}

/**
 * Generate admin layout with sidebar navigation
 */
function generateAdminLayout(models: ParsedModel[]): string {
  return `/**
 * Generated by SSOT CodeGen
 * Admin panel layout with navigation
 * 
 * ✨ SAFE TO EDIT - Customize navigation and styling
 */

import Link from 'next/link'

export default function AdminLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex flex-col h-screen bg-neutral-50">
      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar */}
        <aside className="w-64 bg-white border-r border-neutral-200 overflow-y-auto">
        <div className="p-6 border-b border-neutral-200">
          <h1 className="text-xl font-bold">Admin Panel</h1>
          <p className="text-sm text-neutral-600">Data Browser</p>
        </div>
        
        <nav className="p-4">
          <Link
            href="/admin"
            className="block px-4 py-2 rounded-md hover:bg-neutral-100 text-neutral-700 hover:text-neutral-900 focus:outline-none focus:ring-2 focus:ring-primary-500"
          >
            📊 Dashboard
          </Link>
          
          <div className="mt-6">
            <h3 className="px-4 text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-2">
              Models
            </h3>
            ${models.map(model => `
            <Link
              href="/admin/${model.namePlural}"
              className="block px-4 py-2 rounded-md hover:bg-neutral-100 text-neutral-700 hover:text-neutral-900 focus:outline-none focus:ring-2 focus:ring-primary-500"
            >
              📝 ${model.namePlural}
            </Link>`).join('')}
          </div>
        </nav>
      </aside>
      
        {/* Main content */}
        <main className="flex-1 overflow-auto" role="main">
          {children}
        </main>
      </div>
    </div>
  )
}
`
}

/**
 * Generate dashboard page
 */
function generateDashboard(models: ParsedModel[]): string {
  return `/**
 * Generated by SSOT CodeGen
 * Admin dashboard
 */

import Link from 'next/link'

export default function DashboardPage() {
  return (
    <div className="p-8">
      <h1 className="text-3xl font-bold mb-2">Dashboard</h1>
      <p className="text-neutral-600 mb-8">
        Browse your data - Generated by SSOT CodeGen
      </p>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        ${models.map(model => `
        <Link
          href="/admin/${model.namePlural}"
          className="block p-6 bg-white rounded-lg border border-neutral-200 hover:border-primary-300 hover:shadow-md transition-all focus:outline-none focus:ring-2 focus:ring-primary-500"
        >
          <h2 className="text-xl font-semibold mb-2">📝 ${model.namePlural}</h2>
          <p className="text-neutral-600 text-sm">
            Browse all ${model.nameLower} records
          </p>
        </Link>`).join('')}
      </div>
      
      <div className="mt-12 p-6 bg-blue-50 border border-blue-200 rounded-lg">
        <h3 className="font-semibold mb-2">🎨 Generated UI</h3>
        <p className="text-sm text-neutral-700">
          This admin panel was auto-generated from your Prisma schema using SSOT CodeGen.
          All pages use the <code className="px-1 py-0.5 bg-white rounded">@ssot-ui/data-table</code> component.
        </p>
        <p className="text-sm text-neutral-600 mt-2">
          See <code>UI_README.md</code> for customization options.
        </p>
      </div>
    </div>
  )
}
`
}

/**
 * Generate list page for a model
 */
function generateModelListPage(model: ParsedModel): string {
  // Select display fields intelligently
  const sensitivePatterns = ['password', 'hash', 'token', 'secret']
  const nonSensitiveFields = model.fields.filter(f => 
    !sensitivePatterns.some(p => f.name.toLowerCase().includes(p))
  )
  
  // Prioritize: id, name/title, then others (max 5)
  const priorityFields = nonSensitiveFields.filter(f => 
    f.isId || f.name.toLowerCase() === 'name' || f.name.toLowerCase() === 'title'
  )
  const otherFields = nonSensitiveFields.filter(f => 
    !f.isId && f.name.toLowerCase() !== 'name' && f.name.toLowerCase() !== 'title'
  )
  const displayFields = [...priorityFields, ...otherFields].slice(0, 5)
  
  // Select searchable fields
  const searchableFields = displayFields
    .filter(f => !f.isRelation && f.type === 'String')
    .map(f => f.name)
  
  return `/**
 * Generated by SSOT CodeGen
 * ${model.name} list page
 * 
 * ✨ SAFE TO EDIT - Customize columns, filters, and behavior
 * 🔄 To regenerate: pnpm ssot generate --ui
 */

'use client'

import { DataTable } from '@ssot-ui/data-table'
import '@ssot-ui/data-table/styles.css'
import { use${model.name}List } from '@/generated/sdk/hooks/react/use-${model.nameLower}'
import Link from 'next/link'

export default function ${model.name}ListPage() {
  return (
    <div className="p-8">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-3xl font-bold">${model.namePlural}</h1>
          <p className="text-neutral-600">
            Browse all ${model.nameLower} records
          </p>
        </div>
      </div>
      
      <DataTable
        hook={use${model.name}List}
        idAccessor="${model.idField.name}"
        columns={[${displayFields.map(f => `
          {
            key: '${f.name}',
            header: '${formatFieldLabel(f.name)}',
            sortable: ${!f.isRelation},${f.name === model.idField.name ? '' : `
            cellRender: (value, row) => (
              <Link 
                href={\`/admin/${model.namePlural}/\${encodeURIComponent(String(row.${model.idField.name}))}\`}
                className="text-primary-600 hover:underline focus:outline-none focus:ring-2 focus:ring-primary-500"
              >
                {${f.isRelation ? `value?.name || value?.title || '-'` : f.type === 'Boolean' ? `value ? '✓' : '○'` : 'value'}}
              </Link>
            )`}
          }`).join(',')
        }]}${searchableFields.length > 0 ? `
        searchable={${JSON.stringify(searchableFields)}}` : ''}
        pagination="pages"
        defaultPageSize={20}
      />
    </div>
  )
}
`
}

/**
 * Generate detail page for a model
 */
function generateModelDetailPage(model: ParsedModel): string {
  const sensitivePatterns = ['password', 'hash', 'token', 'secret']
  const displayFields = model.fields.filter(f => 
    !sensitivePatterns.some(p => f.name.toLowerCase().includes(p))
  )
  
  return `/**
 * Generated by SSOT CodeGen
 * ${model.name} detail page
 * 
 * ✨ SAFE TO EDIT - Customize layout and fields
 */

'use client'

import { use${model.name} } from '@/generated/sdk/hooks/react/use-${model.nameLower}'
import Link from 'next/link'
import { Loading } from '@/components/loading'
import { ErrorMessage } from '@/components/error-message'

export default function ${model.name}DetailPage({
  params
}: {
  params: { id: string }
}) {
  const { data: ${model.nameLower}, isLoading, error } = use${model.name}(${generateIdParam(model.idField)})
  
  if (isLoading) {
    return <Loading />
  }
  
  if (error || !${model.nameLower}) {
    return (
      <div className="p-8">
        <ErrorMessage message={error?.message || '${model.name} not found'} />
      </div>
    )
  }
  
  const idValue = ${model.nameLower}.${model.idField.name}
  
  return (
    <div className="p-8">
      <div className="mb-6">
        <Link 
          href="/admin/${model.namePlural}"
          className="text-primary-600 hover:underline mb-2 inline-block focus:outline-none focus:ring-2 focus:ring-primary-500"
        >
          ← Back to ${model.namePlural}
        </Link>
        <h1 className="text-3xl font-bold">
          ${model.name} #{idValue ?? 'Unknown'}
        </h1>
      </div>
      
      <div className="bg-white rounded-lg border border-neutral-200 p-6">
        <dl className="grid grid-cols-1 md:grid-cols-2 gap-4">
          ${displayFields.map(f => `
          <div>
            <dt className="text-sm font-medium text-neutral-500">${formatFieldLabel(f.name)}</dt>
            <dd className="mt-1 text-sm text-neutral-900">
              {${f.isRelation 
                ? `${model.nameLower}.${f.name}?.name || ${model.nameLower}.${f.name}?.title || '-'`
                : f.type === 'DateTime'
                  ? `${model.nameLower}.${f.name} ? new Date(${model.nameLower}.${f.name}).toLocaleString() : '-'`
                  : f.type === 'Boolean'
                    ? `${model.nameLower}.${f.name} ? '✓ Yes' : '○ No'`
                    : `${model.nameLower}.${f.name} ?? '-'`
              }}
            </dd>
          </div>`).join('')}
        </dl>
      </div>
    </div>
  )
}
`
}

/**
 * Generate globals.css with Tailwind
 */
function generateGlobalCSS(): string {
  return `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: #ffffff;
  --foreground: #111827;
}

body {
  color: var(--foreground);
  background: var(--background);
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}
`
}

/**
 * Generate tailwind.config.ts (ESM)
 */
function generateTailwindConfig(): string {
  return `/**
 * Generated by SSOT CodeGen
 * Tailwind configuration using @ssot-ui/tokens
 */

import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/@ssot-ui/**/*.{js,ts,jsx,tsx}'
  ],
  theme: {
    extend: {}
  },
  plugins: []
}

export default config
`
}

/**
 * Generate next.config.mjs (ESM)
 */
function generateNextConfig(): string {
  return `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: ['@ssot-ui/data-table', '@ssot-ui/tokens', '@ssot-ui/shared']
}

export default nextConfig
`
}

/**
 * Generate Next.js tsconfig.json
 */
function generateNextTSConfig(): string {
  return `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`
}

/**
 * Generate UI README
 */
function generateUIReadme(models: ParsedModel[]): string {
  return `# Generated UI - Data Browser

## 🎨 What Was Generated

This project includes a **read-only data browser** admin panel generated by SSOT CodeGen.

### Pages Generated

**Dashboard**: \`/admin\`
- Overview of all models
- Quick navigation

${models.map(model => `**${model.name} Pages**:
- \`/admin/${model.namePlural}\` - List all ${model.nameLower}s (with search, sort, pagination)
- \`/admin/${model.namePlural}/[id]\` - View ${model.nameLower} details`).join('\n\n')}

### Components Used

- **@ssot-ui/data-table**: Production-ready table with sorting, filtering, search
- **@ssot-ui/tokens**: Design tokens (Tailwind + theme)

---

## 🚀 Getting Started

1. **Install dependencies**:
   \`\`\`bash
   ${models.length > 0 ? 'npm install' : '# Already done during setup'}
   \`\`\`

2. **Start dev server**:
   \`\`\`bash
   npm run dev:ui
   \`\`\`

3. **Open admin panel**:
   \`\`\`
   http://localhost:3001/admin
   \`\`\`

---

## ✏️ Customization

### Change Table Columns

Edit \`app/admin/[model]/page.tsx\`:

\`\`\`tsx
<DataTable
  columns={[
    { key: 'id', header: 'ID' },
    { key: 'title', header: 'Title', sortable: true },
    // Add or remove columns
  ]}
/>
\`\`\`

### Add Filters

\`\`\`tsx
<DataTable
  filterable={[
    {
      field: 'published',
      type: 'boolean',
      label: 'Status'
    }
  ]}
/>
\`\`\`

### Custom Cell Renderers

\`\`\`tsx
{
  key: 'title',
  header: 'Title',
  cellRender: (value, row) => (
    <strong>{value.toUpperCase()}</strong>
  )
}
\`\`\`

---

## 📖 Documentation

- **@ssot-ui/data-table**: See node_modules/@ssot-ui/data-table/README.md
- **Tailwind**: https://tailwindcss.com/docs
- **Next.js**: https://nextjs.org/docs

---

## 🔄 Regeneration

Running \`pnpm ssot generate --ui\` will:
- ✅ Update model pages if schema changed
- ⚠️  Prompt before overwriting your customizations
- ✅ Preserve your edits in marked sections

---

**Generated by**: SSOT CodeGen v1.0.0  
**Template**: Data Browser  
**Read-only**: Yes (write features coming in Phase 2)
`
}

/**
 * Format field name to Title Case
 */
function formatFieldLabel(name: string): string {
  return name
    .replace(/([A-Z])/g, ' $1')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, l => l.toUpperCase())
    .trim()
}

/**
 * Generate shared Loading component
 */
function generateLoadingComponent(): string {
  return `/**
 * Generated by SSOT CodeGen
 * Shared loading component
 */

export function Loading() {
  return (
    <div className="p-8">
      <div className="animate-pulse" role="status" aria-label="Loading">
        <div className="h-8 bg-neutral-200 rounded w-1/4 mb-4"></div>
        <div className="h-4 bg-neutral-200 rounded w-1/2 mb-2"></div>
        <div className="h-4 bg-neutral-200 rounded w-1/3"></div>
      </div>
    </div>
  )
}
`
}

/**
 * Generate shared Error component
 */
function generateErrorComponent(): string {
  return `/**
 * Generated by SSOT CodeGen
 * Shared error message component
 */

interface ErrorMessageProps {
  message: string
}

export function ErrorMessage({ message }: ErrorMessageProps) {
  return (
    <div 
      className="bg-red-50 border border-red-200 text-red-800 p-4 rounded-md"
      role="alert"
      aria-live="polite"
    >
      <strong className="font-semibold">Error: </strong>
      {message}
    </div>
  )
}
`
}

/**
 * Get UI dependencies for package.json
 */
export function getUIDependencies(config: ProjectConfig): Record<string, string> {
  if (!config.generateUI) {
    return {}
  }
  
  // Check if we're in development (packages exist locally)
  const isDev = fs.existsSync(path.resolve(__dirname, '../../ui-data-table'))
  
  const deps: Record<string, string> = {
    'next': '^14.1.0',
    'react': '^18.2.0',
    'react-dom': '^18.2.0',
    '@ssot-ui/tokens': isDev ? 'file:../ui-tokens' : '^1.0.0',
    '@ssot-ui/shared': isDev ? 'file:../ui-shared' : '^1.0.0'
  }
  
  // Add template-specific dependencies
  if (config.uiTemplate === 'data-browser' || config.uiTemplate === 'blog') {
    deps['@ssot-ui/data-table'] = isDev ? 'file:../ui-data-table' : '^1.0.0'
  }
  
  return deps
}

/**
 * Get UI dev dependencies
 */
export function getUIDevDependencies(config: ProjectConfig): Record<string, string> {
  if (!config.generateUI) {
    return {}
  }
  
  return {
    '@types/react': '^18.2.0',
    '@types/react-dom': '^18.2.0',
    'autoprefixer': '^10.4.17',
    'postcss': '^8.4.33',
    'tailwindcss': '^3.4.0'
  }
}

/**
 * Get UI scripts for package.json
 */
export function getUIScripts(config: ProjectConfig): Record<string, string> {
  if (!config.generateUI) {
    return {}
  }
  
  return {
    'dev:ui': 'next dev -p 3001',
    'build:ui': 'next build',
    'start:ui': 'next start -p 3001'
  }
}

