/**
 * UI generation for create-ssot-app
 * Generates Next.js pages using @ssot-ui components
 */

import type { ProjectConfig } from './prompts.js'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

export interface ParsedModel {
  name: string
  nameLower: string
  namePlural: string
  fields: Array<{
    name: string
    type: string
    isRelation: boolean
  }>
}

/**
 * Generate UI files based on template selection
 */
export function generateUI(projectPath: string, config: ProjectConfig, models: ParsedModel[]): void {
  if (!config.generateUI || !config.uiTemplate) {
    return
  }
  
  switch (config.uiTemplate) {
    case 'data-browser':
      generateDataBrowser(projectPath, config, models)
      break
    case 'blog':
    case 'ecommerce':
    case 'dashboard':
      // Not implemented yet
      console.log(`\n⚠️  ${config.uiTemplate} template coming soon`)
      break
  }
}

/**
 * Generate Data Browser UI (read-only admin panel)
 */
function generateDataBrowser(projectPath: string, config: ProjectConfig, models: ParsedModel[]): void {
  // Create app directory for Next.js
  const appDir = path.join(projectPath, 'app')
  const adminDir = path.join(appDir, 'admin')
  
  fs.mkdirSync(appDir, { recursive: true })
  fs.mkdirSync(adminDir, { recursive: true })
  
  // Generate root layout
  fs.writeFileSync(
    path.join(appDir, 'layout.tsx'),
    generateRootLayout(config)
  )
  
  // Generate admin layout with navigation
  fs.writeFileSync(
    path.join(adminDir, 'layout.tsx'),
    generateAdminLayout(models)
  )
  
  // Generate admin dashboard (home)
  fs.writeFileSync(
    path.join(adminDir, 'page.tsx'),
    generateDashboard(models)
  )
  
  // Generate a page for each model
  for (const model of models) {
    const modelDir = path.join(adminDir, model.namePlural)
    fs.mkdirSync(modelDir, { recursive: true })
    
    // List page
    fs.writeFileSync(
      path.join(modelDir, 'page.tsx'),
      generateModelListPage(model)
    )
    
    // Detail page
    const detailDir = path.join(modelDir, '[id]')
    fs.mkdirSync(detailDir, { recursive: true })
    fs.writeFileSync(
      path.join(detailDir, 'page.tsx'),
      generateModelDetailPage(model)
    )
  }
  
  // Generate globals.css with Tailwind
  fs.writeFileSync(
    path.join(appDir, 'globals.css'),
    generateGlobalCSS()
  )
  
  // Generate tailwind.config.js
  fs.writeFileSync(
    path.join(projectPath, 'tailwind.config.js'),
    generateTailwindConfig()
  )
  
  // Generate next.config.js
  fs.writeFileSync(
    path.join(projectPath, 'next.config.js'),
    generateNextConfig()
  )
  
  // Generate tsconfig.json for Next.js
  fs.writeFileSync(
    path.join(projectPath, 'tsconfig.json'),
    generateNextTSConfig()
  )
  
  // Generate UI README
  fs.writeFileSync(
    path.join(projectPath, 'UI_README.md'),
    generateUIReadme(models)
  )
}

/**
 * Generate root layout.tsx
 */
function generateRootLayout(config: ProjectConfig): string {
  return `/**
 * Generated by SSOT CodeGen
 * Root layout for Next.js app
 * 
 * ✨ SAFE TO EDIT - Your changes preserved
 */

import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: '${config.projectName} - Admin',
  description: 'Data browser generated by SSOT CodeGen'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`
}

/**
 * Generate admin layout with sidebar navigation
 */
function generateAdminLayout(models: ParsedModel[]): string {
  return `/**
 * Generated by SSOT CodeGen
 * Admin panel layout with navigation
 * 
 * ✨ SAFE TO EDIT - Customize navigation and styling
 */

import Link from 'next/link'

export default function AdminLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex h-screen bg-neutral-50">
      {/* Sidebar */}
      <aside className="w-64 bg-white border-r border-neutral-200">
        <div className="p-6 border-b border-neutral-200">
          <h1 className="text-xl font-bold">Admin Panel</h1>
          <p className="text-sm text-neutral-600">Data Browser</p>
        </div>
        
        <nav className="p-4">
          <Link
            href="/admin"
            className="block px-4 py-2 rounded-md hover:bg-neutral-100 text-neutral-700 hover:text-neutral-900"
          >
            📊 Dashboard
          </Link>
          
          <div className="mt-6">
            <h3 className="px-4 text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-2">
              Models
            </h3>
            ${models.map(model => `
            <Link
              href="/admin/${model.namePlural}"
              className="block px-4 py-2 rounded-md hover:bg-neutral-100 text-neutral-700 hover:text-neutral-900"
            >
              📝 ${model.name}s
            </Link>`).join('')}
          </div>
        </nav>
      </aside>
      
      {/* Main content */}
      <main className="flex-1 overflow-auto">
        {children}
      </main>
    </div>
  )
}
`
}

/**
 * Generate dashboard page
 */
function generateDashboard(models: ParsedModel[]): string {
  return `/**
 * Generated by SSOT CodeGen
 * Admin dashboard
 */

import Link from 'next/link'

export default function DashboardPage() {
  return (
    <div className="p-8">
      <h1 className="text-3xl font-bold mb-2">Dashboard</h1>
      <p className="text-neutral-600 mb-8">
        Browse your data - Generated by SSOT CodeGen
      </p>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        ${models.map(model => `
        <Link
          href="/admin/${model.namePlural}"
          className="block p-6 bg-white rounded-lg border border-neutral-200 hover:border-primary-300 hover:shadow-md transition-all"
        >
          <h2 className="text-xl font-semibold mb-2">📝 ${model.name}s</h2>
          <p className="text-neutral-600 text-sm">
            Browse all ${model.nameLower} records
          </p>
        </Link>`).join('')}
      </div>
      
      <div className="mt-12 p-6 bg-blue-50 border border-blue-200 rounded-lg">
        <h3 className="font-semibold mb-2">🎨 Generated UI</h3>
        <p className="text-sm text-neutral-700">
          This admin panel was auto-generated from your Prisma schema using SSOT CodeGen.
          All pages use the <code className="px-1 py-0.5 bg-white rounded">@ssot-ui/data-table</code> component.
        </p>
        <p className="text-sm text-neutral-600 mt-2">
          See <code>UI_README.md</code> for customization options.
        </p>
      </div>
    </div>
  )
}
`
}

/**
 * Generate list page for a model
 */
function generateModelListPage(model: ParsedModel): string {
  // Determine which fields to show (max 5)
  const displayFields = model.fields
    .filter(f => !f.name.toLowerCase().includes('password') && !f.name.toLowerCase().includes('hash'))
    .slice(0, 5)
  
  return `/**
 * Generated by SSOT CodeGen
 * ${model.name} list page
 * 
 * ✨ SAFE TO EDIT - Customize columns, filters, and behavior
 * 🔄 To regenerate: pnpm ssot generate --ui
 */

'use client'

import { DataTable } from '@ssot-ui/data-table'
import '@ssot-ui/data-table/styles.css'
import { use${model.name}List } from '@/generated/sdk/hooks/react/use-${model.nameLower}'
import Link from 'next/link'

export default function ${model.name}ListPage() {
  return (
    <div className="p-8">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-3xl font-bold">${model.name}s</h1>
          <p className="text-neutral-600">
            Browse all ${model.nameLower} records
          </p>
        </div>
      </div>
      
      <DataTable
        hook={use${model.name}List}
        columns={[${displayFields.map(f => `
          {
            key: '${f.name}',
            header: '${formatFieldLabel(f.name)}',
            sortable: ${!f.isRelation},${f.name === 'id' ? '' : `
            cellRender: (value, row) => (
              <Link 
                href={\`/admin/${model.namePlural}/\${row.id}\`}
                className="text-primary-600 hover:underline"
              >
                {${f.isRelation ? `value?.name || value?.title || '[${f.type}]'` : 'value'}}
              </Link>
            )`}
          }`).join(',')
        }]}
        searchable={${JSON.stringify(displayFields.filter(f => !f.isRelation && f.type === 'String').map(f => f.name))}}
        pagination="pages"
        defaultPageSize={20}
      />
    </div>
  )
}
`
}

/**
 * Generate detail page for a model
 */
function generateModelDetailPage(model: ParsedModel): string {
  const displayFields = model.fields
    .filter(f => !f.name.toLowerCase().includes('password') && !f.name.toLowerCase().includes('hash'))
  
  return `/**
 * Generated by SSOT CodeGen
 * ${model.name} detail page
 * 
 * ✨ SAFE TO EDIT - Customize layout and fields
 */

'use client'

import { use${model.name} } from '@/generated/sdk/hooks/react/use-${model.nameLower}'
import Link from 'next/link'

export default function ${model.name}DetailPage({
  params
}: {
  params: { id: string }
}) {
  const { data: ${model.nameLower}, isLoading, error } = use${model.name}(Number(params.id))
  
  if (isLoading) {
    return (
      <div className="p-8">
        <div className="animate-pulse">
          <div className="h-8 bg-neutral-200 rounded w-1/4 mb-4"></div>
          <div className="h-4 bg-neutral-200 rounded w-1/2"></div>
        </div>
      </div>
    )
  }
  
  if (error || !${model.nameLower}) {
    return (
      <div className="p-8">
        <div className="bg-error-light border border-error text-error-dark p-4 rounded-md">
          {error?.message || '${model.name} not found'}
        </div>
      </div>
    )
  }
  
  return (
    <div className="p-8">
      <div className="mb-6">
        <Link 
          href="/admin/${model.namePlural}"
          className="text-primary-600 hover:underline mb-2 inline-block"
        >
          ← Back to ${model.name}s
        </Link>
        <h1 className="text-3xl font-bold">
          ${model.name} #{${model.nameLower}.id}
        </h1>
      </div>
      
      <div className="bg-white rounded-lg border border-neutral-200 p-6">
        <dl className="grid grid-cols-1 md:grid-cols-2 gap-4">
          ${displayFields.map(f => `
          <div>
            <dt className="text-sm font-medium text-neutral-500">${formatFieldLabel(f.name)}</dt>
            <dd className="mt-1 text-sm text-neutral-900">
              {${f.isRelation 
                ? `${model.nameLower}.${f.name}?.name || ${model.nameLower}.${f.name}?.title || '[${f.type}]'`
                : f.type === 'DateTime'
                  ? `new Date(${model.nameLower}.${f.name}).toLocaleString()`
                  : f.type === 'Boolean'
                    ? `${model.nameLower}.${f.name} ? '✓ Yes' : '○ No'`
                    : `${model.nameLower}.${f.name} || '-'`
              }}
            </dd>
          </div>`).join('')}
        </dl>
      </div>
    </div>
  )
}
`
}

/**
 * Generate globals.css with Tailwind
 */
function generateGlobalCSS(): string {
  return `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: #ffffff;
  --foreground: #111827;
}

body {
  color: var(--foreground);
  background: var(--background);
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}
`
}

/**
 * Generate tailwind.config.js
 */
function generateTailwindConfig(): string {
  return `/**
 * Generated by SSOT CodeGen
 * Tailwind configuration using @ssot-ui/tokens
 */

const tokens = require('@ssot-ui/tokens/tailwind')

module.exports = {
  ...tokens,
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/@ssot-ui/**/*.{js,ts,jsx,tsx}'
  ]
}
`
}

/**
 * Generate next.config.js
 */
function generateNextConfig(): string {
  return `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: ['@ssot-ui/data-table', '@ssot-ui/tokens']
}

module.exports = nextConfig
`
}

/**
 * Generate Next.js tsconfig.json
 */
function generateNextTSConfig(): string {
  return `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`
}

/**
 * Generate UI README
 */
function generateUIReadme(models: ParsedModel[]): string {
  return `# Generated UI - Data Browser

## 🎨 What Was Generated

This project includes a **read-only data browser** admin panel generated by SSOT CodeGen.

### Pages Generated

**Dashboard**: \`/admin\`
- Overview of all models
- Quick navigation

${models.map(model => `**${model.name} Pages**:
- \`/admin/${model.namePlural}\` - List all ${model.nameLower}s (with search, sort, pagination)
- \`/admin/${model.namePlural}/[id]\` - View ${model.nameLower} details`).join('\n\n')}

### Components Used

- **@ssot-ui/data-table**: Production-ready table with sorting, filtering, search
- **@ssot-ui/tokens**: Design tokens (Tailwind + theme)

---

## 🚀 Getting Started

1. **Install dependencies**:
   \`\`\`bash
   ${models.length > 0 ? 'npm install' : '# Already done during setup'}
   \`\`\`

2. **Start dev server**:
   \`\`\`bash
   npm run dev
   \`\`\`

3. **Open admin panel**:
   \`\`\`
   http://localhost:3000/admin
   \`\`\`

---

## ✏️ Customization

### Change Table Columns

Edit \`app/admin/[model]/page.tsx\`:

\`\`\`tsx
<DataTable
  columns={[
    { key: 'id', header: 'ID' },
    { key: 'title', header: 'Title', sortable: true },
    // Add or remove columns
  ]}
/>
\`\`\`

### Add Filters

\`\`\`tsx
<DataTable
  filterable={[
    {
      field: 'published',
      type: 'boolean',
      label: 'Status'
    }
  ]}
/>
\`\`\`

### Custom Cell Renderers

\`\`\`tsx
{
  key: 'title',
  header: 'Title',
  cellRender: (value, row) => (
    <strong>{value.toUpperCase()}</strong>
  )
}
\`\`\`

---

## 📖 Documentation

- **@ssot-ui/data-table**: See node_modules/@ssot-ui/data-table/README.md
- **Tailwind**: https://tailwindcss.com/docs
- **Next.js**: https://nextjs.org/docs

---

## 🔄 Regeneration

Running \`pnpm ssot generate --ui\` will:
- ✅ Update model pages if schema changed
- ⚠️  Prompt before overwriting your customizations
- ✅ Preserve your edits in marked sections

---

**Generated by**: SSOT CodeGen v1.0.0  
**Template**: Data Browser  
**Read-only**: Yes (write features coming in Phase 2)
`
}

/**
 * Format field name to Title Case
 */
function formatFieldLabel(name: string): string {
  return name
    .replace(/([A-Z])/g, ' $1')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, l => l.toUpperCase())
    .trim()
}

/**
 * Get UI dependencies for package.json
 */
export function getUIDependencies(config: ProjectConfig): Record<string, string> {
  if (!config.generateUI) {
    return {}
  }
  
  // Check if we're in development (packages exist locally)
  const isDev = fs.existsSync(path.resolve(__dirname, '../../ui-data-table'))
  
  return {
    'next': '^14.1.0',
    'react': '^18.2.0',
    'react-dom': '^18.2.0',
    '@ssot-ui/data-table': isDev ? 'file:../ui-data-table' : '^1.0.0',
    '@ssot-ui/tokens': isDev ? 'file:../ui-tokens' : '^1.0.0'
  }
}

/**
 * Get UI dev dependencies
 */
export function getUIDevDependencies(config: ProjectConfig): Record<string, string> {
  if (!config.generateUI) {
    return {}
  }
  
  return {
    '@types/react': '^18.2.0',
    '@types/react-dom': '^18.2.0',
    'autoprefixer': '^10.4.17',
    'postcss': '^8.4.33',
    'tailwindcss': '^3.4.0'
  }
}

/**
 * Get UI scripts for package.json
 */
export function getUIScripts(config: ProjectConfig): Record<string, string> {
  if (!config.generateUI) {
    return {}
  }
  
  return {
    'dev:ui': 'next dev -p 3001',
    'build:ui': 'next build',
    'start:ui': 'next start -p 3001'
  }
}

