// @generated
// This file is automatically generated. Do not edit manually.

import type { BlockUpdateInput } from '@/validators/block/block.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see BlockUpdateSchema in validators
 */
export type BlockUpdateDTO = BlockUpdateInput
