// @generated
// This file is automatically generated. Do not edit manually.

import type { BlockReadDTO } from './block.read.dto.js'

type BlockWhereInput = {
    id?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    createdAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    AND?: BlockWhereInput[]
    OR?: BlockWhereInput[]
    NOT?: BlockWhereInput[]
  }

export interface BlockQueryDTO {
  skip?: number  // Offset pagination (should be >= 0)
  take?: number  // Limit (should be > 0)
  cursor?: string  // Cursor for cursor-based pagination
  orderBy?: {
    id?: 'asc' | 'desc'
    blockerId?: 'asc' | 'desc'
    blockedId?: 'asc' | 'desc'
    createdAt?: 'asc' | 'desc'
    blocker?: { [key: string]: 'asc' | 'desc' }
    blocked?: { [key: string]: 'asc' | 'desc' }
  }
  where?: BlockWhereInput
  include?: {
    blocker?: boolean | { include?: any; select?: any }
    blocked?: boolean | { include?: any; select?: any }
  }
  select?: {
    id?: boolean
    blockerId?: boolean
    blockedId?: boolean
    createdAt?: boolean
    blocker?: boolean | { select?: any; include?: any }
    blocked?: boolean | { select?: any; include?: any }
  }
  distinct?: 'id' | 'createdAt' | Array<'id' | 'createdAt'>
}

export interface BlockListResponse {
  data: BlockReadDTO[]
  meta: {
    total: number
    skip: number
    take: number
    hasMore: boolean  // Calculated as: skip + take < total
  }
}
