// @generated
// This file is automatically generated. Do not edit manually.

import type { BlockCreateInput } from '@/validators/block/block.create.zod.js'

/**
 * Create DTO - Derived from Zod schema (single source of truth)
 * @see BlockCreateSchema in validators
 */
export type BlockCreateDTO = BlockCreateInput
