// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { DimensionCategory } from '@prisma/client'

export const PersonalityDimensionCreateSchema = z.object({
  name: z.string().min(1, 'name is required'),
  description: z.string().nullable().optional(),
  category: z.nativeEnum(DimensionCategory),
  isActive: z.boolean().optional().default(true),
  normalizationConfig: z.record(z.any()).nullable().optional(),
  createdAt: z.coerce.date().optional().default(new Date())
})

export type PersonalityDimensionCreateInput = z.infer<typeof PersonalityDimensionCreateSchema>
