// @generated
// This file is automatically generated. Do not edit manually.

import type { BehaviorEventUpdateInput } from '@/validators/behavior-event/behavior-event.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see BehaviorEventUpdateSchema in validators
 */
export type BehaviorEventUpdateDTO = BehaviorEventUpdateInput
