// @generated
// This file is automatically generated. Do not edit manually.

import type { DimensionMappingRuleCreateInput } from '@/validators/dimension-mapping-rule/dimension-mapping-rule.create.zod.js'

/**
 * Create DTO - Derived from Zod schema (single source of truth)
 * @see DimensionMappingRuleCreateSchema in validators
 */
export type DimensionMappingRuleCreateDTO = DimensionMappingRuleCreateInput
