// @generated
// This file is automatically generated. Do not edit manually.

import { TargetType } from '@prisma/client'

import type { DimensionMappingRuleReadDTO } from './dimension-mapping-rule.read.dto.js'

type DimensionMappingRuleWhereInput = {
    id?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    eventType?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    targetType?: TargetType | {
      equals?: TargetType
      in?: TargetType[]
      notIn?: TargetType[]
      not?: TargetType
    }
    metaKey?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    metaValue?: string | null | {
      equals?: string | null
      contains?: string | null
      startsWith?: string | null
      endsWith?: string | null
      in?: string | null[]
      notIn?: string | null[]
      not?: string | null
      mode?: 'default' | 'insensitive'
      isNull?: boolean
    }
    weight?: number | {
      equals?: number
      gt?: number
      gte?: number
      lt?: number
      lte?: number
      in?: number[]
      notIn?: number[]
      not?: number
    }
    isActive?: boolean | {
      equals?: boolean
      not?: boolean
    }
    version?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    matchType?: string | null | {
      equals?: string | null
      contains?: string | null
      startsWith?: string | null
      endsWith?: string | null
      in?: string | null[]
      notIn?: string | null[]
      not?: string | null
      mode?: 'default' | 'insensitive'
      isNull?: boolean
    }
    createdAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    AND?: DimensionMappingRuleWhereInput[]
    OR?: DimensionMappingRuleWhereInput[]
    NOT?: DimensionMappingRuleWhereInput[]
  }

export interface DimensionMappingRuleQueryDTO {
  skip?: number  // Offset pagination (should be >= 0)
  take?: number  // Limit (should be > 0)
  cursor?: string  // Cursor for cursor-based pagination
  orderBy?: {
    id?: 'asc' | 'desc'
    eventType?: 'asc' | 'desc'
    targetType?: 'asc' | 'desc'
    metaKey?: 'asc' | 'desc'
    metaValue?: 'asc' | 'desc'
    dimensionId?: 'asc' | 'desc'
    weight?: 'asc' | 'desc'
    isActive?: 'asc' | 'desc'
    version?: 'asc' | 'desc'
    matchType?: 'asc' | 'desc'
    createdAt?: 'asc' | 'desc'
    updatedAt?: 'asc' | 'desc'
    dimension?: { [key: string]: 'asc' | 'desc' }
  }
  where?: DimensionMappingRuleWhereInput
  include?: {
    dimension?: boolean | { include?: any; select?: any }
  }
  select?: {
    id?: boolean
    eventType?: boolean
    targetType?: boolean
    metaKey?: boolean
    metaValue?: boolean
    dimensionId?: boolean
    weight?: boolean
    isActive?: boolean
    version?: boolean
    matchType?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    dimension?: boolean | { select?: any; include?: any }
  }
  distinct?: 'id' | 'eventType' | 'targetType' | 'metaKey' | 'metaValue' | 'weight' | 'isActive' | 'version' | 'matchType' | 'createdAt' | Array<'id' | 'eventType' | 'targetType' | 'metaKey' | 'metaValue' | 'weight' | 'isActive' | 'version' | 'matchType' | 'createdAt'>
}

export interface DimensionMappingRuleListResponse {
  data: DimensionMappingRuleReadDTO[]
  meta: {
    total: number
    skip: number
    take: number
    hasMore: boolean  // Calculated as: skip + take < total
  }
}
