// @generated
// This file is automatically generated. Do not edit manually.

import { Router, type Router as RouterType } from 'express'
import * as behaviorEventArchiveController from '@/controllers/behavior-event-archive/index.js'

export const behaviorEventArchiveRouter: RouterType = Router()

// List all BehaviorEventArchive records (simple pagination)
behaviorEventArchiveRouter.get('/', behaviorEventArchiveController.listBehaviorEventArchives)

// Search BehaviorEventArchive records (complex filtering via POST body)
behaviorEventArchiveRouter.post('/search', behaviorEventArchiveController.searchBehaviorEventArchives)

// Get BehaviorEventArchive by ID
behaviorEventArchiveRouter.get('/:id', behaviorEventArchiveController.getBehaviorEventArchive)

// Create BehaviorEventArchive
behaviorEventArchiveRouter.post('/', behaviorEventArchiveController.createBehaviorEventArchive)

// Update BehaviorEventArchive
behaviorEventArchiveRouter.put('/:id', behaviorEventArchiveController.updateBehaviorEventArchive)
behaviorEventArchiveRouter.patch('/:id', behaviorEventArchiveController.updateBehaviorEventArchive)

// Delete BehaviorEventArchive
behaviorEventArchiveRouter.delete('/:id', behaviorEventArchiveController.deleteBehaviorEventArchive)

// Count BehaviorEventArchive records
behaviorEventArchiveRouter.get('/meta/count', behaviorEventArchiveController.countBehaviorEventArchives)

// Bulk operations
behaviorEventArchiveRouter.post('/bulk/create', behaviorEventArchiveController.bulkCreateBehaviorEventArchives)
behaviorEventArchiveRouter.put('/bulk/update', behaviorEventArchiveController.bulkUpdateBehaviorEventArchives)
behaviorEventArchiveRouter.delete('/bulk/delete', behaviorEventArchiveController.bulkDeleteBehaviorEventArchives)

