// @generated
// This file is automatically generated. Do not edit manually.

import { Router, type Router as RouterType } from 'express'
import * as userController from '@/controllers/user/index.js'

export const userRouter: RouterType = Router()

// List all User records (simple pagination)
userRouter.get('/', userController.listUsers)

// Search User records (complex filtering via POST body)
userRouter.post('/search', userController.searchUsers)

// Get User by ID
userRouter.get('/:id', userController.getUser)

// Create User
userRouter.post('/', userController.createUser)

// Update User
userRouter.put('/:id', userController.updateUser)
userRouter.patch('/:id', userController.updateUser)

// Delete User
userRouter.delete('/:id', userController.deleteUser)

// Count User records
userRouter.get('/meta/count', userController.countUsers)

// Bulk operations
userRouter.post('/bulk/create', userController.bulkCreateUsers)
userRouter.put('/bulk/update', userController.bulkUpdateUsers)
userRouter.delete('/bulk/delete', userController.bulkDeleteUsers)

