// @generated
// This file is automatically generated. Do not edit manually.

import {
  BaseCRUDController
} from '../../base/index.js'
import { photoService } from '../../services/photo/index.js'
import {
  PhotoCreateSchema,
  PhotoUpdateSchema,
  PhotoQuerySchema
} from '../../validators/photo/index.js'

/**
 * Photo CRUD Controller
 * Using BaseCRUDController to eliminate boilerplate
 */
const photoCRUD = new BaseCRUDController(
  photoService,
  {
    create: PhotoCreateSchema,
    update: PhotoUpdateSchema,
    query: PhotoQuerySchema
  } as any,
  {
    modelName: 'Photo',
    idType: 'string'
  }
)


// Standard CRUD operations
export const listPhotos = photoCRUD.list.bind(photoCRUD)
export const searchPhotos = photoCRUD.search.bind(photoCRUD)
export const getPhoto = photoCRUD.getById.bind(photoCRUD)
export const createPhoto = photoCRUD.create.bind(photoCRUD)
export const updatePhoto = photoCRUD.update.bind(photoCRUD)
export const deletePhoto = photoCRUD.deleteRecord.bind(photoCRUD)
export const countPhotos = photoCRUD.count.bind(photoCRUD)

// Bulk operations
export const bulkCreatePhotos = photoCRUD.bulkCreate.bind(photoCRUD)
export const bulkUpdatePhotos = photoCRUD.bulkUpdate.bind(photoCRUD)
export const bulkDeletePhotos = photoCRUD.bulkDelete.bind(photoCRUD)
