// @generated
// This file is automatically generated. Do not edit manually.

import { Router, type Router as RouterType } from 'express'
import * as profileController from '@/controllers/profile/index.js'

export const profileRouter: RouterType = Router()

// List all Profile records (simple pagination)
profileRouter.get('/', profileController.listProfiles)

// Search Profile records (complex filtering via POST body)
profileRouter.post('/search', profileController.searchProfiles)

// Get Profile by ID
profileRouter.get('/:id', profileController.getProfile)

// Create Profile
profileRouter.post('/', profileController.createProfile)

// Update Profile
profileRouter.put('/:id', profileController.updateProfile)
profileRouter.patch('/:id', profileController.updateProfile)

// Delete Profile
profileRouter.delete('/:id', profileController.deleteProfile)

// Count Profile records
profileRouter.get('/meta/count', profileController.countProfiles)

// Bulk operations
profileRouter.post('/bulk/create', profileController.bulkCreateProfiles)
profileRouter.put('/bulk/update', profileController.bulkUpdateProfiles)
profileRouter.delete('/bulk/delete', profileController.bulkDeleteProfiles)

