// @generated
// This file is automatically generated. Do not edit manually.

import { Router, type Router as RouterType } from 'express'
import * as quizQuestionController from '@/controllers/quiz-question/index.js'

export const quizQuestionRouter: RouterType = Router()

// List all QuizQuestion records (simple pagination)
quizQuestionRouter.get('/', quizQuestionController.listQuizQuestions)

// Search QuizQuestion records (complex filtering via POST body)
quizQuestionRouter.post('/search', quizQuestionController.searchQuizQuestions)

// Get QuizQuestion by ID
quizQuestionRouter.get('/:id', quizQuestionController.getQuizQuestion)

// Create QuizQuestion
quizQuestionRouter.post('/', quizQuestionController.createQuizQuestion)

// Update QuizQuestion
quizQuestionRouter.put('/:id', quizQuestionController.updateQuizQuestion)
quizQuestionRouter.patch('/:id', quizQuestionController.updateQuizQuestion)

// Delete QuizQuestion
quizQuestionRouter.delete('/:id', quizQuestionController.deleteQuizQuestion)

// Count QuizQuestion records
quizQuestionRouter.get('/meta/count', quizQuestionController.countQuizQuestions)

// Bulk operations
quizQuestionRouter.post('/bulk/create', quizQuestionController.bulkCreateQuizQuestions)
quizQuestionRouter.put('/bulk/update', quizQuestionController.bulkUpdateQuizQuestions)
quizQuestionRouter.delete('/bulk/delete', quizQuestionController.bulkDeleteQuizQuestions)

