// @generated
// This file is automatically generated. Do not edit manually.

import prisma from '@/db'
import type { BehaviorEventCreateDTO, BehaviorEventUpdateDTO, BehaviorEventQueryDTO } from '@/contracts/behavior-event'
import type { Prisma } from '@prisma/client'
import { EventType, TargetType } from '@prisma/client'
import { logger } from '@/logger'

export const behaviorEventService = {
  /**
   * List BehaviorEvent records with pagination and relationships
   */
  async list(query: BehaviorEventQueryDTO) {
    const { skip = 0, take = 20, orderBy, where } = query
    
    logger.debug({ skip, take }, 'Listing BehaviorEvent records')
    
    const whereWithSoftDelete = where
    
    const [items, total] = await Promise.all([
      prisma.behaviorEvent.findMany({
        skip,
        take,
        orderBy: orderBy as Prisma.BehaviorEventOrderByWithRelationInput,
        where: whereWithSoftDelete as Prisma.BehaviorEventWhereInput,
      include: {
        user: {
          select: { id: true, email: true }
        }
      }
      }),
      prisma.behaviorEvent.count({
        where: whereWithSoftDelete as Prisma.BehaviorEventWhereInput,
      })
    ])
    
    return {
      data: items,
      meta: {
        total,
        skip,
        take,
        hasMore: skip + take < total
      }
    }
  },
  
  /**
   * Find BehaviorEvent by ID with relationships
   */
  async findById(id: string) {
    return prisma.behaviorEvent.findUnique({
      where: { id },
      include: {
        user: {
          select: { id: true, email: true }
        }
      }
    })
  },
  
  /**
   * Create BehaviorEvent
   */
  async create(data: Prisma.BehaviorEventCreateInput) {
    const item = await prisma.behaviorEvent.create({
      data,
      include: {
        user: {
          select: { id: true, email: true }
        }
      }
    })
    logger.info({ behaviorEventId: item.id }, 'BehaviorEvent created')
    return item
  },
  
  /**
   * Update BehaviorEvent
   */
  async update(id: string, data: BehaviorEventUpdateDTO) {
    const item = await prisma.behaviorEvent.update({
      where: { id },
      data: data as Prisma.BehaviorEventUpdateInput,
      include: {
        user: {
          select: { id: true, email: true }
        }
      }
    })
    logger.info({ behaviorEventId: id }, 'BehaviorEvent updated')
    return item
  },
  
  /**
   * Delete BehaviorEvent
   */
  async delete(id: string) {
    await prisma.behaviorEvent.delete({
      where: { id }
    })
    logger.info({ behaviorEventId: id }, 'BehaviorEvent deleted')
    return true
  },
  
  /**
   * Count BehaviorEvent records
   */
  async count(where?: Prisma.BehaviorEventWhereInput) {
    return prisma.behaviorEvent.count({ where })
  },
  
  /**
   * Check if BehaviorEvent exists
   */
  async exists(id: string) {
    const count = await prisma.behaviorEvent.count({
      where: { id }
    })
    return count > 0
  },
  
  /**
   * Create multiple BehaviorEvent records (bulk operation)
   */
  async createMany(data: Prisma.BehaviorEventCreateManyInput[]) {
    const result = await prisma.behaviorEvent.createMany({
      data,
      skipDuplicates: true
    })
    logger.info({ count: result.count }, 'BehaviorEvent bulk created')
    return result
  },
  
  /**
   * Update multiple BehaviorEvent records (bulk operation)
   */
  async updateMany(where: Prisma.BehaviorEventWhereInput, data: Prisma.BehaviorEventUpdateManyMutationInput) {
    const result = await prisma.behaviorEvent.updateMany({
      where,
      data
    })
    logger.info({ count: result.count }, 'BehaviorEvent bulk updated')
    return result
  },
  
  /**
   * Delete multiple BehaviorEvent records (bulk operation)
   */
  async deleteMany(where: Prisma.BehaviorEventWhereInput) {
    const result = await prisma.behaviorEvent.deleteMany({ where })
    logger.info({ count: result.count }, 'BehaviorEvent bulk deleted')
    return result
  },

  /**
   * Search BehaviorEvents with text query and filters
   * Auto-generated from searchable fields: targetId, ruleVersion
   */
  async search(params: {
    q: string
    eventType?: EventType
    targetType?: TargetType
    targetId?: string
    minProcessedAt?: Date | string
    maxProcessedAt?: Date | string
    ruleVersion?: string
    minCreatedAt?: Date | string
    maxCreatedAt?: Date | string
    skip?: number
    take?: number
  }) {
    const where: Prisma.BehaviorEventWhereInput = {
      AND: [
        params.q ? {
          OR: [
            { targetId: { contains: params.q } },
            { ruleVersion: { contains: params.q } }
          ]
        } : {},
        params.eventType ? { eventType: params.eventType } : {},
        params.targetType ? { targetType: params.targetType } : {},
        params.targetId ? { targetId: params.targetId } : {},
        params.minProcessedAt ? { processedAt: { gte: params.minProcessedAt } } : {},
        params.maxProcessedAt ? { processedAt: { lte: params.maxProcessedAt } } : {},
        params.ruleVersion ? { ruleVersion: params.ruleVersion } : {},
        params.minCreatedAt ? { createdAt: { gte: params.minCreatedAt } } : {},
        params.maxCreatedAt ? { createdAt: { lte: params.maxCreatedAt } } : {}
      ].filter(condition => Object.keys(condition).length > 0)
    }
    
    return prisma.behaviorEvent.findMany({
      where,
      skip: params.skip || 0,
      take: Math.min(params.take || 20, 100)
    })
  },

  /**
   * Get BehaviorEvents by BehaviorEventToUser
   * Auto-generated from foreign key detection: userId
   */
  async getByBehaviorEventToUser(userId: string, options?: {
    skip?: number
    take?: number
  }) {
    return prisma.behaviorEvent.findMany({
      where: { userId },
      skip: options?.skip || 0,
      take: options?.take || 20
    })
  }
}
