// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { EventType } from '@prisma/client'

export const EventWeightConfigQuerySchema = z.object({
  skip: z.coerce.number().min(0).optional(),
  take: z.coerce.number().min(1).max(100).optional().default(20),
  orderBy: z.object({
    id: z.enum(['asc', 'desc']).optional(),
    eventType: z.enum(['asc', 'desc']).optional(),
    baseWeight: z.enum(['asc', 'desc']).optional(),
    isActive: z.enum(['asc', 'desc']).optional(),
    description: z.enum(['asc', 'desc']).optional(),
    createdAt: z.enum(['asc', 'desc']).optional(),
    updatedAt: z.enum(['asc', 'desc']).optional()
  }).optional(),
  where: z.object({
    id: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    eventType: z.nativeEnum(EventType).optional(),
    baseWeight: z.object({
      equals: z.number().optional(),
      gt: z.number().optional(),
      gte: z.number().optional(),
      lt: z.number().optional(),
      lte: z.number().optional()
    }).optional(),
    isActive: z.boolean().optional(),
    description: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional(),
      isNull: z.boolean().optional()
    }).optional(),
    createdAt: z.object({
      equals: z.coerce.date().optional(),
      gt: z.coerce.date().optional(),
      gte: z.coerce.date().optional(),
      lt: z.coerce.date().optional(),
      lte: z.coerce.date().optional()
    }).optional()
  }).optional(),
  include: z.record(z.boolean()).optional(),
  select: z.object({
    id: z.boolean().optional(),
    eventType: z.boolean().optional(),
    baseWeight: z.boolean().optional(),
    isActive: z.boolean().optional(),
    description: z.boolean().optional(),
    createdAt: z.boolean().optional(),
    updatedAt: z.boolean().optional()
  }).optional()
})

export type EventWeightConfigQueryInput = z.infer<typeof EventWeightConfigQuerySchema>
