// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  behavioreventQueries, 
  behavioreventMutations,
  behavioreventInfinite
} from '../../core/queries/behaviorevent-queries'
import type { 
  BehaviorEvent, 
  BehaviorEventCreate, 
  BehaviorEventUpdate, 
  BehaviorEventQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single BehaviorEvent by ID */
export function useBehaviorEvent(
  id: string,
  options?: UseQueryOptions<BehaviorEvent | null, Error>
) {
  return useQuery({ ...behavioreventQueries.all.get(id), ...options })
}

/** List BehaviorEvent records */
export function useBehaviorEvents(
  query?: BehaviorEventQuery,
  options?: UseQueryOptions<ListResponse<BehaviorEvent>, Error>
) {
  return useQuery({ ...behavioreventQueries.all.list(query), ...options })
}

/** Infinite scroll BehaviorEvent records */
export function useInfiniteBehaviorEvents(
  query?: Omit<BehaviorEventQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<BehaviorEvent>, Error>
) {
  return useInfiniteQuery({ ...behavioreventInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create BehaviorEvent mutation */
export function useCreateBehaviorEvent(
  options?: UseMutationOptions<BehaviorEvent, Error, BehaviorEventCreate>
) {
  return useMutation({ ...behavioreventMutations.create(), ...options })
}

/** Update BehaviorEvent mutation */
export function useUpdateBehaviorEvent(
  options?: UseMutationOptions<BehaviorEvent | null, Error, { id: string; data: BehaviorEventUpdate }>
) {
  return useMutation({ ...behavioreventMutations.update(), ...options })
}

/** Delete BehaviorEvent mutation */
export function useDeleteBehaviorEvent(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...behavioreventMutations.delete(), ...options })
}

