// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  quizresultQueries, 
  quizresultMutations,
  quizresultInfinite
} from '../../core/queries/quizresult-queries'
import type { 
  QuizResult, 
  QuizResultCreate, 
  QuizResultUpdate, 
  QuizResultQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single QuizResult by ID */
export function useQuizResult(
  id: string,
  options?: UseQueryOptions<QuizResult | null, Error>
) {
  return useQuery({ ...quizresultQueries.all.get(id), ...options })
}

/** List QuizResult records */
export function useQuizResults(
  query?: QuizResultQuery,
  options?: UseQueryOptions<ListResponse<QuizResult>, Error>
) {
  return useQuery({ ...quizresultQueries.all.list(query), ...options })
}

/** Infinite scroll QuizResult records */
export function useInfiniteQuizResults(
  query?: Omit<QuizResultQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<QuizResult>, Error>
) {
  return useInfiniteQuery({ ...quizresultInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create QuizResult mutation */
export function useCreateQuizResult(
  options?: UseMutationOptions<QuizResult, Error, QuizResultCreate>
) {
  return useMutation({ ...quizresultMutations.create(), ...options })
}

/** Update QuizResult mutation */
export function useUpdateQuizResult(
  options?: UseMutationOptions<QuizResult | null, Error, { id: string; data: QuizResultUpdate }>
) {
  return useMutation({ ...quizresultMutations.update(), ...options })
}

/** Delete QuizResult mutation */
export function useDeleteQuizResult(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...quizresultMutations.delete(), ...options })
}

