// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  dimensionmappingruleQueries, 
  dimensionmappingruleMutations,
  dimensionmappingruleInfinite
} from '../../core/queries/dimensionmappingrule-queries'
import type { 
  DimensionMappingRule, 
  DimensionMappingRuleCreate, 
  DimensionMappingRuleUpdate, 
  DimensionMappingRuleQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single DimensionMappingRule by ID */
export function useDimensionMappingRule(
  id: string,
  options?: UseQueryOptions<DimensionMappingRule | null, Error>
) {
  return useQuery({ ...dimensionmappingruleQueries.all.get(id), ...options })
}

/** List DimensionMappingRule records */
export function useDimensionMappingRules(
  query?: DimensionMappingRuleQuery,
  options?: UseQueryOptions<ListResponse<DimensionMappingRule>, Error>
) {
  return useQuery({ ...dimensionmappingruleQueries.all.list(query), ...options })
}

/** Infinite scroll DimensionMappingRule records */
export function useInfiniteDimensionMappingRules(
  query?: Omit<DimensionMappingRuleQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<DimensionMappingRule>, Error>
) {
  return useInfiniteQuery({ ...dimensionmappingruleInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create DimensionMappingRule mutation */
export function useCreateDimensionMappingRule(
  options?: UseMutationOptions<DimensionMappingRule, Error, DimensionMappingRuleCreate>
) {
  return useMutation({ ...dimensionmappingruleMutations.create(), ...options })
}

/** Update DimensionMappingRule mutation */
export function useUpdateDimensionMappingRule(
  options?: UseMutationOptions<DimensionMappingRule | null, Error, { id: string; data: DimensionMappingRuleUpdate }>
) {
  return useMutation({ ...dimensionmappingruleMutations.update(), ...options })
}

/** Delete DimensionMappingRule mutation */
export function useDeleteDimensionMappingRule(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...dimensionmappingruleMutations.delete(), ...options })
}

