// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  personalitydimensionQueries, 
  personalitydimensionMutations,
  personalitydimensionInfinite
} from '../../core/queries/personalitydimension-queries'
import type { 
  PersonalityDimension, 
  PersonalityDimensionCreate, 
  PersonalityDimensionUpdate, 
  PersonalityDimensionQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single PersonalityDimension by ID */
export function usePersonalityDimension(
  id: string,
  options?: UseQueryOptions<PersonalityDimension | null, Error>
) {
  return useQuery({ ...personalitydimensionQueries.all.get(id), ...options })
}

/** List PersonalityDimension records */
export function usePersonalityDimensions(
  query?: PersonalityDimensionQuery,
  options?: UseQueryOptions<ListResponse<PersonalityDimension>, Error>
) {
  return useQuery({ ...personalitydimensionQueries.all.list(query), ...options })
}

/** Infinite scroll PersonalityDimension records */
export function useInfinitePersonalityDimensions(
  query?: Omit<PersonalityDimensionQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<PersonalityDimension>, Error>
) {
  return useInfiniteQuery({ ...personalitydimensionInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create PersonalityDimension mutation */
export function useCreatePersonalityDimension(
  options?: UseMutationOptions<PersonalityDimension, Error, PersonalityDimensionCreate>
) {
  return useMutation({ ...personalitydimensionMutations.create(), ...options })
}

/** Update PersonalityDimension mutation */
export function useUpdatePersonalityDimension(
  options?: UseMutationOptions<PersonalityDimension | null, Error, { id: string; data: PersonalityDimensionUpdate }>
) {
  return useMutation({ ...personalitydimensionMutations.update(), ...options })
}

/** Delete PersonalityDimension mutation */
export function useDeletePersonalityDimension(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...personalitydimensionMutations.delete(), ...options })
}

