// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  matchQueries, 
  matchMutations,
  matchInfinite
} from '../../core/queries/match-queries'
import type { 
  Match, 
  MatchCreate, 
  MatchUpdate, 
  MatchQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single Match by ID */
export function useMatch(
  id: string,
  options?: UseQueryOptions<Match | null, Error>
) {
  return useQuery({ ...matchQueries.all.get(id), ...options })
}

/** List Match records */
export function useMatchs(
  query?: MatchQuery,
  options?: UseQueryOptions<ListResponse<Match>, Error>
) {
  return useQuery({ ...matchQueries.all.list(query), ...options })
}

/** Infinite scroll Match records */
export function useInfiniteMatchs(
  query?: Omit<MatchQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<Match>, Error>
) {
  return useInfiniteQuery({ ...matchInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create Match mutation */
export function useCreateMatch(
  options?: UseMutationOptions<Match, Error, MatchCreate>
) {
  return useMutation({ ...matchMutations.create(), ...options })
}

/** Update Match mutation */
export function useUpdateMatch(
  options?: UseMutationOptions<Match | null, Error, { id: string; data: MatchUpdate }>
) {
  return useMutation({ ...matchMutations.update(), ...options })
}

/** Delete Match mutation */
export function useDeleteMatch(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...matchMutations.delete(), ...options })
}

