// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  userQueries, 
  userMutations,
  userInfinite
} from '../../core/queries/user-queries'
import type { 
  User, 
  UserCreate, 
  UserUpdate, 
  UserQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single User by ID */
export function useUser(
  id: string,
  options?: UseQueryOptions<User | null, Error>
) {
  return useQuery({ ...userQueries.all.get(id), ...options })
}

/** List User records */
export function useUsers(
  query?: UserQuery,
  options?: UseQueryOptions<ListResponse<User>, Error>
) {
  return useQuery({ ...userQueries.all.list(query), ...options })
}

/** Infinite scroll User records */
export function useInfiniteUsers(
  query?: Omit<UserQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<User>, Error>
) {
  return useInfiniteQuery({ ...userInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create User mutation */
export function useCreateUser(
  options?: UseMutationOptions<User, Error, UserCreate>
) {
  return useMutation({ ...userMutations.create(), ...options })
}

/** Update User mutation */
export function useUpdateUser(
  options?: UseMutationOptions<User | null, Error, { id: string; data: UserUpdate }>
) {
  return useMutation({ ...userMutations.update(), ...options })
}

/** Delete User mutation */
export function useDeleteUser(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...userMutations.delete(), ...options })
}

