// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  eventweightconfigQueries, 
  eventweightconfigMutations,
  eventweightconfigInfinite
} from '../../core/queries/eventweightconfig-queries'
import type { 
  EventWeightConfig, 
  EventWeightConfigCreate, 
  EventWeightConfigUpdate, 
  EventWeightConfigQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single EventWeightConfig by ID */
export function useEventWeightConfig(
  id: string,
  options?: UseQueryOptions<EventWeightConfig | null, Error>
) {
  return useQuery({ ...eventweightconfigQueries.all.get(id), ...options })
}

/** List EventWeightConfig records */
export function useEventWeightConfigs(
  query?: EventWeightConfigQuery,
  options?: UseQueryOptions<ListResponse<EventWeightConfig>, Error>
) {
  return useQuery({ ...eventweightconfigQueries.all.list(query), ...options })
}

/** Infinite scroll EventWeightConfig records */
export function useInfiniteEventWeightConfigs(
  query?: Omit<EventWeightConfigQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<EventWeightConfig>, Error>
) {
  return useInfiniteQuery({ ...eventweightconfigInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create EventWeightConfig mutation */
export function useCreateEventWeightConfig(
  options?: UseMutationOptions<EventWeightConfig, Error, EventWeightConfigCreate>
) {
  return useMutation({ ...eventweightconfigMutations.create(), ...options })
}

/** Update EventWeightConfig mutation */
export function useUpdateEventWeightConfig(
  options?: UseMutationOptions<EventWeightConfig | null, Error, { id: string; data: EventWeightConfigUpdate }>
) {
  return useMutation({ ...eventweightconfigMutations.update(), ...options })
}

/** Delete EventWeightConfig mutation */
export function useDeleteEventWeightConfig(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...eventweightconfigMutations.delete(), ...options })
}

