// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  swipeQueries, 
  swipeMutations,
  swipeInfinite
} from '../../core/queries/swipe-queries'
import type { 
  Swipe, 
  SwipeCreate, 
  SwipeUpdate, 
  SwipeQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single Swipe by ID */
export function useSwipe(
  id: string,
  options?: UseQueryOptions<Swipe | null, Error>
) {
  return useQuery({ ...swipeQueries.all.get(id), ...options })
}

/** List Swipe records */
export function useSwipes(
  query?: SwipeQuery,
  options?: UseQueryOptions<ListResponse<Swipe>, Error>
) {
  return useQuery({ ...swipeQueries.all.list(query), ...options })
}

/** Infinite scroll Swipe records */
export function useInfiniteSwipes(
  query?: Omit<SwipeQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<Swipe>, Error>
) {
  return useInfiniteQuery({ ...swipeInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create Swipe mutation */
export function useCreateSwipe(
  options?: UseMutationOptions<Swipe, Error, SwipeCreate>
) {
  return useMutation({ ...swipeMutations.create(), ...options })
}

/** Update Swipe mutation */
export function useUpdateSwipe(
  options?: UseMutationOptions<Swipe | null, Error, { id: string; data: SwipeUpdate }>
) {
  return useMutation({ ...swipeMutations.update(), ...options })
}

/** Delete Swipe mutation */
export function useDeleteSwipe(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...swipeMutations.delete(), ...options })
}

