// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  userdimensionscoreQueries, 
  userdimensionscoreMutations,
  userdimensionscoreInfinite
} from '../../core/queries/userdimensionscore-queries'
import type { 
  UserDimensionScore, 
  UserDimensionScoreCreate, 
  UserDimensionScoreUpdate, 
  UserDimensionScoreQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single UserDimensionScore by ID */
export function useUserDimensionScore(
  id: string,
  options?: UseQueryOptions<UserDimensionScore | null, Error>
) {
  return useQuery({ ...userdimensionscoreQueries.all.get(id), ...options })
}

/** List UserDimensionScore records */
export function useUserDimensionScores(
  query?: UserDimensionScoreQuery,
  options?: UseQueryOptions<ListResponse<UserDimensionScore>, Error>
) {
  return useQuery({ ...userdimensionscoreQueries.all.list(query), ...options })
}

/** Infinite scroll UserDimensionScore records */
export function useInfiniteUserDimensionScores(
  query?: Omit<UserDimensionScoreQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<UserDimensionScore>, Error>
) {
  return useInfiniteQuery({ ...userdimensionscoreInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create UserDimensionScore mutation */
export function useCreateUserDimensionScore(
  options?: UseMutationOptions<UserDimensionScore, Error, UserDimensionScoreCreate>
) {
  return useMutation({ ...userdimensionscoreMutations.create(), ...options })
}

/** Update UserDimensionScore mutation */
export function useUpdateUserDimensionScore(
  options?: UseMutationOptions<UserDimensionScore | null, Error, { id: string; data: UserDimensionScoreUpdate }>
) {
  return useMutation({ ...userdimensionscoreMutations.update(), ...options })
}

/** Delete UserDimensionScore mutation */
export function useDeleteUserDimensionScore(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...userdimensionscoreMutations.delete(), ...options })
}

