// @generated
// This file is automatically generated. Do not edit manually.

import { useQuery, useMutation, useInfiniteQuery } from '@tanstack/react-query'
import type { 
  UseQueryOptions, 
  UseMutationOptions, 
  UseInfiniteQueryOptions 
} from '@tanstack/react-query'
import { 
  photoQueries, 
  photoMutations,
  photoInfinite
} from '../../core/queries/photo-queries'
import type { 
  Photo, 
  PhotoCreate, 
  PhotoUpdate, 
  PhotoQuery,
  ListResponse 
} from '../../types'

// ============================================
// QUERY HOOKS - Read operations
// ============================================

/** Get single Photo by ID */
export function usePhoto(
  id: string,
  options?: UseQueryOptions<Photo | null, Error>
) {
  return useQuery({ ...photoQueries.all.get(id), ...options })
}

/** List Photo records */
export function usePhotos(
  query?: PhotoQuery,
  options?: UseQueryOptions<ListResponse<Photo>, Error>
) {
  return useQuery({ ...photoQueries.all.list(query), ...options })
}

/** Infinite scroll Photo records */
export function useInfinitePhotos(
  query?: Omit<PhotoQuery, 'skip'>,
  options?: UseInfiniteQueryOptions<ListResponse<Photo>, Error>
) {
  return useInfiniteQuery({ ...photoInfinite.list(query), ...options })
}

// ============================================
// MUTATION HOOKS - Write operations
// ============================================

/** Create Photo mutation */
export function useCreatePhoto(
  options?: UseMutationOptions<Photo, Error, PhotoCreate>
) {
  return useMutation({ ...photoMutations.create(), ...options })
}

/** Update Photo mutation */
export function useUpdatePhoto(
  options?: UseMutationOptions<Photo | null, Error, { id: string; data: PhotoUpdate }>
) {
  return useMutation({ ...photoMutations.update(), ...options })
}

/** Delete Photo mutation */
export function useDeletePhoto(
  options?: UseMutationOptions<boolean, Error, string>
) {
  return useMutation({ ...photoMutations.delete(), ...options })
}

