// @generated
// This file is automatically generated. Do not edit manually.

import prisma from '@/db'
import type { QuizCreateDTO, QuizUpdateDTO, QuizQueryDTO } from '@/contracts/quiz'
import type { Prisma } from '@prisma/client'
import { logger } from '@/logger'

export const quizService = {
  /**
   * List Quiz records with pagination
   */
  async list(query: QuizQueryDTO) {
    const { skip = 0, take = 20, orderBy, where, include, select } = query
    
    logger.debug({ skip, take }, 'Listing Quiz records')
    
    const whereWithSoftDelete = where
    
    const [items, total] = await Promise.all([
      prisma.quiz.findMany({
        skip,
        take,
        ...(orderBy && { orderBy: orderBy as Prisma.QuizOrderByWithRelationInput }),
        ...(whereWithSoftDelete && { where: whereWithSoftDelete as Prisma.QuizWhereInput }),
        ...(include && { include: include as Prisma.QuizInclude }),
        ...(select && { select: select as Prisma.QuizSelect })
      }),
      prisma.quiz.count({
        where: whereWithSoftDelete as Prisma.QuizWhereInput,
      })
    ])
    
    return {
      data: items,
      meta: {
        total,
        skip,
        take,
        hasMore: skip + take < total
      }
    }
  },
  
  /**
   * Find Quiz by ID
   */
  async findById(id: string) {
    return prisma.quiz.findUnique({
      where: { id }
    })
  },
  
  /**
   * Create Quiz
   */
  async create(data: Prisma.QuizCreateInput) {
    const item = await prisma.quiz.create({
      data
    })
    logger.info({ quizId: item.id }, 'Quiz created')
    return item
  },
  
  /**
   * Update Quiz
   */
  async update(id: string, data: QuizUpdateDTO) {
    const item = await prisma.quiz.update({
      where: { id },
      data: data as Prisma.QuizUpdateInput
    })
    logger.info({ quizId: id }, 'Quiz updated')
    return item
  },
  
  /**
   * Delete Quiz
   */
  async delete(id: string) {
    await prisma.quiz.delete({
      where: { id }
    })
    logger.info({ quizId: id }, 'Quiz deleted')
    return true
  },
  
  /**
   * Count Quiz records
   */
  async count(where?: Prisma.QuizWhereInput) {
    return prisma.quiz.count({ where })
  },
  
  /**
   * Check if Quiz exists
   */
  async exists(id: string) {
    const count = await prisma.quiz.count({
      where: { id }
    })
    return count > 0
  },
  
  /**
   * Create multiple Quiz records (bulk operation)
   */
  async createMany(data: Prisma.QuizCreateManyInput[]) {
    const result = await prisma.quiz.createMany({
      data,
      skipDuplicates: true
    })
    logger.info({ count: result.count }, 'Quiz bulk created')
    return result
  },
  
  /**
   * Update multiple Quiz records (bulk operation)
   */
  async updateMany(where: Prisma.QuizWhereInput, data: Prisma.QuizUpdateManyMutationInput) {
    const result = await prisma.quiz.updateMany({
      where,
      data
    })
    logger.info({ count: result.count }, 'Quiz bulk updated')
    return result
  },
  
  /**
   * Delete multiple Quiz records (bulk operation)
   */
  async deleteMany(where: Prisma.QuizWhereInput) {
    const result = await prisma.quiz.deleteMany({ where })
    logger.info({ count: result.count }, 'Quiz bulk deleted')
    return result
  },

  /**
   * Search Quizs with text query and filters
   * Auto-generated from searchable fields: title, description, category
   */
  async search(params: {
    q: string
    title?: string
    description?: string
    category?: string
    minEstimatedTime?: number
    maxEstimatedTime?: number
    minCreatedAt?: Date | string
    maxCreatedAt?: Date | string
    skip?: number
    take?: number
  }) {
    const where: Prisma.QuizWhereInput = {
      AND: [
        params.q ? {
          OR: [
            { title: { contains: params.q } },
            { description: { contains: params.q } },
            { category: { contains: params.q } }
          ]
        } : {},
        params.title ? { title: params.title } : {},
        params.description ? { description: params.description } : {},
        params.category ? { category: params.category } : {},
        params.minEstimatedTime ? { estimatedTime: { gte: params.minEstimatedTime } } : {},
        params.maxEstimatedTime ? { estimatedTime: { lte: params.maxEstimatedTime } } : {},
        params.minCreatedAt ? { createdAt: { gte: params.minCreatedAt } } : {},
        params.maxCreatedAt ? { createdAt: { lte: params.maxCreatedAt } } : {}
      ].filter(condition => Object.keys(condition).length > 0)
    }
    
    return prisma.quiz.findMany({
      where,
      skip: params.skip || 0,
      take: Math.min(params.take || 20, 100)
    })
  }
}
