// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'

export const MessageQuerySchema = z.object({
  skip: z.coerce.number().min(0).optional(),
  take: z.coerce.number().min(1).max(100).optional().default(20),
  orderBy: z.object({
    id: z.enum(['asc', 'desc']).optional(),
    matchId: z.enum(['asc', 'desc']).optional(),
    senderId: z.enum(['asc', 'desc']).optional(),
    receiverId: z.enum(['asc', 'desc']).optional(),
    content: z.enum(['asc', 'desc']).optional(),
    messageType: z.enum(['asc', 'desc']).optional(),
    readAt: z.enum(['asc', 'desc']).optional(),
    createdAt: z.enum(['asc', 'desc']).optional(),
    match: z.record(z.enum(['asc', 'desc'])).optional(),
    sender: z.record(z.enum(['asc', 'desc'])).optional(),
    receiver: z.record(z.enum(['asc', 'desc'])).optional()
  }).optional(),
  where: z.object({
    id: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    matchId: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    senderId: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    receiverId: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    content: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    messageType: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    readAt: z.object({
      equals: z.coerce.date().optional(),
      gt: z.coerce.date().optional(),
      gte: z.coerce.date().optional(),
      lt: z.coerce.date().optional(),
      lte: z.coerce.date().optional(),
      isNull: z.boolean().optional()
    }).optional(),
    createdAt: z.object({
      equals: z.coerce.date().optional(),
      gt: z.coerce.date().optional(),
      gte: z.coerce.date().optional(),
      lt: z.coerce.date().optional(),
      lte: z.coerce.date().optional()
    }).optional()
  }).optional(),
  include: z.object({
    match: z.boolean().optional(),
    sender: z.boolean().optional(),
    receiver: z.boolean().optional()
  }).optional(),
  select: z.object({
    id: z.boolean().optional(),
    matchId: z.boolean().optional(),
    senderId: z.boolean().optional(),
    receiverId: z.boolean().optional(),
    content: z.boolean().optional(),
    messageType: z.boolean().optional(),
    readAt: z.boolean().optional(),
    createdAt: z.boolean().optional(),
    match: z.boolean().optional(),
    sender: z.boolean().optional(),
    receiver: z.boolean().optional()
  }).optional()
})

export type MessageQueryInput = z.infer<typeof MessageQuerySchema>
