// @generated
// This file is automatically generated. Do not edit manually.

import {
  BaseCRUDController
} from '../../base/index.js'
import { compatibilityScoreService } from '../../services/compatibility-score/index.js'
import {
  CompatibilityScoreCreateSchema,
  CompatibilityScoreUpdateSchema,
  CompatibilityScoreQuerySchema
} from '../../validators/compatibility-score/index.js'

/**
 * CompatibilityScore CRUD Controller
 * Using BaseCRUDController to eliminate boilerplate
 */
const compatibilityScoreCRUD = new BaseCRUDController(
  compatibilityScoreService,
  {
    create: CompatibilityScoreCreateSchema,
    update: CompatibilityScoreUpdateSchema,
    query: CompatibilityScoreQuerySchema
  } as any,
  {
    modelName: 'CompatibilityScore',
    idType: 'string'
  }
)


// Standard CRUD operations
export const listCompatibilityScores = compatibilityScoreCRUD.list.bind(compatibilityScoreCRUD)
export const searchCompatibilityScores = compatibilityScoreCRUD.search.bind(compatibilityScoreCRUD)
export const getCompatibilityScore = compatibilityScoreCRUD.getById.bind(compatibilityScoreCRUD)
export const createCompatibilityScore = compatibilityScoreCRUD.create.bind(compatibilityScoreCRUD)
export const updateCompatibilityScore = compatibilityScoreCRUD.update.bind(compatibilityScoreCRUD)
export const deleteCompatibilityScore = compatibilityScoreCRUD.deleteRecord.bind(compatibilityScoreCRUD)
export const countCompatibilityScores = compatibilityScoreCRUD.count.bind(compatibilityScoreCRUD)

// Bulk operations
export const bulkCreateCompatibilityScores = compatibilityScoreCRUD.bulkCreate.bind(compatibilityScoreCRUD)
export const bulkUpdateCompatibilityScores = compatibilityScoreCRUD.bulkUpdate.bind(compatibilityScoreCRUD)
export const bulkDeleteCompatibilityScores = compatibilityScoreCRUD.bulkDelete.bind(compatibilityScoreCRUD)
