// @generated
// This file is automatically generated. Do not edit manually.

import prisma from '@/db'
import type { UserCreateDTO, UserUpdateDTO, UserQueryDTO } from '@/contracts/user'
import type { Prisma } from '@prisma/client'
import { AccountStatus } from '@prisma/client'
import { logger } from '@/logger'

export const userService = {
  /**
   * List User records with pagination and relationships
   */
  async list(query: UserQueryDTO) {
    const { skip = 0, take = 20, orderBy, where } = query
    
    logger.debug({ skip, take }, 'Listing User records')
    
    const whereWithSoftDelete = where
    
    const [items, total] = await Promise.all([
      prisma.user.findMany({
        skip,
        take,
        orderBy: orderBy as Prisma.UserOrderByWithRelationInput,
        where: whereWithSoftDelete as Prisma.UserWhereInput,
      include: {
        profile: {
          select: { id: true, name: true }
        }
      }
      }),
      prisma.user.count({
        where: whereWithSoftDelete as Prisma.UserWhereInput,
      })
    ])
    
    return {
      data: items,
      meta: {
        total,
        skip,
        take,
        hasMore: skip + take < total
      }
    }
  },
  
  /**
   * Find User by ID with relationships
   */
  async findById(id: string) {
    return prisma.user.findUnique({
      where: { id },
      include: {
        profile: {
          select: { id: true, name: true }
        }
      }
    })
  },
  
  /**
   * Create User
   */
  async create(data: Prisma.UserCreateInput) {
    const item = await prisma.user.create({
      data,
      include: {
        profile: {
          select: { id: true, name: true }
        }
      }
    })
    logger.info({ userId: item.id }, 'User created')
    return item
  },
  
  /**
   * Update User
   */
  async update(id: string, data: UserUpdateDTO) {
    const item = await prisma.user.update({
      where: { id },
      data: data as Prisma.UserUpdateInput,
      include: {
        profile: {
          select: { id: true, name: true }
        }
      }
    })
    logger.info({ userId: id }, 'User updated')
    return item
  },
  
  /**
   * Delete User
   */
  async delete(id: string) {
    await prisma.user.delete({
      where: { id }
    })
    logger.info({ userId: id }, 'User deleted')
    return true
  },
  
  /**
   * Count User records
   */
  async count(where?: Prisma.UserWhereInput) {
    return prisma.user.count({ where })
  },
  
  /**
   * Check if User exists
   */
  async exists(id: string) {
    const count = await prisma.user.count({
      where: { id }
    })
    return count > 0
  },
  
  /**
   * Create multiple User records (bulk operation)
   */
  async createMany(data: Prisma.UserCreateManyInput[]) {
    const result = await prisma.user.createMany({
      data,
      skipDuplicates: true
    })
    logger.info({ count: result.count }, 'User bulk created')
    return result
  },
  
  /**
   * Update multiple User records (bulk operation)
   */
  async updateMany(where: Prisma.UserWhereInput, data: Prisma.UserUpdateManyMutationInput) {
    const result = await prisma.user.updateMany({
      where,
      data
    })
    logger.info({ count: result.count }, 'User bulk updated')
    return result
  },
  
  /**
   * Delete multiple User records (bulk operation)
   */
  async deleteMany(where: Prisma.UserWhereInput) {
    const result = await prisma.user.deleteMany({ where })
    logger.info({ count: result.count }, 'User bulk deleted')
    return result
  },

  /**
   * Search Users with text query and filters
   * Auto-generated from searchable fields: email, oauthProvider, oauthId
   */
  async search(params: {
    q: string
    email?: string
    passwordHash?: string
    oauthProvider?: string
    oauthId?: string
    accountStatus?: AccountStatus
    minCreatedAt?: Date | string
    maxCreatedAt?: Date | string
    minLastLoginAt?: Date | string
    maxLastLoginAt?: Date | string
    skip?: number
    take?: number
  }) {
    const where: Prisma.UserWhereInput = {
      AND: [
        params.q ? {
          OR: [
            { email: { contains: params.q } },
            { oauthProvider: { contains: params.q } },
            { oauthId: { contains: params.q } }
          ]
        } : {},
        params.email ? { email: params.email } : {},
        params.passwordHash ? { passwordHash: params.passwordHash } : {},
        params.oauthProvider ? { oauthProvider: params.oauthProvider } : {},
        params.oauthId ? { oauthId: params.oauthId } : {},
        params.accountStatus ? { accountStatus: params.accountStatus } : {},
        params.minCreatedAt ? { createdAt: { gte: params.minCreatedAt } } : {},
        params.maxCreatedAt ? { createdAt: { lte: params.maxCreatedAt } } : {},
        params.minLastLoginAt ? { lastLoginAt: { gte: params.minLastLoginAt } } : {},
        params.maxLastLoginAt ? { lastLoginAt: { lte: params.maxLastLoginAt } } : {}
      ].filter(condition => Object.keys(condition).length > 0)
    }
    
    return prisma.user.findMany({
      where,
      skip: params.skip || 0,
      take: Math.min(params.take || 20, 100)
    })
  }
}
