// @generated
// This file is automatically generated. Do not edit manually.

import { Router, type Router as RouterType } from 'express'
import * as eventWeightConfigController from '@/controllers/event-weight-config/index.js'

export const eventWeightConfigRouter: RouterType = Router()

// List all EventWeightConfig records (simple pagination)
eventWeightConfigRouter.get('/', eventWeightConfigController.listEventWeightConfigs)

// Search EventWeightConfig records (complex filtering via POST body)
eventWeightConfigRouter.post('/search', eventWeightConfigController.searchEventWeightConfigs)

// Get EventWeightConfig by ID
eventWeightConfigRouter.get('/:id', eventWeightConfigController.getEventWeightConfig)

// Create EventWeightConfig
eventWeightConfigRouter.post('/', eventWeightConfigController.createEventWeightConfig)

// Update EventWeightConfig
eventWeightConfigRouter.put('/:id', eventWeightConfigController.updateEventWeightConfig)
eventWeightConfigRouter.patch('/:id', eventWeightConfigController.updateEventWeightConfig)

// Delete EventWeightConfig
eventWeightConfigRouter.delete('/:id', eventWeightConfigController.deleteEventWeightConfig)

// Count EventWeightConfig records
eventWeightConfigRouter.get('/meta/count', eventWeightConfigController.countEventWeightConfigs)

// Bulk operations
eventWeightConfigRouter.post('/bulk/create', eventWeightConfigController.bulkCreateEventWeightConfigs)
eventWeightConfigRouter.put('/bulk/update', eventWeightConfigController.bulkUpdateEventWeightConfigs)
eventWeightConfigRouter.delete('/bulk/delete', eventWeightConfigController.bulkDeleteEventWeightConfigs)

