// @generated
// This file is automatically generated. Do not edit manually.

export interface MatchReadDTO {
  id: string
  user1Id: string
  user2Id: string
  createdAt: Date
  unmatchedAt: Date | null
}
