// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'

export const UserDimensionPriorityQuerySchema = z.object({
  skip: z.coerce.number().min(0).optional(),
  take: z.coerce.number().min(1).max(100).optional().default(20),
  orderBy: z.object({
    id: z.enum(['asc', 'desc']).optional(),
    userId: z.enum(['asc', 'desc']).optional(),
    dimensionId: z.enum(['asc', 'desc']).optional(),
    weight: z.enum(['asc', 'desc']).optional(),
    createdAt: z.enum(['asc', 'desc']).optional(),
    updatedAt: z.enum(['asc', 'desc']).optional(),
    user: z.record(z.enum(['asc', 'desc'])).optional(),
    dimension: z.record(z.enum(['asc', 'desc'])).optional()
  }).optional(),
  where: z.object({
    id: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    userId: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    dimensionId: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    weight: z.object({
      equals: z.number().optional(),
      gt: z.number().optional(),
      gte: z.number().optional(),
      lt: z.number().optional(),
      lte: z.number().optional()
    }).optional(),
    createdAt: z.object({
      equals: z.coerce.date().optional(),
      gt: z.coerce.date().optional(),
      gte: z.coerce.date().optional(),
      lt: z.coerce.date().optional(),
      lte: z.coerce.date().optional()
    }).optional()
  }).optional(),
  include: z.object({
    user: z.boolean().optional(),
    dimension: z.boolean().optional()
  }).optional(),
  select: z.object({
    id: z.boolean().optional(),
    userId: z.boolean().optional(),
    dimensionId: z.boolean().optional(),
    weight: z.boolean().optional(),
    createdAt: z.boolean().optional(),
    updatedAt: z.boolean().optional(),
    user: z.boolean().optional(),
    dimension: z.boolean().optional()
  }).optional()
})

export type UserDimensionPriorityQueryInput = z.infer<typeof UserDimensionPriorityQuerySchema>
