// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { UserDimensionPriorityCreateSchema } from './user-dimension-priority.create.zod.js'

export const UserDimensionPriorityUpdateSchema = UserDimensionPriorityCreateSchema.partial()

export type UserDimensionPriorityUpdateInput = z.infer<typeof UserDimensionPriorityUpdateSchema>
