// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'

export const UserDimensionPriorityCreateSchema = z.object({
  weight: z.number().optional().default(1),
  createdAt: z.coerce.date().optional().default(new Date())
})

export type UserDimensionPriorityCreateInput = z.infer<typeof UserDimensionPriorityCreateSchema>
