// @generated
// This file is automatically generated. Do not edit manually.

import {
  BaseCRUDController
} from '../../base/index.js'
import { quizAnswerService } from '../../services/quiz-answer/index.js'
import {
  QuizAnswerCreateSchema,
  QuizAnswerUpdateSchema,
  QuizAnswerQuerySchema
} from '../../validators/quiz-answer/index.js'

/**
 * QuizAnswer CRUD Controller
 * Using BaseCRUDController to eliminate boilerplate
 */
const quizAnswerCRUD = new BaseCRUDController(
  quizAnswerService,
  {
    create: QuizAnswerCreateSchema,
    update: QuizAnswerUpdateSchema,
    query: QuizAnswerQuerySchema
  } as any,
  {
    modelName: 'QuizAnswer',
    idType: 'string'
  }
)


// Standard CRUD operations
export const listQuizAnswers = quizAnswerCRUD.list.bind(quizAnswerCRUD)
export const searchQuizAnswers = quizAnswerCRUD.search.bind(quizAnswerCRUD)
export const getQuizAnswer = quizAnswerCRUD.getById.bind(quizAnswerCRUD)
export const createQuizAnswer = quizAnswerCRUD.create.bind(quizAnswerCRUD)
export const updateQuizAnswer = quizAnswerCRUD.update.bind(quizAnswerCRUD)
export const deleteQuizAnswer = quizAnswerCRUD.deleteRecord.bind(quizAnswerCRUD)
export const countQuizAnswers = quizAnswerCRUD.count.bind(quizAnswerCRUD)

// Bulk operations
export const bulkCreateQuizAnswers = quizAnswerCRUD.bulkCreate.bind(quizAnswerCRUD)
export const bulkUpdateQuizAnswers = quizAnswerCRUD.bulkUpdate.bind(quizAnswerCRUD)
export const bulkDeleteQuizAnswers = quizAnswerCRUD.bulkDelete.bind(quizAnswerCRUD)
