// @generated
// This file is automatically generated. Do not edit manually.

import {
  BaseCRUDController
} from '../../base/index.js'
import { quizService } from '../../services/quiz/index.js'
import {
  QuizCreateSchema,
  QuizUpdateSchema,
  QuizQuerySchema
} from '../../validators/quiz/index.js'

/**
 * Quiz CRUD Controller
 * Using BaseCRUDController to eliminate boilerplate
 */
const quizCRUD = new BaseCRUDController(
  quizService,
  {
    create: QuizCreateSchema,
    update: QuizUpdateSchema,
    query: QuizQuerySchema
  } as any,
  {
    modelName: 'Quiz',
    idType: 'string'
  }
)


// Standard CRUD operations
export const listQuizs = quizCRUD.list.bind(quizCRUD)
export const searchQuizs = quizCRUD.search.bind(quizCRUD)
export const getQuiz = quizCRUD.getById.bind(quizCRUD)
export const createQuiz = quizCRUD.create.bind(quizCRUD)
export const updateQuiz = quizCRUD.update.bind(quizCRUD)
export const deleteQuiz = quizCRUD.deleteRecord.bind(quizCRUD)
export const countQuizs = quizCRUD.count.bind(quizCRUD)

// Bulk operations
export const bulkCreateQuizs = quizCRUD.bulkCreate.bind(quizCRUD)
export const bulkUpdateQuizs = quizCRUD.bulkUpdate.bind(quizCRUD)
export const bulkDeleteQuizs = quizCRUD.bulkDelete.bind(quizCRUD)
