// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { Gender, BodyType } from '@prisma/client'

export const ProfileQuerySchema = z.object({
  skip: z.coerce.number().min(0).optional(),
  take: z.coerce.number().min(1).max(100).optional().default(20),
  orderBy: z.object({
    id: z.enum(['asc', 'desc']).optional(),
    userId: z.enum(['asc', 'desc']).optional(),
    name: z.enum(['asc', 'desc']).optional(),
    age: z.enum(['asc', 'desc']).optional(),
    gender: z.enum(['asc', 'desc']).optional(),
    bio: z.enum(['asc', 'desc']).optional(),
    location: z.enum(['asc', 'desc']).optional(),
    ethnicity: z.enum(['asc', 'desc']).optional(),
    height: z.enum(['asc', 'desc']).optional(),
    bodyType: z.enum(['asc', 'desc']).optional(),
    eyeColor: z.enum(['asc', 'desc']).optional(),
    hairColor: z.enum(['asc', 'desc']).optional(),
    education: z.enum(['asc', 'desc']).optional(),
    occupation: z.enum(['asc', 'desc']).optional(),
    meta: z.enum(['asc', 'desc']).optional(),
    createdAt: z.enum(['asc', 'desc']).optional(),
    updatedAt: z.enum(['asc', 'desc']).optional(),
    user: z.record(z.enum(['asc', 'desc'])).optional()
  }).optional(),
  where: z.object({
    id: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    userId: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    name: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    age: z.object({
      equals: z.number().optional(),
      gt: z.number().optional(),
      gte: z.number().optional(),
      lt: z.number().optional(),
      lte: z.number().optional()
    }).optional(),
    gender: z.nativeEnum(Gender).optional(),
    bio: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional(),
      isNull: z.boolean().optional()
    }).optional(),
    ethnicity: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional(),
      isNull: z.boolean().optional()
    }).optional(),
    height: z.object({
      equals: z.number().optional(),
      gt: z.number().optional(),
      gte: z.number().optional(),
      lt: z.number().optional(),
      lte: z.number().optional(),
      isNull: z.boolean().optional()
    }).optional(),
    bodyType: z.union([
      z.nativeEnum(BodyType),
      z.object({ isNull: z.boolean() })
    ]).optional(),
    eyeColor: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional(),
      isNull: z.boolean().optional()
    }).optional(),
    hairColor: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional(),
      isNull: z.boolean().optional()
    }).optional(),
    education: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional(),
      isNull: z.boolean().optional()
    }).optional(),
    occupation: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional(),
      isNull: z.boolean().optional()
    }).optional(),
    createdAt: z.object({
      equals: z.coerce.date().optional(),
      gt: z.coerce.date().optional(),
      gte: z.coerce.date().optional(),
      lt: z.coerce.date().optional(),
      lte: z.coerce.date().optional()
    }).optional()
  }).optional(),
  include: z.object({
    user: z.boolean().optional()
  }).optional(),
  select: z.object({
    id: z.boolean().optional(),
    userId: z.boolean().optional(),
    name: z.boolean().optional(),
    age: z.boolean().optional(),
    gender: z.boolean().optional(),
    bio: z.boolean().optional(),
    location: z.boolean().optional(),
    ethnicity: z.boolean().optional(),
    height: z.boolean().optional(),
    bodyType: z.boolean().optional(),
    eyeColor: z.boolean().optional(),
    hairColor: z.boolean().optional(),
    education: z.boolean().optional(),
    occupation: z.boolean().optional(),
    meta: z.boolean().optional(),
    createdAt: z.boolean().optional(),
    updatedAt: z.boolean().optional(),
    user: z.boolean().optional()
  }).optional()
})

export type ProfileQueryInput = z.infer<typeof ProfileQuerySchema>
