// @generated
// This file is automatically generated. Do not edit manually.

import type { QuizReadDTO } from './quiz.read.dto.js'

type QuizWhereInput = {
    id?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    title?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    description?: string | null | {
      equals?: string | null
      contains?: string | null
      startsWith?: string | null
      endsWith?: string | null
      in?: string | null[]
      notIn?: string | null[]
      not?: string | null
      mode?: 'default' | 'insensitive'
      isNull?: boolean
    }
    category?: string | null | {
      equals?: string | null
      contains?: string | null
      startsWith?: string | null
      endsWith?: string | null
      in?: string | null[]
      notIn?: string | null[]
      not?: string | null
      mode?: 'default' | 'insensitive'
      isNull?: boolean
    }
    estimatedTime?: number | null | {
      equals?: number | null
      gt?: number | null
      gte?: number | null
      lt?: number | null
      lte?: number | null
      in?: number | null[]
      notIn?: number | null[]
      not?: number | null
      isNull?: boolean
    }
    meta?: Record<string, any> | null | { isNull?: boolean }
    createdAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    AND?: QuizWhereInput[]
    OR?: QuizWhereInput[]
    NOT?: QuizWhereInput[]
  }

export interface QuizQueryDTO {
  skip?: number  // Offset pagination (should be >= 0)
  take?: number  // Limit (should be > 0)
  cursor?: string  // Cursor for cursor-based pagination
  orderBy?: {
    id?: 'asc' | 'desc'
    title?: 'asc' | 'desc'
    description?: 'asc' | 'desc'
    category?: 'asc' | 'desc'
    estimatedTime?: 'asc' | 'desc'
    meta?: 'asc' | 'desc'
    createdAt?: 'asc' | 'desc'
    updatedAt?: 'asc' | 'desc'
    questions?: { [key: string]: 'asc' | 'desc' }
    answers?: { [key: string]: 'asc' | 'desc' }
    results?: { [key: string]: 'asc' | 'desc' }
  }
  where?: QuizWhereInput
  include?: {
    questions?: boolean | { include?: any; select?: any }
    answers?: boolean | { include?: any; select?: any }
    results?: boolean | { include?: any; select?: any }
  }
  select?: {
    id?: boolean
    title?: boolean
    description?: boolean
    category?: boolean
    estimatedTime?: boolean
    meta?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    questions?: boolean | { select?: any; include?: any }
    answers?: boolean | { select?: any; include?: any }
    results?: boolean | { select?: any; include?: any }
  }
  distinct?: 'id' | 'title' | 'description' | 'category' | 'estimatedTime' | 'meta' | 'createdAt' | Array<'id' | 'title' | 'description' | 'category' | 'estimatedTime' | 'meta' | 'createdAt'>
}

export interface QuizListResponse {
  data: QuizReadDTO[]
  meta: {
    total: number
    skip: number
    take: number
    hasMore: boolean  // Calculated as: skip + take < total
  }
}
