// @generated
// This file is automatically generated. Do not edit manually.

export interface QuizReadDTO {
  id: string
  title: string
  description: string | null
  category: string | null
  estimatedTime: number | null
  meta: Record<string, any> | null
  createdAt: Date
  updatedAt: Date
}
