// @generated
// This file is automatically generated. Do not edit manually.

import type { QuizUpdateInput } from '@/validators/quiz/quiz.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see QuizUpdateSchema in validators
 */
export type QuizUpdateDTO = QuizUpdateInput
