// @generated
// This file is automatically generated. Do not edit manually.

import type { QuizCreateInput } from '@/validators/quiz/quiz.create.zod.js'

/**
 * Create DTO - Derived from Zod schema (single source of truth)
 * @see QuizCreateSchema in validators
 */
export type QuizCreateDTO = QuizCreateInput
