// @generated
// This file is automatically generated. Do not edit manually.

import { EventType, TargetType } from '@prisma/client'

import type { BehaviorEventArchiveReadDTO } from './behavior-event-archive.read.dto.js'

type BehaviorEventArchiveWhereInput = {
    id?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    userId?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    eventType?: EventType | {
      equals?: EventType
      in?: EventType[]
      notIn?: EventType[]
      not?: EventType
    }
    targetType?: TargetType | {
      equals?: TargetType
      in?: TargetType[]
      notIn?: TargetType[]
      not?: TargetType
    }
    targetId?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    meta?: Record<string, any>
    processedAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
      isNull?: boolean
    }
    ruleVersion?: string | null | {
      equals?: string | null
      contains?: string | null
      startsWith?: string | null
      endsWith?: string | null
      in?: string | null[]
      notIn?: string | null[]
      not?: string | null
      mode?: 'default' | 'insensitive'
      isNull?: boolean
    }
    createdAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    archivedAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    AND?: BehaviorEventArchiveWhereInput[]
    OR?: BehaviorEventArchiveWhereInput[]
    NOT?: BehaviorEventArchiveWhereInput[]
  }

export interface BehaviorEventArchiveQueryDTO {
  skip?: number  // Offset pagination (should be >= 0)
  take?: number  // Limit (should be > 0)
  cursor?: string  // Cursor for cursor-based pagination
  orderBy?: {
    id?: 'asc' | 'desc'
    userId?: 'asc' | 'desc'
    eventType?: 'asc' | 'desc'
    targetType?: 'asc' | 'desc'
    targetId?: 'asc' | 'desc'
    meta?: 'asc' | 'desc'
    processedAt?: 'asc' | 'desc'
    ruleVersion?: 'asc' | 'desc'
    createdAt?: 'asc' | 'desc'
    archivedAt?: 'asc' | 'desc'
  }
  where?: BehaviorEventArchiveWhereInput
  include?: Record<string, boolean | { include?: any; select?: any }>
  select?: {
    id?: boolean
    userId?: boolean
    eventType?: boolean
    targetType?: boolean
    targetId?: boolean
    meta?: boolean
    processedAt?: boolean
    ruleVersion?: boolean
    createdAt?: boolean
    archivedAt?: boolean
  }
  distinct?: 'id' | 'userId' | 'eventType' | 'targetType' | 'targetId' | 'meta' | 'processedAt' | 'ruleVersion' | 'createdAt' | 'archivedAt' | Array<'id' | 'userId' | 'eventType' | 'targetType' | 'targetId' | 'meta' | 'processedAt' | 'ruleVersion' | 'createdAt' | 'archivedAt'>
}

export interface BehaviorEventArchiveListResponse {
  data: BehaviorEventArchiveReadDTO[]
  meta: {
    total: number
    skip: number
    take: number
    hasMore: boolean  // Calculated as: skip + take < total
  }
}
