// @generated
// This file is automatically generated. Do not edit manually.

import { EventType } from '@prisma/client'
import { TargetType } from '@prisma/client'

export interface BehaviorEventArchiveReadDTO {
  id: string
  userId: string
  eventType: EventType
  targetType: TargetType
  targetId: string
  meta: Record<string, any>
  processedAt: Date | null
  ruleVersion: string | null
  createdAt: Date
  archivedAt: Date
}
