// @generated
// This file is automatically generated. Do not edit manually.

import type { BehaviorEventArchiveUpdateInput } from '@/validators/behavior-event-archive/behavior-event-archive.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see BehaviorEventArchiveUpdateSchema in validators
 */
export type BehaviorEventArchiveUpdateDTO = BehaviorEventArchiveUpdateInput
