// @generated
// This file is automatically generated. Do not edit manually.

import prisma from '@/db'
import type { QuizAnswerCreateDTO, QuizAnswerUpdateDTO, QuizAnswerQueryDTO } from '@/contracts/quiz-answer'
import type { Prisma } from '@prisma/client'
import { logger } from '@/logger'

export const quizAnswerService = {
  /**
   * List QuizAnswer records with pagination and relationships
   */
  async list(query: QuizAnswerQueryDTO) {
    const { skip = 0, take = 20, orderBy, where } = query
    
    logger.debug({ skip, take }, 'Listing QuizAnswer records')
    
    const whereWithSoftDelete = where
    
    const [items, total] = await Promise.all([
      prisma.quizAnswer.findMany({
        skip,
        take,
        orderBy: orderBy as Prisma.QuizAnswerOrderByWithRelationInput,
        where: whereWithSoftDelete as Prisma.QuizAnswerWhereInput,
      include: {
        quiz: {
          select: { id: true, title: true }
        },
        question: true,
        user: {
          select: { id: true, email: true }
        }
      }
      }),
      prisma.quizAnswer.count({
        where: whereWithSoftDelete as Prisma.QuizAnswerWhereInput,
      })
    ])
    
    return {
      data: items,
      meta: {
        total,
        skip,
        take,
        hasMore: skip + take < total
      }
    }
  },
  
  /**
   * Find QuizAnswer by ID with relationships
   */
  async findById(id: string) {
    return prisma.quizAnswer.findUnique({
      where: { id },
      include: {
        quiz: {
          select: { id: true, title: true }
        },
        question: true,
        user: {
          select: { id: true, email: true }
        }
      }
    })
  },
  
  /**
   * Create QuizAnswer
   */
  async create(data: Prisma.QuizAnswerCreateInput) {
    const item = await prisma.quizAnswer.create({
      data,
      include: {
        quiz: {
          select: { id: true, title: true }
        },
        question: true,
        user: {
          select: { id: true, email: true }
        }
      }
    })
    logger.info({ quizAnswerId: item.id }, 'QuizAnswer created')
    return item
  },
  
  /**
   * Update QuizAnswer
   */
  async update(id: string, data: QuizAnswerUpdateDTO) {
    const item = await prisma.quizAnswer.update({
      where: { id },
      data: data as Prisma.QuizAnswerUpdateInput,
      include: {
        quiz: {
          select: { id: true, title: true }
        },
        question: true,
        user: {
          select: { id: true, email: true }
        }
      }
    })
    logger.info({ quizAnswerId: id }, 'QuizAnswer updated')
    return item
  },
  
  /**
   * Delete QuizAnswer
   */
  async delete(id: string) {
    await prisma.quizAnswer.delete({
      where: { id }
    })
    logger.info({ quizAnswerId: id }, 'QuizAnswer deleted')
    return true
  },
  
  /**
   * Count QuizAnswer records
   */
  async count(where?: Prisma.QuizAnswerWhereInput) {
    return prisma.quizAnswer.count({ where })
  },
  
  /**
   * Check if QuizAnswer exists
   */
  async exists(id: string) {
    const count = await prisma.quizAnswer.count({
      where: { id }
    })
    return count > 0
  },
  
  /**
   * Create multiple QuizAnswer records (bulk operation)
   */
  async createMany(data: Prisma.QuizAnswerCreateManyInput[]) {
    const result = await prisma.quizAnswer.createMany({
      data,
      skipDuplicates: true
    })
    logger.info({ count: result.count }, 'QuizAnswer bulk created')
    return result
  },
  
  /**
   * Update multiple QuizAnswer records (bulk operation)
   */
  async updateMany(where: Prisma.QuizAnswerWhereInput, data: Prisma.QuizAnswerUpdateManyMutationInput) {
    const result = await prisma.quizAnswer.updateMany({
      where,
      data
    })
    logger.info({ count: result.count }, 'QuizAnswer bulk updated')
    return result
  },
  
  /**
   * Delete multiple QuizAnswer records (bulk operation)
   */
  async deleteMany(where: Prisma.QuizAnswerWhereInput) {
    const result = await prisma.quizAnswer.deleteMany({ where })
    logger.info({ count: result.count }, 'QuizAnswer bulk deleted')
    return result
  },

  /**
   * Get QuizAnswers by QuizToQuizAnswer
   * Auto-generated from foreign key detection: quizId
   */
  async getByQuizToQuizAnswer(quizId: string, options?: {
    skip?: number
    take?: number
  }) {
    return prisma.quizAnswer.findMany({
      where: { quizId },
      skip: options?.skip || 0,
      take: options?.take || 20
    })
  },

  /**
   * Get QuizAnswers by QuizAnswerToQuizQuestion
   * Auto-generated from foreign key detection: questionId
   */
  async getByQuizAnswerToQuizQuestion(questionId: string, options?: {
    skip?: number
    take?: number
  }) {
    return prisma.quizAnswer.findMany({
      where: { questionId },
      skip: options?.skip || 0,
      take: options?.take || 20
    })
  },

  /**
   * Get QuizAnswers by QuizAnswerToUser
   * Auto-generated from foreign key detection: userId
   */
  async getByQuizAnswerToUser(userId: string, options?: {
    skip?: number
    take?: number
  }) {
    return prisma.quizAnswer.findMany({
      where: { userId },
      skip: options?.skip || 0,
      take: options?.take || 20
    })
  }
}
