// @generated
// This file is automatically generated. Do not edit manually.

import prisma from '@/db'
import type { CompatibilityScoreCreateDTO, CompatibilityScoreUpdateDTO, CompatibilityScoreQueryDTO } from '@/contracts/compatibility-score'
import type { Prisma } from '@prisma/client'
import { logger } from '@/logger'

export const compatibilityScoreService = {
  /**
   * List CompatibilityScore records with pagination and relationships
   */
  async list(query: CompatibilityScoreQueryDTO) {
    const { skip = 0, take = 20, orderBy, where } = query
    
    logger.debug({ skip, take }, 'Listing CompatibilityScore records')
    
    const whereWithSoftDelete = where
    
    const [items, total] = await Promise.all([
      prisma.compatibilityScore.findMany({
        skip,
        take,
        orderBy: orderBy as Prisma.CompatibilityScoreOrderByWithRelationInput,
        where: whereWithSoftDelete as Prisma.CompatibilityScoreWhereInput,
      include: {
        user1: {
          select: { id: true, email: true }
        },
        user2: {
          select: { id: true, email: true }
        }
      }
      }),
      prisma.compatibilityScore.count({
        where: whereWithSoftDelete as Prisma.CompatibilityScoreWhereInput,
      })
    ])
    
    return {
      data: items,
      meta: {
        total,
        skip,
        take,
        hasMore: skip + take < total
      }
    }
  },
  
  /**
   * Find CompatibilityScore by ID with relationships
   */
  async findById(id: string) {
    return prisma.compatibilityScore.findUnique({
      where: { id },
      include: {
        user1: {
          select: { id: true, email: true }
        },
        user2: {
          select: { id: true, email: true }
        }
      }
    })
  },
  
  /**
   * Create CompatibilityScore
   */
  async create(data: Prisma.CompatibilityScoreCreateInput) {
    const item = await prisma.compatibilityScore.create({
      data,
      include: {
        user1: {
          select: { id: true, email: true }
        },
        user2: {
          select: { id: true, email: true }
        }
      }
    })
    logger.info({ compatibilityScoreId: item.id }, 'CompatibilityScore created')
    return item
  },
  
  /**
   * Update CompatibilityScore
   */
  async update(id: string, data: CompatibilityScoreUpdateDTO) {
    const item = await prisma.compatibilityScore.update({
      where: { id },
      data: data as Prisma.CompatibilityScoreUpdateInput,
      include: {
        user1: {
          select: { id: true, email: true }
        },
        user2: {
          select: { id: true, email: true }
        }
      }
    })
    logger.info({ compatibilityScoreId: id }, 'CompatibilityScore updated')
    return item
  },
  
  /**
   * Delete CompatibilityScore
   */
  async delete(id: string) {
    await prisma.compatibilityScore.delete({
      where: { id }
    })
    logger.info({ compatibilityScoreId: id }, 'CompatibilityScore deleted')
    return true
  },
  
  /**
   * Count CompatibilityScore records
   */
  async count(where?: Prisma.CompatibilityScoreWhereInput) {
    return prisma.compatibilityScore.count({ where })
  },
  
  /**
   * Check if CompatibilityScore exists
   */
  async exists(id: string) {
    const count = await prisma.compatibilityScore.count({
      where: { id }
    })
    return count > 0
  },
  
  /**
   * Create multiple CompatibilityScore records (bulk operation)
   */
  async createMany(data: Prisma.CompatibilityScoreCreateManyInput[]) {
    const result = await prisma.compatibilityScore.createMany({
      data,
      skipDuplicates: true
    })
    logger.info({ count: result.count }, 'CompatibilityScore bulk created')
    return result
  },
  
  /**
   * Update multiple CompatibilityScore records (bulk operation)
   */
  async updateMany(where: Prisma.CompatibilityScoreWhereInput, data: Prisma.CompatibilityScoreUpdateManyMutationInput) {
    const result = await prisma.compatibilityScore.updateMany({
      where,
      data
    })
    logger.info({ count: result.count }, 'CompatibilityScore bulk updated')
    return result
  },
  
  /**
   * Delete multiple CompatibilityScore records (bulk operation)
   */
  async deleteMany(where: Prisma.CompatibilityScoreWhereInput) {
    const result = await prisma.compatibilityScore.deleteMany({ where })
    logger.info({ count: result.count }, 'CompatibilityScore bulk deleted')
    return result
  },

  /**
   * Search CompatibilityScores with text query and filters
   * Auto-generated from searchable fields: cacheVersion
   */
  async search(params: {
    q: string
    minOverallScore?: number
    maxOverallScore?: number
    minCalculatedAt?: Date | string
    maxCalculatedAt?: Date | string
    cacheVersion?: string
    skip?: number
    take?: number
  }) {
    const where: Prisma.CompatibilityScoreWhereInput = {
      AND: [
        params.q ? {
          OR: [
            { cacheVersion: { contains: params.q } }
          ]
        } : {},
        params.minOverallScore ? { overallScore: { gte: params.minOverallScore } } : {},
        params.maxOverallScore ? { overallScore: { lte: params.maxOverallScore } } : {},
        params.minCalculatedAt ? { calculatedAt: { gte: params.minCalculatedAt } } : {},
        params.maxCalculatedAt ? { calculatedAt: { lte: params.maxCalculatedAt } } : {},
        params.cacheVersion ? { cacheVersion: params.cacheVersion } : {}
      ].filter(condition => Object.keys(condition).length > 0)
    }
    
    return prisma.compatibilityScore.findMany({
      where,
      skip: params.skip || 0,
      take: Math.min(params.take || 20, 100)
    })
  },

  /**
   * Get CompatibilityScores by User1Compat
   * Auto-generated from foreign key detection: user1Id
   */
  async getByUser1Compat(user1Id: string, options?: {
    skip?: number
    take?: number
  }) {
    return prisma.compatibilityScore.findMany({
      where: { user1Id },
      skip: options?.skip || 0,
      take: options?.take || 20
    })
  },

  /**
   * Get CompatibilityScores by User2Compat
   * Auto-generated from foreign key detection: user2Id
   */
  async getByUser2Compat(user2Id: string, options?: {
    skip?: number
    take?: number
  }) {
    return prisma.compatibilityScore.findMany({
      where: { user2Id },
      skip: options?.skip || 0,
      take: options?.take || 20
    })
  }
}
