// @generated
// This file is automatically generated. Do not edit manually.

import {
  BaseCRUDController
} from '../../base/index.js'
import { personalityDimensionService } from '../../services/personality-dimension/index.js'
import {
  PersonalityDimensionCreateSchema,
  PersonalityDimensionUpdateSchema,
  PersonalityDimensionQuerySchema
} from '../../validators/personality-dimension/index.js'

/**
 * PersonalityDimension CRUD Controller
 * Using BaseCRUDController to eliminate boilerplate
 */
const personalityDimensionCRUD = new BaseCRUDController(
  personalityDimensionService,
  {
    create: PersonalityDimensionCreateSchema,
    update: PersonalityDimensionUpdateSchema,
    query: PersonalityDimensionQuerySchema
  } as any,
  {
    modelName: 'PersonalityDimension',
    idType: 'string'
  }
)


// Standard CRUD operations
export const listPersonalityDimensions = personalityDimensionCRUD.list.bind(personalityDimensionCRUD)
export const searchPersonalityDimensions = personalityDimensionCRUD.search.bind(personalityDimensionCRUD)
export const getPersonalityDimension = personalityDimensionCRUD.getById.bind(personalityDimensionCRUD)
export const createPersonalityDimension = personalityDimensionCRUD.create.bind(personalityDimensionCRUD)
export const updatePersonalityDimension = personalityDimensionCRUD.update.bind(personalityDimensionCRUD)
export const deletePersonalityDimension = personalityDimensionCRUD.deleteRecord.bind(personalityDimensionCRUD)
export const countPersonalityDimensions = personalityDimensionCRUD.count.bind(personalityDimensionCRUD)

// Bulk operations
export const bulkCreatePersonalityDimensions = personalityDimensionCRUD.bulkCreate.bind(personalityDimensionCRUD)
export const bulkUpdatePersonalityDimensions = personalityDimensionCRUD.bulkUpdate.bind(personalityDimensionCRUD)
export const bulkDeletePersonalityDimensions = personalityDimensionCRUD.bulkDelete.bind(personalityDimensionCRUD)
