// @generated
// This file is automatically generated. Do not edit manually.

import {
  BaseCRUDController
} from '../../base/index.js'
import { profileService } from '../../services/profile/index.js'
import {
  ProfileCreateSchema,
  ProfileUpdateSchema,
  ProfileQuerySchema
} from '../../validators/profile/index.js'

/**
 * Profile CRUD Controller
 * Using BaseCRUDController to eliminate boilerplate
 */
const profileCRUD = new BaseCRUDController(
  profileService,
  {
    create: ProfileCreateSchema,
    update: ProfileUpdateSchema,
    query: ProfileQuerySchema
  } as any,
  {
    modelName: 'Profile',
    idType: 'string'
  }
)


// Standard CRUD operations
export const listProfiles = profileCRUD.list.bind(profileCRUD)
export const searchProfiles = profileCRUD.search.bind(profileCRUD)
export const getProfile = profileCRUD.getById.bind(profileCRUD)
export const createProfile = profileCRUD.create.bind(profileCRUD)
export const updateProfile = profileCRUD.update.bind(profileCRUD)
export const deleteProfile = profileCRUD.deleteRecord.bind(profileCRUD)
export const countProfiles = profileCRUD.count.bind(profileCRUD)

// Bulk operations
export const bulkCreateProfiles = profileCRUD.bulkCreate.bind(profileCRUD)
export const bulkUpdateProfiles = profileCRUD.bulkUpdate.bind(profileCRUD)
export const bulkDeleteProfiles = profileCRUD.bulkDelete.bind(profileCRUD)
