// @generated
// This file is automatically generated. Do not edit manually.

import { Router, type Router as RouterType } from 'express'
import * as quizAnswerController from '@/controllers/quiz-answer/index.js'

export const quizAnswerRouter: RouterType = Router()

// List all QuizAnswer records (simple pagination)
quizAnswerRouter.get('/', quizAnswerController.listQuizAnswers)

// Search QuizAnswer records (complex filtering via POST body)
quizAnswerRouter.post('/search', quizAnswerController.searchQuizAnswers)

// Get QuizAnswer by ID
quizAnswerRouter.get('/:id', quizAnswerController.getQuizAnswer)

// Create QuizAnswer
quizAnswerRouter.post('/', quizAnswerController.createQuizAnswer)

// Update QuizAnswer
quizAnswerRouter.put('/:id', quizAnswerController.updateQuizAnswer)
quizAnswerRouter.patch('/:id', quizAnswerController.updateQuizAnswer)

// Delete QuizAnswer
quizAnswerRouter.delete('/:id', quizAnswerController.deleteQuizAnswer)

// Count QuizAnswer records
quizAnswerRouter.get('/meta/count', quizAnswerController.countQuizAnswers)

// Bulk operations
quizAnswerRouter.post('/bulk/create', quizAnswerController.bulkCreateQuizAnswers)
quizAnswerRouter.put('/bulk/update', quizAnswerController.bulkUpdateQuizAnswers)
quizAnswerRouter.delete('/bulk/delete', quizAnswerController.bulkDeleteQuizAnswers)

