// @generated
// This file is automatically generated. Do not edit manually.

import { Gender, BodyType } from '@prisma/client'

import type { ProfileReadDTO } from './profile.read.dto.js'

type ProfileWhereInput = {
    id?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    name?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    age?: number | {
      equals?: number
      gt?: number
      gte?: number
      lt?: number
      lte?: number
      in?: number[]
      notIn?: number[]
      not?: number
    }
    gender?: Gender | {
      equals?: Gender
      in?: Gender[]
      notIn?: Gender[]
      not?: Gender
    }
    bio?: string | null | {
      equals?: string | null
      contains?: string | null
      startsWith?: string | null
      endsWith?: string | null
      in?: string | null[]
      notIn?: string | null[]
      not?: string | null
      mode?: 'default' | 'insensitive'
      isNull?: boolean
    }
    location?: Record<string, any>
    ethnicity?: string | null | {
      equals?: string | null
      contains?: string | null
      startsWith?: string | null
      endsWith?: string | null
      in?: string | null[]
      notIn?: string | null[]
      not?: string | null
      mode?: 'default' | 'insensitive'
      isNull?: boolean
    }
    height?: number | null | {
      equals?: number | null
      gt?: number | null
      gte?: number | null
      lt?: number | null
      lte?: number | null
      in?: number | null[]
      notIn?: number | null[]
      not?: number | null
      isNull?: boolean
    }
    bodyType?: BodyType | null | {
      equals?: BodyType | null
      in?: BodyType | null[]
      notIn?: BodyType | null[]
      not?: BodyType | null
      isNull?: boolean
    }
    eyeColor?: string | null | {
      equals?: string | null
      contains?: string | null
      startsWith?: string | null
      endsWith?: string | null
      in?: string | null[]
      notIn?: string | null[]
      not?: string | null
      mode?: 'default' | 'insensitive'
      isNull?: boolean
    }
    hairColor?: string | null | {
      equals?: string | null
      contains?: string | null
      startsWith?: string | null
      endsWith?: string | null
      in?: string | null[]
      notIn?: string | null[]
      not?: string | null
      mode?: 'default' | 'insensitive'
      isNull?: boolean
    }
    education?: string | null | {
      equals?: string | null
      contains?: string | null
      startsWith?: string | null
      endsWith?: string | null
      in?: string | null[]
      notIn?: string | null[]
      not?: string | null
      mode?: 'default' | 'insensitive'
      isNull?: boolean
    }
    occupation?: string | null | {
      equals?: string | null
      contains?: string | null
      startsWith?: string | null
      endsWith?: string | null
      in?: string | null[]
      notIn?: string | null[]
      not?: string | null
      mode?: 'default' | 'insensitive'
      isNull?: boolean
    }
    meta?: Record<string, any> | null | { isNull?: boolean }
    createdAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    AND?: ProfileWhereInput[]
    OR?: ProfileWhereInput[]
    NOT?: ProfileWhereInput[]
  }

export interface ProfileQueryDTO {
  skip?: number  // Offset pagination (should be >= 0)
  take?: number  // Limit (should be > 0)
  cursor?: string  // Cursor for cursor-based pagination
  orderBy?: {
    id?: 'asc' | 'desc'
    userId?: 'asc' | 'desc'
    name?: 'asc' | 'desc'
    age?: 'asc' | 'desc'
    gender?: 'asc' | 'desc'
    bio?: 'asc' | 'desc'
    location?: 'asc' | 'desc'
    ethnicity?: 'asc' | 'desc'
    height?: 'asc' | 'desc'
    bodyType?: 'asc' | 'desc'
    eyeColor?: 'asc' | 'desc'
    hairColor?: 'asc' | 'desc'
    education?: 'asc' | 'desc'
    occupation?: 'asc' | 'desc'
    meta?: 'asc' | 'desc'
    createdAt?: 'asc' | 'desc'
    updatedAt?: 'asc' | 'desc'
    user?: { [key: string]: 'asc' | 'desc' }
  }
  where?: ProfileWhereInput
  include?: {
    user?: boolean | { include?: any; select?: any }
  }
  select?: {
    id?: boolean
    userId?: boolean
    name?: boolean
    age?: boolean
    gender?: boolean
    bio?: boolean
    location?: boolean
    ethnicity?: boolean
    height?: boolean
    bodyType?: boolean
    eyeColor?: boolean
    hairColor?: boolean
    education?: boolean
    occupation?: boolean
    meta?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    user?: boolean | { select?: any; include?: any }
  }
  distinct?: 'id' | 'name' | 'age' | 'gender' | 'bio' | 'location' | 'ethnicity' | 'height' | 'bodyType' | 'eyeColor' | 'hairColor' | 'education' | 'occupation' | 'meta' | 'createdAt' | Array<'id' | 'name' | 'age' | 'gender' | 'bio' | 'location' | 'ethnicity' | 'height' | 'bodyType' | 'eyeColor' | 'hairColor' | 'education' | 'occupation' | 'meta' | 'createdAt'>
}

export interface ProfileListResponse {
  data: ProfileReadDTO[]
  meta: {
    total: number
    skip: number
    take: number
    hasMore: boolean  // Calculated as: skip + take < total
  }
}
