// @generated
// This file is automatically generated. Do not edit manually.

import type { ProfileUpdateInput } from '@/validators/profile/profile.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see ProfileUpdateSchema in validators
 */
export type ProfileUpdateDTO = ProfileUpdateInput
