// @generated
// This file is automatically generated. Do not edit manually.

import { Gender } from '@prisma/client'
import { BodyType } from '@prisma/client'

export interface ProfileReadDTO {
  id: string
  userId: string
  name: string
  age: number
  gender: Gender
  bio: string | null
  location: Record<string, any>
  ethnicity: string | null
  height: number | null
  bodyType: BodyType | null
  eyeColor: string | null
  hairColor: string | null
  education: string | null
  occupation: string | null
  meta: Record<string, any> | null
  createdAt: Date
  updatedAt: Date
}
