// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { EventType, TargetType } from '@prisma/client'

export const BehaviorEventCreateSchema = z.object({
  eventType: z.nativeEnum(EventType),
  targetType: z.nativeEnum(TargetType),
  targetId: z.string().min(1, 'targetId is required'),
  meta: z.record(z.string(), z.unknown()).optional().default({}),
  processedAt: z.coerce.date().nullable().optional(),
  ruleVersion: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional().default(new Date())
})

export type BehaviorEventCreateInput = z.infer<typeof BehaviorEventCreateSchema>
