/**
 * CLI Helper Functions
 * 
 * Extracted utilities for better testability and maintainability
 */

import { resolve, isAbsolute, extname, normalize } from 'path'
import { existsSync, readdirSync, statSync, writeFileSync, readFileSync } from 'fs'
import { execSync } from 'child_process'
import chalk from 'chalk'

export interface SchemaResolutionResult {
  schemaPath: string
  isExample: boolean
  exampleName?: string
}

/**
 * Resolve schema argument to absolute path
 * 
 * Handles three cases:
 * 1. File paths (absolute, relative, or with .prisma extension)
 * 2. Example names (no path separators, no extension)
 * 3. Invalid paths (provides helpful error messages)
 * 
 * @throws Error if schema not found
 */
export function resolveSchemaArg(schemaArg: string | undefined): SchemaResolutionResult {
  if (!schemaArg) {
    console.error(chalk.red('❌ Error: Schema path or example name required'))
    console.log(chalk.gray('\nExamples:'))
    console.log(chalk.gray('  ssot generate minimal'))
    console.log(chalk.gray('  ssot generate examples/blog/schema.prisma'))
    console.log(chalk.gray('  ssot generate ./my-schema.prisma'))
    process.exit(1)
  }
  
  const normalizedArg = normalize(schemaArg)
  
  // Check if it's a file path (absolute, relative, or has .prisma extension)
  const looksLikeFilePath = isAbsolute(normalizedArg) || 
                            normalizedArg.startsWith('.') ||
                            extname(normalizedArg) === '.prisma'
  
  if (looksLikeFilePath) {
    // It's a file path - resolve and validate
    const schemaPath = resolve(process.cwd(), normalizedArg)
    
    if (!existsSync(schemaPath)) {
      console.error(chalk.red(`❌ Schema file not found: ${schemaPath}`))
      process.exit(1)
    }
    
    if (extname(schemaPath) !== '.prisma') {
      console.error(chalk.red(`❌ Schema file must have .prisma extension: ${schemaPath}`))
      process.exit(1)
    }
    
    return { schemaPath, isExample: false }
  }
  
  // Assume it's an example name
  const examplePath = resolve(process.cwd(), 'examples', normalizedArg, 'schema.prisma')
  if (existsSync(examplePath)) {
    return { schemaPath: examplePath, isExample: true, exampleName: normalizedArg }
  }
  
  // Try with prisma/ subdirectory
  const prismaPath = resolve(process.cwd(), 'examples', normalizedArg, 'prisma', 'schema.prisma')
  if (existsSync(prismaPath)) {
    return { schemaPath: prismaPath, isExample: true, exampleName: normalizedArg }
  }
  
  // Not found - show helpful error
  console.error(chalk.red(`❌ Example not found: ${normalizedArg}`))
  console.log(chalk.gray(`   Tried: ${examplePath}`))
  console.log(chalk.gray(`   Tried: ${prismaPath}`))
  console.log(chalk.gray('\nAvailable examples:'))
  
  // List available examples
  const examplesDir = resolve(process.cwd(), 'examples')
  if (existsSync(examplesDir)) {
    const examples = readdirSync(examplesDir)
      .filter(f => statSync(resolve(examplesDir, f)).isDirectory())
      .filter(f => 
        existsSync(resolve(examplesDir, f, 'schema.prisma')) ||
        existsSync(resolve(examplesDir, f, 'prisma', 'schema.prisma'))
      )
    
    if (examples.length > 0) {
      examples.forEach(ex => console.log(chalk.gray(`  • ${ex}`)))
    }
  }
  
  process.exit(1)
}

export interface PostGenOptions {
  outputDir: string
  schemaPath: string
  runTests: boolean
}

/**
 * Post-generation project setup
 * 
 * Handles:
 * 1. Create .env file with test-ready values
 * 2. Install dependencies
 * 3. Generate Prisma client
 * 4. Run validation tests (optional)
 */
export async function runPostGenSetup(options: PostGenOptions): Promise<void> {
  const { outputDir, schemaPath, runTests } = options
  
  console.log(chalk.blue('\n🔧 Setting up project...\n'))
  
  try {
    // 1. Create .env file with test-ready values
    const envPath = resolve(outputDir, '.env')
    if (!existsSync(envPath)) {
      console.log(chalk.gray('  📝 Creating .env file...'))
      
      // Read schema to detect database provider
      const schemaContent = readFileSync(schemaPath, 'utf-8')
      const providerMatch = schemaContent.match(/provider\s*=\s*"(\w+)"/)
      const provider = providerMatch ? providerMatch[1] : 'postgresql'
      
      // Generate appropriate DATABASE_URL
      let databaseUrl = ''
      switch (provider) {
        case 'mysql':
          databaseUrl = 'mysql://root@localhost:3306/test_db'
          break
        case 'postgresql':
          databaseUrl = 'postgresql://postgres@localhost:5432/test_db'
          break
        case 'sqlite':
          databaseUrl = 'file:./dev.db'
          break
        default:
          databaseUrl = 'postgresql://postgres@localhost:5432/test_db'
      }
      
      const envContent = `# Auto-generated environment file
# Generated by SSOT Codegen

# Database Configuration
DATABASE_URL="${databaseUrl}"

# Server Configuration
PORT=3000
NODE_ENV=development

# Logging
LOG_LEVEL=info
`
      writeFileSync(envPath, envContent, 'utf-8')
      console.log(chalk.green('  ✓ Created .env with test configuration'))
    }
    
    // 2. Install dependencies
    console.log(chalk.gray('\n  📦 Installing dependencies...'))
    execSync('pnpm install --ignore-workspace', { 
      cwd: outputDir, 
      stdio: 'inherit'
    })
    console.log(chalk.green('  ✓ Dependencies installed'))
    
    // 3. Generate Prisma client (use local version)
    console.log(chalk.gray('\n  🔨 Generating Prisma client...'))
    try {
      execSync('pnpm exec prisma generate --schema=prisma/schema.prisma', { 
        cwd: outputDir, 
        stdio: 'inherit'
      })
      console.log(chalk.green('  ✓ Prisma client generated'))
    } catch {
      console.log(chalk.yellow('  ⚠️  Prisma generation failed (install prisma and run: pnpm exec prisma generate)'))
    }
    
    // 4. Run validation tests if requested
    if (runTests) {
      console.log(chalk.gray('\n  🧪 Running validation tests...'))
      try {
        execSync('pnpm test:validate', { 
          cwd: outputDir, 
          stdio: 'inherit'
        })
        console.log(chalk.green('  ✓ All tests passed!'))
      } catch {
        console.log(chalk.yellow('  ⚠️  Some tests failed (this is OK if database is not set up)'))
      }
    }
    
    console.log(chalk.green('\n✅ Project setup complete!\n'))
  } catch (setupError) {
    const err = setupError as Error
    throw new Error(`Setup failed: ${err.message}`)
  }
}

