// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { QuizCreateSchema } from './quiz.create.zod.js'

export const QuizUpdateSchema = QuizCreateSchema.partial()

export type QuizUpdateInput = z.infer<typeof QuizUpdateSchema>
