// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'

export const QuizCreateSchema = z.object({
  title: z.string().min(1, 'title is required'),
  description: z.string().nullable().optional(),
  category: z.string().nullable().optional(),
  estimatedTime: z.number().int().nullable().optional(),
  meta: z.record(z.string(), z.unknown()).optional().default({}),
  createdAt: z.coerce.date().optional().default(new Date())
})

export type QuizCreateInput = z.infer<typeof QuizCreateSchema>
