// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'

export const BlockCreateSchema = z.object({
  createdAt: z.coerce.date().optional().default(new Date())
})

export type BlockCreateInput = z.infer<typeof BlockCreateSchema>
