// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'

export const BlockQuerySchema = z.object({
  skip: z.coerce.number().min(0).optional(),
  take: z.coerce.number().min(1).max(100).optional().default(20),
  orderBy: z.object({
    id: z.enum(['asc', 'desc']).optional(),
    blockerId: z.enum(['asc', 'desc']).optional(),
    blockedId: z.enum(['asc', 'desc']).optional(),
    createdAt: z.enum(['asc', 'desc']).optional(),
    blocker: z.record(z.enum(['asc', 'desc'])).optional(),
    blocked: z.record(z.enum(['asc', 'desc'])).optional()
  }).optional(),
  where: z.object({
    id: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    blockerId: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    blockedId: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    createdAt: z.object({
      equals: z.coerce.date().optional(),
      gt: z.coerce.date().optional(),
      gte: z.coerce.date().optional(),
      lt: z.coerce.date().optional(),
      lte: z.coerce.date().optional()
    }).optional()
  }).optional(),
  include: z.object({
    blocker: z.boolean().optional(),
    blocked: z.boolean().optional()
  }).optional(),
  select: z.object({
    id: z.boolean().optional(),
    blockerId: z.boolean().optional(),
    blockedId: z.boolean().optional(),
    createdAt: z.boolean().optional(),
    blocker: z.boolean().optional(),
    blocked: z.boolean().optional()
  }).optional()
})

export type BlockQueryInput = z.infer<typeof BlockQuerySchema>
