// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'

export const CompatibilityScoreQuerySchema = z.object({
  skip: z.coerce.number().min(0).optional(),
  take: z.coerce.number().min(1).max(100).optional().default(20),
  orderBy: z.object({
    id: z.enum(['asc', 'desc']).optional(),
    user1Id: z.enum(['asc', 'desc']).optional(),
    user2Id: z.enum(['asc', 'desc']).optional(),
    overallScore: z.enum(['asc', 'desc']).optional(),
    dimensionBreakdown: z.enum(['asc', 'desc']).optional(),
    calculatedAt: z.enum(['asc', 'desc']).optional(),
    cacheVersion: z.enum(['asc', 'desc']).optional(),
    user1: z.record(z.enum(['asc', 'desc'])).optional(),
    user2: z.record(z.enum(['asc', 'desc'])).optional()
  }).optional(),
  where: z.object({
    id: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    user1Id: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    user2Id: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional()
    }).optional(),
    overallScore: z.object({
      equals: z.number().optional(),
      gt: z.number().optional(),
      gte: z.number().optional(),
      lt: z.number().optional(),
      lte: z.number().optional()
    }).optional(),
    calculatedAt: z.object({
      equals: z.coerce.date().optional(),
      gt: z.coerce.date().optional(),
      gte: z.coerce.date().optional(),
      lt: z.coerce.date().optional(),
      lte: z.coerce.date().optional()
    }).optional(),
    cacheVersion: z.object({
      contains: z.string().optional(),
      startsWith: z.string().optional(),
      endsWith: z.string().optional(),
      equals: z.string().optional(),
      isNull: z.boolean().optional()
    }).optional()
  }).optional(),
  include: z.object({
    user1: z.boolean().optional(),
    user2: z.boolean().optional()
  }).optional(),
  select: z.object({
    id: z.boolean().optional(),
    user1Id: z.boolean().optional(),
    user2Id: z.boolean().optional(),
    overallScore: z.boolean().optional(),
    dimensionBreakdown: z.boolean().optional(),
    calculatedAt: z.boolean().optional(),
    cacheVersion: z.boolean().optional(),
    user1: z.boolean().optional(),
    user2: z.boolean().optional()
  }).optional()
})

export type CompatibilityScoreQueryInput = z.infer<typeof CompatibilityScoreQuerySchema>
