// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'

export const CompatibilityScoreCreateSchema = z.object({
  overallScore: z.number(),
  dimensionBreakdown: z.record(z.any()),
  calculatedAt: z.coerce.date().optional().default(new Date()),
  cacheVersion: z.string().nullable().optional()
})

export type CompatibilityScoreCreateInput = z.infer<typeof CompatibilityScoreCreateSchema>
