// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { CompatibilityScoreCreateSchema } from './compatibility-score.create.zod.js'

export const CompatibilityScoreUpdateSchema = CompatibilityScoreCreateSchema.partial()

export type CompatibilityScoreUpdateInput = z.infer<typeof CompatibilityScoreUpdateSchema>
