// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'

export const UserDimensionScoreCreateSchema = z.object({
  normalizedScore: z.number().optional(),
  rawScore: z.number().nullable().optional(),
  lastUpdated: z.coerce.date().optional().default(new Date()),
  lastNormalizedAt: z.coerce.date().nullable().optional(),
  createdAt: z.coerce.date().optional().default(new Date())
})

export type UserDimensionScoreCreateInput = z.infer<typeof UserDimensionScoreCreateSchema>
