// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { UserDimensionScoreCreateSchema } from './user-dimension-score.create.zod.js'

export const UserDimensionScoreUpdateSchema = UserDimensionScoreCreateSchema.partial()

export type UserDimensionScoreUpdateInput = z.infer<typeof UserDimensionScoreUpdateSchema>
