// @generated
// This file is automatically generated. Do not edit manually.

import { EventType } from '@prisma/client'

export interface EventWeightConfigReadDTO {
  id: string
  eventType: EventType
  baseWeight: number
  isActive: boolean
  description: string | null
  createdAt: Date
  updatedAt: Date
}
