// @generated
// This file is automatically generated. Do not edit manually.

import { Router, type Router as RouterType } from 'express'
import * as quizController from '@/controllers/quiz/index.js'

export const quizRouter: RouterType = Router()

// List all Quiz records (simple pagination)
quizRouter.get('/', quizController.listQuizs)

// Search Quiz records (complex filtering via POST body)
quizRouter.post('/search', quizController.searchQuizs)

// Get Quiz by ID
quizRouter.get('/:id', quizController.getQuiz)

// Create Quiz
quizRouter.post('/', quizController.createQuiz)

// Update Quiz
quizRouter.put('/:id', quizController.updateQuiz)
quizRouter.patch('/:id', quizController.updateQuiz)

// Delete Quiz
quizRouter.delete('/:id', quizController.deleteQuiz)

// Count Quiz records
quizRouter.get('/meta/count', quizController.countQuizs)

// Bulk operations
quizRouter.post('/bulk/create', quizController.bulkCreateQuizs)
quizRouter.put('/bulk/update', quizController.bulkUpdateQuizs)
quizRouter.delete('/bulk/delete', quizController.bulkDeleteQuizs)

