// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { QuizQuestionType } from '@prisma/client'

export const QuizQuestionCreateSchema = z.object({
  type: z.nativeEnum(QuizQuestionType),
  order: z.number().int(),
  configJson: z.record(z.any()),
  createdAt: z.coerce.date().optional().default(new Date())
})

export type QuizQuestionCreateInput = z.infer<typeof QuizQuestionCreateSchema>
