// @generated
// This file is automatically generated. Do not edit manually.

import type { PersonalityDimensionUpdateInput } from '@/validators/personality-dimension/personality-dimension.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see PersonalityDimensionUpdateSchema in validators
 */
export type PersonalityDimensionUpdateDTO = PersonalityDimensionUpdateInput
