// @generated
// This file is automatically generated. Do not edit manually.

import { EventType, TargetType } from '@prisma/client'

import type { BehaviorEventReadDTO } from './behavior-event.read.dto.js'

type BehaviorEventWhereInput = {
    id?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    eventType?: EventType | {
      equals?: EventType
      in?: EventType[]
      notIn?: EventType[]
      not?: EventType
    }
    targetType?: TargetType | {
      equals?: TargetType
      in?: TargetType[]
      notIn?: TargetType[]
      not?: TargetType
    }
    targetId?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    meta?: Record<string, any>
    processedAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
      isNull?: boolean
    }
    ruleVersion?: string | null | {
      equals?: string | null
      contains?: string | null
      startsWith?: string | null
      endsWith?: string | null
      in?: string | null[]
      notIn?: string | null[]
      not?: string | null
      mode?: 'default' | 'insensitive'
      isNull?: boolean
    }
    createdAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    AND?: BehaviorEventWhereInput[]
    OR?: BehaviorEventWhereInput[]
    NOT?: BehaviorEventWhereInput[]
  }

export interface BehaviorEventQueryDTO {
  skip?: number  // Offset pagination (should be >= 0)
  take?: number  // Limit (should be > 0)
  cursor?: string  // Cursor for cursor-based pagination
  orderBy?: {
    id?: 'asc' | 'desc'
    userId?: 'asc' | 'desc'
    eventType?: 'asc' | 'desc'
    targetType?: 'asc' | 'desc'
    targetId?: 'asc' | 'desc'
    meta?: 'asc' | 'desc'
    processedAt?: 'asc' | 'desc'
    ruleVersion?: 'asc' | 'desc'
    createdAt?: 'asc' | 'desc'
    user?: { [key: string]: 'asc' | 'desc' }
  }
  where?: BehaviorEventWhereInput
  include?: {
    user?: boolean | { include?: any; select?: any }
  }
  select?: {
    id?: boolean
    userId?: boolean
    eventType?: boolean
    targetType?: boolean
    targetId?: boolean
    meta?: boolean
    processedAt?: boolean
    ruleVersion?: boolean
    createdAt?: boolean
    user?: boolean | { select?: any; include?: any }
  }
  distinct?: 'id' | 'eventType' | 'targetType' | 'targetId' | 'meta' | 'processedAt' | 'ruleVersion' | 'createdAt' | Array<'id' | 'eventType' | 'targetType' | 'targetId' | 'meta' | 'processedAt' | 'ruleVersion' | 'createdAt'>
}

export interface BehaviorEventListResponse {
  data: BehaviorEventReadDTO[]
  meta: {
    total: number
    skip: number
    take: number
    hasMore: boolean  // Calculated as: skip + take < total
  }
}
