// @generated
// This file is automatically generated. Do not edit manually.

import type { BehaviorEventCreateInput } from '@/validators/behavior-event/behavior-event.create.zod.js'

/**
 * Create DTO - Derived from Zod schema (single source of truth)
 * @see BehaviorEventCreateSchema in validators
 */
export type BehaviorEventCreateDTO = BehaviorEventCreateInput
