// @generated
// This file is automatically generated. Do not edit manually.

import { DimensionCategory } from '@prisma/client'

import type { PersonalityDimensionReadDTO } from './personality-dimension.read.dto.js'

type PersonalityDimensionWhereInput = {
    id?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    name?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    description?: string | null | {
      equals?: string | null
      contains?: string | null
      startsWith?: string | null
      endsWith?: string | null
      in?: string | null[]
      notIn?: string | null[]
      not?: string | null
      mode?: 'default' | 'insensitive'
      isNull?: boolean
    }
    category?: DimensionCategory | {
      equals?: DimensionCategory
      in?: DimensionCategory[]
      notIn?: DimensionCategory[]
      not?: DimensionCategory
    }
    isActive?: boolean | {
      equals?: boolean
      not?: boolean
    }
    normalizationConfig?: Record<string, any> | null | { isNull?: boolean }
    createdAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    AND?: PersonalityDimensionWhereInput[]
    OR?: PersonalityDimensionWhereInput[]
    NOT?: PersonalityDimensionWhereInput[]
  }

export interface PersonalityDimensionQueryDTO {
  skip?: number  // Offset pagination (should be >= 0)
  take?: number  // Limit (should be > 0)
  cursor?: string  // Cursor for cursor-based pagination
  orderBy?: {
    id?: 'asc' | 'desc'
    name?: 'asc' | 'desc'
    description?: 'asc' | 'desc'
    category?: 'asc' | 'desc'
    isActive?: 'asc' | 'desc'
    normalizationConfig?: 'asc' | 'desc'
    createdAt?: 'asc' | 'desc'
    updatedAt?: 'asc' | 'desc'
    userDimensionScores?: { [key: string]: 'asc' | 'desc' }
    dimensionMappingRules?: { [key: string]: 'asc' | 'desc' }
    userDimensionPriorities?: { [key: string]: 'asc' | 'desc' }
  }
  where?: PersonalityDimensionWhereInput
  include?: {
    userDimensionScores?: boolean | { include?: any; select?: any }
    dimensionMappingRules?: boolean | { include?: any; select?: any }
    userDimensionPriorities?: boolean | { include?: any; select?: any }
  }
  select?: {
    id?: boolean
    name?: boolean
    description?: boolean
    category?: boolean
    isActive?: boolean
    normalizationConfig?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    userDimensionScores?: boolean | { select?: any; include?: any }
    dimensionMappingRules?: boolean | { select?: any; include?: any }
    userDimensionPriorities?: boolean | { select?: any; include?: any }
  }
  distinct?: 'id' | 'name' | 'description' | 'category' | 'isActive' | 'normalizationConfig' | 'createdAt' | Array<'id' | 'name' | 'description' | 'category' | 'isActive' | 'normalizationConfig' | 'createdAt'>
}

export interface PersonalityDimensionListResponse {
  data: PersonalityDimensionReadDTO[]
  meta: {
    total: number
    skip: number
    take: number
    hasMore: boolean  // Calculated as: skip + take < total
  }
}
