// @generated
// This file is automatically generated. Do not edit manually.

import { DimensionCategory } from '@prisma/client'

export interface PersonalityDimensionReadDTO {
  id: string
  name: string
  description: string | null
  category: DimensionCategory
  isActive: boolean
  normalizationConfig: Record<string, any> | null
  createdAt: Date
  updatedAt: Date
}
