// @generated
// This file is automatically generated. Do not edit manually.

import {
  BaseCRUDController
} from '../../base/index.js'
import { quizQuestionService } from '../../services/quiz-question/index.js'
import {
  QuizQuestionCreateSchema,
  QuizQuestionUpdateSchema,
  QuizQuestionQuerySchema
} from '../../validators/quiz-question/index.js'

/**
 * QuizQuestion CRUD Controller
 * Using BaseCRUDController to eliminate boilerplate
 */
const quizQuestionCRUD = new BaseCRUDController(
  quizQuestionService,
  {
    create: QuizQuestionCreateSchema,
    update: QuizQuestionUpdateSchema,
    query: QuizQuestionQuerySchema
  } as any,
  {
    modelName: 'QuizQuestion',
    idType: 'string'
  }
)


// Standard CRUD operations
export const listQuizQuestions = quizQuestionCRUD.list.bind(quizQuestionCRUD)
export const searchQuizQuestions = quizQuestionCRUD.search.bind(quizQuestionCRUD)
export const getQuizQuestion = quizQuestionCRUD.getById.bind(quizQuestionCRUD)
export const createQuizQuestion = quizQuestionCRUD.create.bind(quizQuestionCRUD)
export const updateQuizQuestion = quizQuestionCRUD.update.bind(quizQuestionCRUD)
export const deleteQuizQuestion = quizQuestionCRUD.deleteRecord.bind(quizQuestionCRUD)
export const countQuizQuestions = quizQuestionCRUD.count.bind(quizQuestionCRUD)

// Bulk operations
export const bulkCreateQuizQuestions = quizQuestionCRUD.bulkCreate.bind(quizQuestionCRUD)
export const bulkUpdateQuizQuestions = quizQuestionCRUD.bulkUpdate.bind(quizQuestionCRUD)
export const bulkDeleteQuizQuestions = quizQuestionCRUD.bulkDelete.bind(quizQuestionCRUD)
