// @generated
// This file is automatically generated. Do not edit manually.

import type { CompatibilityScoreCreateInput } from '@/validators/compatibility-score/compatibility-score.create.zod.js'

/**
 * Create DTO - Derived from Zod schema (single source of truth)
 * @see CompatibilityScoreCreateSchema in validators
 */
export type CompatibilityScoreCreateDTO = CompatibilityScoreCreateInput
