// @generated
// This file is automatically generated. Do not edit manually.

import type { CompatibilityScoreReadDTO } from './compatibility-score.read.dto.js'

type CompatibilityScoreWhereInput = {
    id?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    overallScore?: number | {
      equals?: number
      gt?: number
      gte?: number
      lt?: number
      lte?: number
      in?: number[]
      notIn?: number[]
      not?: number
    }
    dimensionBreakdown?: Record<string, any>
    calculatedAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    cacheVersion?: string | null | {
      equals?: string | null
      contains?: string | null
      startsWith?: string | null
      endsWith?: string | null
      in?: string | null[]
      notIn?: string | null[]
      not?: string | null
      mode?: 'default' | 'insensitive'
      isNull?: boolean
    }
    AND?: CompatibilityScoreWhereInput[]
    OR?: CompatibilityScoreWhereInput[]
    NOT?: CompatibilityScoreWhereInput[]
  }

export interface CompatibilityScoreQueryDTO {
  skip?: number  // Offset pagination (should be >= 0)
  take?: number  // Limit (should be > 0)
  cursor?: string  // Cursor for cursor-based pagination
  orderBy?: {
    id?: 'asc' | 'desc'
    user1Id?: 'asc' | 'desc'
    user2Id?: 'asc' | 'desc'
    overallScore?: 'asc' | 'desc'
    dimensionBreakdown?: 'asc' | 'desc'
    calculatedAt?: 'asc' | 'desc'
    cacheVersion?: 'asc' | 'desc'
    user1?: { [key: string]: 'asc' | 'desc' }
    user2?: { [key: string]: 'asc' | 'desc' }
  }
  where?: CompatibilityScoreWhereInput
  include?: {
    user1?: boolean | { include?: any; select?: any }
    user2?: boolean | { include?: any; select?: any }
  }
  select?: {
    id?: boolean
    user1Id?: boolean
    user2Id?: boolean
    overallScore?: boolean
    dimensionBreakdown?: boolean
    calculatedAt?: boolean
    cacheVersion?: boolean
    user1?: boolean | { select?: any; include?: any }
    user2?: boolean | { select?: any; include?: any }
  }
  distinct?: 'id' | 'overallScore' | 'dimensionBreakdown' | 'calculatedAt' | 'cacheVersion' | Array<'id' | 'overallScore' | 'dimensionBreakdown' | 'calculatedAt' | 'cacheVersion'>
}

export interface CompatibilityScoreListResponse {
  data: CompatibilityScoreReadDTO[]
  meta: {
    total: number
    skip: number
    take: number
    hasMore: boolean  // Calculated as: skip + take < total
  }
}
