// @generated
// This file is automatically generated. Do not edit manually.

import { Router, type Router as RouterType } from 'express'
import * as behaviorEventController from '@/controllers/behavior-event/index.js'

export const behaviorEventRouter: RouterType = Router()

// List all BehaviorEvent records (simple pagination)
behaviorEventRouter.get('/', behaviorEventController.listBehaviorEvents)

// Search BehaviorEvent records (complex filtering via POST body)
behaviorEventRouter.post('/search', behaviorEventController.searchBehaviorEvents)

// Get BehaviorEvent by ID
behaviorEventRouter.get('/:id', behaviorEventController.getBehaviorEvent)

// Create BehaviorEvent
behaviorEventRouter.post('/', behaviorEventController.createBehaviorEvent)

// Update BehaviorEvent
behaviorEventRouter.put('/:id', behaviorEventController.updateBehaviorEvent)
behaviorEventRouter.patch('/:id', behaviorEventController.updateBehaviorEvent)

// Delete BehaviorEvent
behaviorEventRouter.delete('/:id', behaviorEventController.deleteBehaviorEvent)

// Count BehaviorEvent records
behaviorEventRouter.get('/meta/count', behaviorEventController.countBehaviorEvents)

// Bulk operations
behaviorEventRouter.post('/bulk/create', behaviorEventController.bulkCreateBehaviorEvents)
behaviorEventRouter.put('/bulk/update', behaviorEventController.bulkUpdateBehaviorEvents)
behaviorEventRouter.delete('/bulk/delete', behaviorEventController.bulkDeleteBehaviorEvents)

