// @generated
// This file is automatically generated. Do not edit manually.

import { QuizQuestionType } from '@prisma/client'

export interface QuizQuestionReadDTO {
  id: string
  quizId: string
  type: QuizQuestionType
  order: number
  configJson: Record<string, any>
  createdAt: Date
}
