// @generated
// This file is automatically generated. Do not edit manually.

import type { QuizQuestionCreateInput } from '@/validators/quiz-question/quiz-question.create.zod.js'

/**
 * Create DTO - Derived from Zod schema (single source of truth)
 * @see QuizQuestionCreateSchema in validators
 */
export type QuizQuestionCreateDTO = QuizQuestionCreateInput
