// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { Gender, BodyType } from '@prisma/client'

export const ProfileCreateSchema = z.object({
  name: z.string().min(1, 'name is required'),
  age: z.number().int(),
  gender: z.nativeEnum(Gender),
  bio: z.string().nullable().optional(),
  location: z.record(z.string(), z.unknown()),
  ethnicity: z.string().nullable().optional(),
  height: z.number().int().nullable().optional(),
  bodyType: z.nativeEnum(BodyType).nullable().optional(),
  eyeColor: z.string().nullable().optional(),
  hairColor: z.string().nullable().optional(),
  education: z.string().nullable().optional(),
  occupation: z.string().nullable().optional(),
  meta: z.record(z.string(), z.unknown()).optional().default({}),
  createdAt: z.coerce.date().optional().default(new Date())
})

export type ProfileCreateInput = z.infer<typeof ProfileCreateSchema>
