// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { ProfileCreateSchema } from './profile.create.zod.js'

export const ProfileUpdateSchema = ProfileCreateSchema.partial()

export type ProfileUpdateInput = z.infer<typeof ProfileUpdateSchema>
