// @generated
// This file is automatically generated. Do not edit manually.

export interface PhotoReadDTO {
  id: string
  userId: string
  url: string
  order: number
  moderationStatus: string
  createdAt: Date
  updatedAt: Date
}
