// @generated
// This file is automatically generated. Do not edit manually.

import type { PhotoUpdateInput } from '@/validators/photo/photo.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see PhotoUpdateSchema in validators
 */
export type PhotoUpdateDTO = PhotoUpdateInput
