// @generated
// This file is automatically generated. Do not edit manually.

import type { UserDimensionPriorityReadDTO } from './user-dimension-priority.read.dto.js'

type UserDimensionPriorityWhereInput = {
    id?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    weight?: number | {
      equals?: number
      gt?: number
      gte?: number
      lt?: number
      lte?: number
      in?: number[]
      notIn?: number[]
      not?: number
    }
    createdAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    AND?: UserDimensionPriorityWhereInput[]
    OR?: UserDimensionPriorityWhereInput[]
    NOT?: UserDimensionPriorityWhereInput[]
  }

export interface UserDimensionPriorityQueryDTO {
  skip?: number  // Offset pagination (should be >= 0)
  take?: number  // Limit (should be > 0)
  cursor?: string  // Cursor for cursor-based pagination
  orderBy?: {
    id?: 'asc' | 'desc'
    userId?: 'asc' | 'desc'
    dimensionId?: 'asc' | 'desc'
    weight?: 'asc' | 'desc'
    createdAt?: 'asc' | 'desc'
    updatedAt?: 'asc' | 'desc'
    user?: { [key: string]: 'asc' | 'desc' }
    dimension?: { [key: string]: 'asc' | 'desc' }
  }
  where?: UserDimensionPriorityWhereInput
  include?: {
    user?: boolean | { include?: any; select?: any }
    dimension?: boolean | { include?: any; select?: any }
  }
  select?: {
    id?: boolean
    userId?: boolean
    dimensionId?: boolean
    weight?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    user?: boolean | { select?: any; include?: any }
    dimension?: boolean | { select?: any; include?: any }
  }
  distinct?: 'id' | 'weight' | 'createdAt' | Array<'id' | 'weight' | 'createdAt'>
}

export interface UserDimensionPriorityListResponse {
  data: UserDimensionPriorityReadDTO[]
  meta: {
    total: number
    skip: number
    take: number
    hasMore: boolean  // Calculated as: skip + take < total
  }
}
