// @generated
// This file is automatically generated. Do not edit manually.

export interface UserDimensionPriorityReadDTO {
  id: string
  userId: string
  dimensionId: string
  weight: number
  createdAt: Date
  updatedAt: Date
}
