// @generated
// This file is automatically generated. Do not edit manually.

import type { SwipeUpdateInput } from '@/validators/swipe/swipe.update.zod.js'

/**
 * Update DTO - Derived from Zod schema (single source of truth)
 * @see SwipeUpdateSchema in validators
 */
export type SwipeUpdateDTO = SwipeUpdateInput
