// @generated
// This file is automatically generated. Do not edit manually.

import type { SwipeCreateInput } from '@/validators/swipe/swipe.create.zod.js'

/**
 * Create DTO - Derived from Zod schema (single source of truth)
 * @see SwipeCreateSchema in validators
 */
export type SwipeCreateDTO = SwipeCreateInput
