// @generated
// This file is automatically generated. Do not edit manually.

import type { UserDimensionScoreCreateInput } from '@/validators/user-dimension-score/user-dimension-score.create.zod.js'

/**
 * Create DTO - Derived from Zod schema (single source of truth)
 * @see UserDimensionScoreCreateSchema in validators
 */
export type UserDimensionScoreCreateDTO = UserDimensionScoreCreateInput
