// @generated
// This file is automatically generated. Do not edit manually.

import type { UserDimensionScoreReadDTO } from './user-dimension-score.read.dto.js'

type UserDimensionScoreWhereInput = {
    id?: string | {
      equals?: string
      contains?: string
      startsWith?: string
      endsWith?: string
      in?: string[]
      notIn?: string[]
      not?: string
      mode?: 'default' | 'insensitive'
    }
    normalizedScore?: number | {
      equals?: number
      gt?: number
      gte?: number
      lt?: number
      lte?: number
      in?: number[]
      notIn?: number[]
      not?: number
    }
    rawScore?: number | null | {
      equals?: number | null
      gt?: number | null
      gte?: number | null
      lt?: number | null
      lte?: number | null
      in?: number | null[]
      notIn?: number | null[]
      not?: number | null
      isNull?: boolean
    }
    lastUpdated?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    lastNormalizedAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
      isNull?: boolean
    }
    createdAt?: Date | string | {
      equals?: Date | string
      gt?: Date | string
      gte?: Date | string
      lt?: Date | string
      lte?: Date | string
      in?: Date | string[]
      notIn?: Date | string[]
    }
    AND?: UserDimensionScoreWhereInput[]
    OR?: UserDimensionScoreWhereInput[]
    NOT?: UserDimensionScoreWhereInput[]
  }

export interface UserDimensionScoreQueryDTO {
  skip?: number  // Offset pagination (should be >= 0)
  take?: number  // Limit (should be > 0)
  cursor?: string  // Cursor for cursor-based pagination
  orderBy?: {
    id?: 'asc' | 'desc'
    userId?: 'asc' | 'desc'
    dimensionId?: 'asc' | 'desc'
    normalizedScore?: 'asc' | 'desc'
    rawScore?: 'asc' | 'desc'
    lastUpdated?: 'asc' | 'desc'
    lastNormalizedAt?: 'asc' | 'desc'
    createdAt?: 'asc' | 'desc'
    updatedAt?: 'asc' | 'desc'
    user?: { [key: string]: 'asc' | 'desc' }
    dimension?: { [key: string]: 'asc' | 'desc' }
  }
  where?: UserDimensionScoreWhereInput
  include?: {
    user?: boolean | { include?: any; select?: any }
    dimension?: boolean | { include?: any; select?: any }
  }
  select?: {
    id?: boolean
    userId?: boolean
    dimensionId?: boolean
    normalizedScore?: boolean
    rawScore?: boolean
    lastUpdated?: boolean
    lastNormalizedAt?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    user?: boolean | { select?: any; include?: any }
    dimension?: boolean | { select?: any; include?: any }
  }
  distinct?: 'id' | 'normalizedScore' | 'rawScore' | 'lastUpdated' | 'lastNormalizedAt' | 'createdAt' | Array<'id' | 'normalizedScore' | 'rawScore' | 'lastUpdated' | 'lastNormalizedAt' | 'createdAt'>
}

export interface UserDimensionScoreListResponse {
  data: UserDimensionScoreReadDTO[]
  meta: {
    total: number
    skip: number
    take: number
    hasMore: boolean  // Calculated as: skip + take < total
  }
}
