// @generated
// This file is automatically generated. Do not edit manually.

export interface UserDimensionScoreReadDTO {
  id: string
  userId: string
  dimensionId: string
  normalizedScore: number
  rawScore: number | null
  lastUpdated: Date
  lastNormalizedAt: Date | null
  createdAt: Date
  updatedAt: Date
}
