// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'
import { MatchCreateSchema } from './match.create.zod.js'

export const MatchUpdateSchema = MatchCreateSchema.partial()

export type MatchUpdateInput = z.infer<typeof MatchUpdateSchema>
