// @generated
// This file is automatically generated. Do not edit manually.

import { z } from 'zod'

export const MatchCreateSchema = z.object({
  createdAt: z.coerce.date().optional().default(new Date()),
  unmatchedAt: z.coerce.date().nullable().optional()
})

export type MatchCreateInput = z.infer<typeof MatchCreateSchema>
