// @generated
// This file is automatically generated. Do not edit manually.

import { Router, type Router as RouterType } from 'express'
import * as userDimensionScoreController from '@/controllers/user-dimension-score/index.js'

export const userDimensionScoreRouter: RouterType = Router()

// List all UserDimensionScore records (simple pagination)
userDimensionScoreRouter.get('/', userDimensionScoreController.listUserDimensionScores)

// Search UserDimensionScore records (complex filtering via POST body)
userDimensionScoreRouter.post('/search', userDimensionScoreController.searchUserDimensionScores)

// Get UserDimensionScore by ID
userDimensionScoreRouter.get('/:id', userDimensionScoreController.getUserDimensionScore)

// Create UserDimensionScore
userDimensionScoreRouter.post('/', userDimensionScoreController.createUserDimensionScore)

// Update UserDimensionScore
userDimensionScoreRouter.put('/:id', userDimensionScoreController.updateUserDimensionScore)
userDimensionScoreRouter.patch('/:id', userDimensionScoreController.updateUserDimensionScore)

// Delete UserDimensionScore
userDimensionScoreRouter.delete('/:id', userDimensionScoreController.deleteUserDimensionScore)

// Count UserDimensionScore records
userDimensionScoreRouter.get('/meta/count', userDimensionScoreController.countUserDimensionScores)

// Bulk operations
userDimensionScoreRouter.post('/bulk/create', userDimensionScoreController.bulkCreateUserDimensionScores)
userDimensionScoreRouter.put('/bulk/update', userDimensionScoreController.bulkUpdateUserDimensionScores)
userDimensionScoreRouter.delete('/bulk/delete', userDimensionScoreController.bulkDeleteUserDimensionScores)

