// @generated
// This file is automatically generated. Do not edit manually.

import { BaseAPIClient, createAuthInterceptor, type RequestConfig } from '@ssot-codegen/sdk-runtime'
import { UserClient } from './models/user.client.js'
import { ProfileClient } from './models/profile.client.js'
import { PhotoClient } from './models/photo.client.js'
import { MessageClient } from './models/message.client.js'
import { QuizClient } from './models/quiz.client.js'
import { QuizQuestionClient } from './models/quizquestion.client.js'
import { QuizAnswerClient } from './models/quizanswer.client.js'
import { QuizResultClient } from './models/quizresult.client.js'
import { BehaviorEventClient } from './models/behaviorevent.client.js'
import { BehaviorEventArchiveClient } from './models/behavioreventarchive.client.js'
import { PersonalityDimensionClient } from './models/personalitydimension.client.js'
import { UserDimensionScoreClient } from './models/userdimensionscore.client.js'
import { CompatibilityScoreClient } from './models/compatibilityscore.client.js'
import { DimensionMappingRuleClient } from './models/dimensionmappingrule.client.js'
import { EventWeightConfigClient } from './models/eventweightconfig.client.js'
import { DiscoveryServiceClient } from './services/discovery-service.client.js'
import { AdminConfigServiceClient } from './services/admin-config-service.client.js'

export interface SDKConfig {
  baseUrl: string
  auth?: {
    token?: string | (() => string | Promise<string>)
    refreshToken?: string | (() => string | Promise<string>)
    onRefresh?: (newToken: string) => void | Promise<void>
    header?: string
    scheme?: string
  }
  timeout?: number
  retries?: number
  headers?: Record<string, string>
  onRequest?: (init: RequestInit) => Promise<RequestInit> | RequestInit
  onResponse?: (response: Response) => Promise<Response> | Response
  onError?: (error: Error | { status: number; message: string }) => Promise<void> | void
}

/**
 * Create type-safe SDK client
 * 
 * @example
 * ```typescript
 * const api = createSDK({
 *   baseUrl: 'http://localhost:3000',
 *   auth: { token: () => localStorage.getItem('jwt') }
 * })
 * 
 * // Model clients:
 * const posts = await api.posts.list({ skip: 0, take: 20 })
 * const post = await api.posts.get(123)
 * 
 * // Service clients:
 * await api.aiAgent.sendMessage({ prompt: 'Hello!' })
 * await api.fileStorage.uploadFile(formData)
 * ```
 */
export function createSDK(config: SDKConfig) {
  // Create base client
  const client = new BaseAPIClient({
    baseUrl: config.baseUrl,
    timeout: config.timeout,
    retries: config.retries,
    headers: config.headers,
    onRequest: config.auth
      ? createAuthInterceptor(config.auth)
      : config.onRequest,
    onResponse: config.onResponse,
    onError: config.onError
  })

  // Return model + service clients
  return {
    user: new UserClient(client),
    profile: new ProfileClient(client),
    photo: new PhotoClient(client),
    message: new MessageClient(client),
    quiz: new QuizClient(client),
    quizquestion: new QuizQuestionClient(client),
    quizanswer: new QuizAnswerClient(client),
    quizresult: new QuizResultClient(client),
    behaviorevent: new BehaviorEventClient(client),
    behavioreventarchive: new BehaviorEventArchiveClient(client),
    personalitydimension: new PersonalityDimensionClient(client),
    userdimensionscore: new UserDimensionScoreClient(client),
    compatibilityscore: new CompatibilityScoreClient(client),
    dimensionmappingrule: new DimensionMappingRuleClient(client),
    eventweightconfig: new EventWeightConfigClient(client),
    discoveryService: new DiscoveryServiceClient(client),
    adminConfigService: new AdminConfigServiceClient(client)
  }
}

/**
 * SDK type (for type annotations)
 */
export interface SDK {
  user: UserClient
  profile: ProfileClient
  photo: PhotoClient
  message: MessageClient
  quiz: QuizClient
  quizquestion: QuizQuestionClient
  quizanswer: QuizAnswerClient
  quizresult: QuizResultClient
  behaviorevent: BehaviorEventClient
  behavioreventarchive: BehaviorEventArchiveClient
  personalitydimension: PersonalityDimensionClient
  userdimensionscore: UserDimensionScoreClient
  compatibilityscore: CompatibilityScoreClient
  dimensionmappingrule: DimensionMappingRuleClient
  eventweightconfig: EventWeightConfigClient
  discoveryService: DiscoveryServiceClient
  adminConfigService: AdminConfigServiceClient
}

// Export for convenience
export type { SDKConfig }
