// @generated
// This file is automatically generated. Do not edit manually.

import prisma from '@/db'
import type { PersonalityDimensionCreateDTO, PersonalityDimensionUpdateDTO, PersonalityDimensionQueryDTO } from '@/contracts/personality-dimension'
import type { Prisma } from '@prisma/client'
import { DimensionCategory } from '@prisma/client'
import { logger } from '@/logger'

export const personalityDimensionService = {
  /**
   * List PersonalityDimension records with pagination
   */
  async list(query: PersonalityDimensionQueryDTO) {
    const { skip = 0, take = 20, orderBy, where, include, select } = query
    
    logger.debug({ skip, take }, 'Listing PersonalityDimension records')
    
    const whereWithSoftDelete = where
    
    const [items, total] = await Promise.all([
      prisma.personalityDimension.findMany({
        skip,
        take,
        ...(orderBy && { orderBy: orderBy as Prisma.PersonalityDimensionOrderByWithRelationInput }),
        ...(whereWithSoftDelete && { where: whereWithSoftDelete as Prisma.PersonalityDimensionWhereInput }),
        ...(include && { include: include as Prisma.PersonalityDimensionInclude }),
        ...(select && { select: select as Prisma.PersonalityDimensionSelect })
      }),
      prisma.personalityDimension.count({
        where: whereWithSoftDelete as Prisma.PersonalityDimensionWhereInput,
      })
    ])
    
    return {
      data: items,
      meta: {
        total,
        skip,
        take,
        hasMore: skip + take < total
      }
    }
  },
  
  /**
   * Find PersonalityDimension by ID
   */
  async findById(id: string) {
    return prisma.personalityDimension.findUnique({
      where: { id }
    })
  },
  
  /**
   * Create PersonalityDimension
   */
  async create(data: Prisma.PersonalityDimensionCreateInput) {
    const item = await prisma.personalityDimension.create({
      data
    })
    logger.info({ personalityDimensionId: item.id }, 'PersonalityDimension created')
    return item
  },
  
  /**
   * Update PersonalityDimension
   */
  async update(id: string, data: PersonalityDimensionUpdateDTO) {
    const item = await prisma.personalityDimension.update({
      where: { id },
      data: data as Prisma.PersonalityDimensionUpdateInput
    })
    logger.info({ personalityDimensionId: id }, 'PersonalityDimension updated')
    return item
  },
  
  /**
   * Delete PersonalityDimension
   */
  async delete(id: string) {
    await prisma.personalityDimension.delete({
      where: { id }
    })
    logger.info({ personalityDimensionId: id }, 'PersonalityDimension deleted')
    return true
  },
  
  /**
   * Count PersonalityDimension records
   */
  async count(where?: Prisma.PersonalityDimensionWhereInput) {
    return prisma.personalityDimension.count({ where })
  },
  
  /**
   * Check if PersonalityDimension exists
   */
  async exists(id: string) {
    const count = await prisma.personalityDimension.count({
      where: { id }
    })
    return count > 0
  },
  
  /**
   * Create multiple PersonalityDimension records (bulk operation)
   */
  async createMany(data: Prisma.PersonalityDimensionCreateManyInput[]) {
    const result = await prisma.personalityDimension.createMany({
      data,
      skipDuplicates: true
    })
    logger.info({ count: result.count }, 'PersonalityDimension bulk created')
    return result
  },
  
  /**
   * Update multiple PersonalityDimension records (bulk operation)
   */
  async updateMany(where: Prisma.PersonalityDimensionWhereInput, data: Prisma.PersonalityDimensionUpdateManyMutationInput) {
    const result = await prisma.personalityDimension.updateMany({
      where,
      data
    })
    logger.info({ count: result.count }, 'PersonalityDimension bulk updated')
    return result
  },
  
  /**
   * Delete multiple PersonalityDimension records (bulk operation)
   */
  async deleteMany(where: Prisma.PersonalityDimensionWhereInput) {
    const result = await prisma.personalityDimension.deleteMany({ where })
    logger.info({ count: result.count }, 'PersonalityDimension bulk deleted')
    return result
  },

  /**
   * Search PersonalityDimensions with text query and filters
   * Auto-generated from searchable fields: name, description
   */
  async search(params: {
    q: string
    name?: string
    description?: string
    category?: DimensionCategory
    isActive?: boolean
    minCreatedAt?: Date | string
    maxCreatedAt?: Date | string
    skip?: number
    take?: number
  }) {
    const where: Prisma.PersonalityDimensionWhereInput = {
      AND: [
        params.q ? {
          OR: [
            { name: { contains: params.q } },
            { description: { contains: params.q } }
          ]
        } : {},
        params.name ? { name: params.name } : {},
        params.description ? { description: params.description } : {},
        params.category ? { category: params.category } : {},
        params.isActive !== undefined ? { isActive: params.isActive } : {},
        params.minCreatedAt ? { createdAt: { gte: params.minCreatedAt } } : {},
        params.maxCreatedAt ? { createdAt: { lte: params.maxCreatedAt } } : {}
      ].filter(condition => Object.keys(condition).length > 0)
    }
    
    return prisma.personalityDimension.findMany({
      where,
      skip: params.skip || 0,
      take: Math.min(params.take || 20, 100)
    })
  },

  /**
   * Get active PersonalityDimensions
   * Auto-generated from 'isActive' field detection
   */
  async getActive(query?: Prisma.PersonalityDimensionWhereInput) {
    return prisma.personalityDimension.findMany({
      where: {
        isActive: true,
        ...query
      }
    })
  }
}
