// @generated
// This file is automatically generated. Do not edit manually.

import prisma from '@/db'
import type { PhotoCreateDTO, PhotoUpdateDTO, PhotoQueryDTO } from '@/contracts/photo'
import type { Prisma } from '@prisma/client'
import { logger } from '@/logger'

export const photoService = {
  /**
   * List Photo records with pagination and relationships
   */
  async list(query: PhotoQueryDTO) {
    const { skip = 0, take = 20, orderBy, where } = query
    
    logger.debug({ skip, take }, 'Listing Photo records')
    
    const whereWithSoftDelete = where
    
    const [items, total] = await Promise.all([
      prisma.photo.findMany({
        skip,
        take,
        orderBy: orderBy as Prisma.PhotoOrderByWithRelationInput,
        where: whereWithSoftDelete as Prisma.PhotoWhereInput,
      include: {
        user: {
          select: { id: true, email: true }
        }
      }
      }),
      prisma.photo.count({
        where: whereWithSoftDelete as Prisma.PhotoWhereInput,
      })
    ])
    
    return {
      data: items,
      meta: {
        total,
        skip,
        take,
        hasMore: skip + take < total
      }
    }
  },
  
  /**
   * Find Photo by ID with relationships
   */
  async findById(id: string) {
    return prisma.photo.findUnique({
      where: { id },
      include: {
        user: {
          select: { id: true, email: true }
        }
      }
    })
  },
  
  /**
   * Create Photo
   */
  async create(data: Prisma.PhotoCreateInput) {
    const item = await prisma.photo.create({
      data,
      include: {
        user: {
          select: { id: true, email: true }
        }
      }
    })
    logger.info({ photoId: item.id }, 'Photo created')
    return item
  },
  
  /**
   * Update Photo
   */
  async update(id: string, data: PhotoUpdateDTO) {
    const item = await prisma.photo.update({
      where: { id },
      data: data as Prisma.PhotoUpdateInput,
      include: {
        user: {
          select: { id: true, email: true }
        }
      }
    })
    logger.info({ photoId: id }, 'Photo updated')
    return item
  },
  
  /**
   * Delete Photo
   */
  async delete(id: string) {
    await prisma.photo.delete({
      where: { id }
    })
    logger.info({ photoId: id }, 'Photo deleted')
    return true
  },
  
  /**
   * Count Photo records
   */
  async count(where?: Prisma.PhotoWhereInput) {
    return prisma.photo.count({ where })
  },
  
  /**
   * Check if Photo exists
   */
  async exists(id: string) {
    const count = await prisma.photo.count({
      where: { id }
    })
    return count > 0
  },
  
  /**
   * Create multiple Photo records (bulk operation)
   */
  async createMany(data: Prisma.PhotoCreateManyInput[]) {
    const result = await prisma.photo.createMany({
      data,
      skipDuplicates: true
    })
    logger.info({ count: result.count }, 'Photo bulk created')
    return result
  },
  
  /**
   * Update multiple Photo records (bulk operation)
   */
  async updateMany(where: Prisma.PhotoWhereInput, data: Prisma.PhotoUpdateManyMutationInput) {
    const result = await prisma.photo.updateMany({
      where,
      data
    })
    logger.info({ count: result.count }, 'Photo bulk updated')
    return result
  },
  
  /**
   * Delete multiple Photo records (bulk operation)
   */
  async deleteMany(where: Prisma.PhotoWhereInput) {
    const result = await prisma.photo.deleteMany({ where })
    logger.info({ count: result.count }, 'Photo bulk deleted')
    return result
  },

  /**
   * Search Photos with text query and filters
   * Auto-generated from searchable fields: url, moderationStatus
   */
  async search(params: {
    q: string
    url?: string
    minOrder?: number
    maxOrder?: number
    moderationStatus?: string
    minCreatedAt?: Date | string
    maxCreatedAt?: Date | string
    skip?: number
    take?: number
  }) {
    const where: Prisma.PhotoWhereInput = {
      AND: [
        params.q ? {
          OR: [
            { url: { contains: params.q } },
            { moderationStatus: { contains: params.q } }
          ]
        } : {},
        params.url ? { url: params.url } : {},
        params.minOrder ? { order: { gte: params.minOrder } } : {},
        params.maxOrder ? { order: { lte: params.maxOrder } } : {},
        params.moderationStatus ? { moderationStatus: params.moderationStatus } : {},
        params.minCreatedAt ? { createdAt: { gte: params.minCreatedAt } } : {},
        params.maxCreatedAt ? { createdAt: { lte: params.maxCreatedAt } } : {}
      ].filter(condition => Object.keys(condition).length > 0)
    }
    
    return prisma.photo.findMany({
      where,
      skip: params.skip || 0,
      take: Math.min(params.take || 20, 100)
    })
  },

  /**
   * Get Photos by PhotoToUser
   * Auto-generated from foreign key detection: userId
   */
  async getByPhotoToUser(userId: string, options?: {
    skip?: number
    take?: number
  }) {
    return prisma.photo.findMany({
      where: { userId },
      skip: options?.skip || 0,
      take: options?.take || 20
    })
  }
}
